### ISSUE TITLE
Reports totally unusable

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1024]
with the latest changes in TLF (and RE?) reports are absolutely unusable.
E.g. compare the [report created few days ago (RE 2.1.244 TLF 1.5.126)](https://github.com/Yuri05/Digoxin-Model/blob/review/Evaluation/report/report.md) vs. the same [report created right now with RE 2.2.252 and TLF 1.5.131](https://github.com/Yuri05/Test_Digoxin/blob/main/Evaluation/report/report.md)
* Axes labes are too small and unreadable (applies to all typesof plots, e.g. also to the DDI-Ratio plots etc.)
* Axes tick labels are too small and unreadable (applies to all typesof plots)
* Curve captions in the plots are too small and unreadable (but even being too small it's splitted into several lines, which would be not required here) (applies to all typesof plots
![grafik](https://user-images.githubusercontent.com/25061876/227731365-e5817e51-7cb1-4a70-8462-ef1bafeaf3da.png)
* Symbols are too small (in another report I could not even find the symbols at all in the DDI-plots) (applies to all typesof plots
* Identity line in GOF plots is missing

While the issue with the symbol size can be explained with the latest changes regarding the shapes in the tlf (and we have an [issue for increasing the default symbol size](https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/437) already), I have no idea why all the other problems suddenly appear.

**Comment by pchelle** [comment]
I did not expect this side effect...
The issue is because of the new package `{showtext}` that translates the glyphs as images.
It seems the solution is using the same dots per inches argument as the one set up by the RE: [`showtext_opts(dpi = 300)`](https://github.com/yixuan/showtext/issues/51)

Not sure if the option should be set up in RE, TLF or both ?
@Yuri05 , thoughts ?

**Comment by pchelle** [comment]
GOF identity missing line is related to PR [418](https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/418) from TLF.
The identity line was removed from the default configuration then.
