### ISSUE TITLE
Mass balance in case of multiple applications

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1039]
Currently the mass balance plots normalize the drug mass by the total final drug mass administered.
However, it does not feels right in case of multiple applications with drug mass as a function of time.
Thoughts ?

Below is an illustration of what this would change:

<details><summary><strong>Usual mass balance plot as Amount of drug vs time</strong></summary>

![Raltegravir_100_mg_filmcoated_tablet_md-1_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md](https://user-images.githubusercontent.com/45343665/234863705-c0d8f4ec-ea0a-444c-8be6-62f07fdeb029.png)

</details>

## Current plot

<details><summary><strong>Normalized mass balance plot normalized by total/final amount of drug</strong></summary>

![Raltegravir_100_mg_filmcoated_tablet_md-3_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md](https://user-images.githubusercontent.com/45343665/234863969-144bb68c-6fdc-4490-99a3-8c92822309ca.png)

</details>

## Suggested updated plot

<details><summary><strong>Normalized mass balance plot normalized by current amount of drug</strong></summary>

![Raltegravir_100_mg_filmcoated_tablet_md-3_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md](https://user-images.githubusercontent.com/45343665/234873287-97ebdb93-3f3b-4d84-ad92-d103e052e26b.png)

</details>

**Comment by Yuri05** [comment]
@sfrechen @AndreDlm @TWendl @Christoph27 Thoughts?

**Comment by sfrechen** [comment]
> Suggested updated plot

like this one. Another idea: mass balance only applicabe for single doses?

**Comment by Christoph27** [comment]
I also agree that the normalized mass balance plot should be normalized by the current amount of drug (as in suggested updated plot)).

**Comment by Yuri05** [comment]
closing in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/1118
