### ISSUE TITLE
Time profiles: missing simulated curves

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#105]
Reporting Engine 1.0.8.

When executing MEanModel-Workflow **Input/win_test-example-02.R** : time profile plots don't show simulated data, only observed
Both input and output are here: [Test01.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4394847/Test01.zip)

**Comment by pchelle** [comment]
Is this the plot you are referring ?
![image](https://user-images.githubusercontent.com/45343665/77934142-a7ce1200-727d-11ea-888d-628ad4f8a7f0.png)

**Comment by pchelle** [comment]
If so, the simulated data are the yellow dots and their value is correct.
The observed data which is in the unitConv column are in fact in µg/L and not mg/L. (I have the exact same values in the original file, but a different unit).

**Comment by msevestre** [comment]
>The observed data which is in the unitConv column are in fact in µg/L and not mg/L. (I have the exact same values in the original file, but a different unit).

What does that mean?

**Comment by Yuri05** [comment]
>Is this the plot you are referring ?

Checked again: other plots were in fact residuals, not time profiles, thus yes, referring to this plot.
Additionally to the question by Michael: the simulated curve should have line type "solid" by default, not "none"

**Comment by pchelle** [comment]
It means that because of the µ unit issue, Juri had to change the units of the script to make it work. 
However, even if the unit was changed, the actual values were not converted in his observed data file.
In my last pull request, I fixed the values within the file they are in mg/l, so it should match better with the simulations

**Comment by pchelle** [comment]
> 
> 
> > Is this the plot you are referring ?
> 
> Checked again: other plots were in fact residuals, not time profiles, thus yes, referring to this plot.
> Additionally to the question by Michael: the simulated curve should have line type "solid" by default, not "none"

Yes, indeed. I am going to add the issue in github

**Comment by Yuri05** [comment]
>I am going to add the issue in github

Thx. Closing the issue then in favor of #110
