### ISSUE TITLE
Log file corrupted

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#106]
Reporting Engine 1.0.8.

Inputs/Outputs - s. #105

suddenly log file is totally corrupted. Wrong are:
 - computer name
 - login
 - user
 - ospsuite package version
 - reproting engine package version

26/03/2020 - 19:43:41 : Reporting Engine Information: 
26/03/2020 - 19:43:41 : Date: 2020-03-25 20:19:18 
26/03/2020 - 19:43:41 : User Information: 
26/03/2020 - 19:43:41 : Computer Name: APPVEYOR-VM 
26/03/2020 - 19:43:41 : User: appveyor 
26/03/2020 - 19:43:41 : Login: appveyor 
26/03/2020 - 19:43:41 : System is  validated 
26/03/2020 - 19:43:41 : System versions: 
26/03/2020 - 19:43:41 : R version: R version 3.6.3 Patched (2020-03-11 r78052) 
26/03/2020 - 19:43:41 : OSP Suite Package version: 9.0.0 
26/03/2020 - 19:43:41 : OSP Reporting Engine version: 1.0.8 
26/03/2020 - 19:43:41 : tlf version: 0.1.0 
26/03/2020 - 19:43:41 : Starting run of mean model workflow
26/03/2020 - 19:43:41 : Starting Perform simulation task
26/03/2020 - 19:43:41 : Run simulation: Raltegravir 10 mg   (lactose formulation)
26/03/2020 - 19:43:47 : Starting: Plot Absorption task in Alpha Testing
26/03/2020 - 19:43:47 : Plot Absorption task in Alpha Testing for Raltegravir 10 mg   (lactose formulation)
26/03/2020 - 19:44:04 : Starting: Plot Mass Balance task in Alpha Testing
26/03/2020 - 19:44:04 : Plot Mass Balance task in Alpha Testing for Raltegravir 10 mg   (lactose formulation)
26/03/2020 - 19:44:22 : Starting: Plot Goodness of Fit task in Alpha Testing
26/03/2020 - 19:44:22 : Plot Goodness of Fit task in Alpha Testing for Raltegravir 10 mg   (lactose formulation)

**Comment by msevestre** [comment]
What's wrong aside from the date?

**Comment by Yuri05** [comment]
s. above. Most infos about compute environment and all package numbers.

26/03/2020 - 19:43:41 : Computer Name: APPVEYOR-VM
26/03/2020 - 19:43:41 : User: appveyor
26/03/2020 - 19:43:41 : Login: appveyor
26/03/2020 - 19:43:41 : OSP Suite Package version: 9.0.0
26/03/2020 - 19:43:41 : OSP Reporting Engine version: 1.0.8
26/03/2020 - 19:43:41 : tlf version: 0.1.0

**Comment by Yuri05** [comment]
I execute it locally and my R installation knows nothing about Appveyor - the info must be cached somewehere (and installed with reporting engine package?).

**Comment by msevestre** [comment]
WHAT!!! How is this possible

**Comment by pchelle** [comment]
I fixed it on my side
If the issue still persists, R help was saying that there was a difference in Linux between Sys.info that we are currently using and Sys.getenv
