### ISSUE TITLE
Training RE users through tutorials

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1081]
A potential cool feature to train Reporting Engine users: https://rstudio.github.io/learnr/

For instance, we could set up one or two mockup workflows and the users could use the playground to test how to change some settings or having some simple multiple choices questions to understand how Workflow works or how to use/tune Excel or Word templates.

Thoughts ?

**Comment by pchelle** [comment]
Just in case, we would like to implement:

- Create the tuto in inst/tutorials: `usethis::use_tutorial`
- Call the tuto from the package using `learnr::run_tutorial` (can be wrapped inside a function) and potentially expose an enum like `Tutorials`

**Comment by AnnikaRPS** [comment]
I think this is nice to have but I am not sure whether these will really help and are worth the effort. Maybe one "Getting started" workflow would be nice. From my point of view, the bigger hurdles come when you want to change specific settings etc. Here, a clear, easily searchable and complete documentation (with some case examples) can be of better help than such interactive workflows, which can only cover small parts. This documentation already exists but could maybe be extended with additional details. Therefore, I would rather focus on the documentation or other tasks. But that is purely my opinion and I don't know how others think about it. Maybe it would be worth to get some more feedback before putting in all the effort.
