### ISSUE TITLE
Ratio comparison: better wording

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1087]
We have 2 PK ratio tables in the report:
1. ratio(X) is simply calculated as `X_Simulation_1/X_Simulation_2`. E.g. `ratio(median) = median_simulation_1/median_simulation_2`
2. ratio(X) is calculated as defined in https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/536#issuecomment-923016901

At the moment the captions of these 2 calculations in a report are very similar and confusing, e.g:
* For case 1:
  * **Table 1-2: Population statistics ratios summarizing C max of Midazolam plasma conc for Midazolam Treatment in comparison to Midazolam Control**
  * **Figure 1-3: C max of Midazolam plasma conc for Midazolam Treatment in comparison to Midazolam Control shown as box-whisker plot, which indicates ratios of the 5th, 25th, 50th, 75th, 95th percentiles**
* For case 2:
  * **Table 1-3: Ratios of C max of Midazolam plasma conc for Midazolam Treatment in comparison to Midazolam Control**

The wording of the captions should be improved.

**Comment by Yuri05** [comment]
@sfrechen @annikarps Any suggestions for wording?

**Comment by AnnikaRPS** [comment]
For case1 it should be clear that the ratios presented are ratios of the summary statistics e.g.:
"Ratio of population summary statistics of cmax of midazolam plasma conc for midazolam treatment in comparison to midazolam control" (for the plot additionally: "shown as box-whisker plot, which indicates ratios of the 5th, 25th, 50th, 75th, 95th percentiles" as you suggested)

For case 2 I would suggest:
"Population summary statistics of cmax ratios of midazolam plasma conc for midazolam treatment in comparison to midazolam control"
Ist there no boxplot for case 2 or did you just leave out the caption?
