### ISSUE TITLE
Inclusion of categorical covariates in demography plots

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1088]
Currently, categorical covariates such as **Gender** are only included in histograms of demography plots but not in range plots.
- Is there value in including them ?
- If so which would be the best plot types (boxplots ?)

**Comment by AnnikaRPS** [comment]
Yes, I think there is a value in including them and I think boxplots could work or if they get to croweded different facets of the range plot
