### ISSUE TITLE
Add time profile plots with y log scale as plot output

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#111]
@Yuri05 let me know if all the plots need to be duplicated with their log-scales versions

**Comment by Yuri05** [comment]
>if all the plots need to be duplicated with their log-scales versions

Yes

**Comment by ThomasGaub** [comment]
The log scale plots are more important then the linear scale plots. 
Any way to change this manual, before they are autmatically added

**Comment by Yuri05** [comment]
@ThomasGaub FYI Matlab-RE creates both log and lin automatically. 
But GoF-Task could get the option `TimeProfileYAxisScaling `or something like this with possible values `Lin `/ `Log `/ `LinAndLog ` (or 2 boolean flags: `TimeProfilePlotInLin`, `TimeProfilePlotInLog` )
@sfrechen @TWendl FYI

**Comment by Yuri05** [comment]
Closing. RE creates currently both plot types (log and lin).
@sfrechen @TWendl If we need an option for "only log/only lin" - this can be added in the next Release of RE.
