### ISSUE TITLE
Nightly Code Coverage: results not properly uploaded

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1111]
According to the output of the GitHub action:
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/c0333d8e-a017-4118-b900-6de5c5de1204)

However [CodeCov-website](https://app.codecov.io/gh/Open-Systems-Pharmacology/OSPSuite.ReportingEngine) shows 
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/86e16b84-aa6a-44a1-91f1-0193b28d5610)

And the shown referenced commit is the one **before** the switch to the GH-Action:
https://app.codecov.io/github/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/commits

At the end of the "test coverage" step, some funny errors are shown:
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/d99282ec-609b-4806-b2ce-c0cd06b8466d)

**Comment by Yuri05** [comment]
@pchelle Looking at the [example](https://github.com/r-lib/actions/blob/v2-branch/examples/test-coverage.yaml): they do not provide any codecov tokens:
https://github.com/r-lib/actions/blob/756399d909bf9c180bbdafe8025f794f51f2da02/examples/test-coverage.yaml#L29-L36

However they pass the GitHub-Token to the action:
https://github.com/r-lib/actions/blob/756399d909bf9c180bbdafe8025f794f51f2da02/examples/test-coverage.yaml#L11-L15

Can you try this?

**Comment by pchelle** [comment]
> Can you try this?

The github token was already included in the GITHUB_PAT https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/7e2880979ed24dcfc00ca91f395403eb69e9aeb4/.github/workflows/codecov-nightly.yml#L12

**Comment by pchelle** [comment]
However, I ran it on windows and not ubuntu, I don't know if there is a difference from codecov run perspective

**Comment by Yuri05** [comment]
> > Can you try this?
> 
> The github token was already included in the GITHUB_PAT
> 
> https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/7e2880979ed24dcfc00ca91f395403eb69e9aeb4/.github/workflows/codecov-nightly.yml#L12

There, the codecov-token was also included in the call of covr(). Can you try with GitHub-Token only, without the codecov-token?
