### ISSUE TITLE
Demography plots / pediatric workflow

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1132]
* <s>the adult reference population should not be shown in the histogram</s>
* in range plots the default should be the reference global range option

**Comment by pchelle** [comment]
> * the adult reference population should not be shown in the histogram

Does this apply for simulated or both observed and simulated populations ?

**Comment by pchelle** [comment]
> > * the adult reference population should not be shown in the histogram
> 
> Does this apply for simulated or both observed and simulated populations ?

I created a separate issue #1145 to fix this
