### ISSUE TITLE
MeanModel/Population workflows: invalid TOC links

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1141]
All subchapter-links in TOC are not working anymore (RE 2.2.303)
E.g. see the example report (MeanModel) here: https://github.com/Yuri05/TestReport/blob/main/00/01_InvalidLinks/Report/Report.md 
(report inputs: https://github.com/Yuri05/TestReport/tree/main/00/01_InvalidLinks )
<img width="500" src="https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/bbe3aec4-1dda-4051-a9c2-d104ceab8c19">

**Comment by pchelle** [comment]
It seems that Github updated the way they preview markdown files.
Because the links work when used in this comment (see below)

**Comment by pchelle** [comment]
# Table of Contents

 * [1 Sensitivity Analysis ](#sensitivity-analysis)
   * [1.1 Sensitivity Analysis for Raltegravir 100 mg filmcoated tablet md ](#sensitivity-analysis-Raltegravir_100_mg_filmcoated_tablet_md)
 * [2 PK parameters ](#pk-parameters)
   * [2.1 PK parameters for Raltegravir 100 mg filmcoated tablet md ](#pk-parameters-Raltegravir_100_mg_filmcoated_tablet_md)
 * [3 Absorption ](#absorption)
   * [3.1 Absorption for Raltegravir 100 mg filmcoated tablet md ](#absorption-Raltegravir_100_mg_filmcoated_tablet_md)
 * [4 Mass Balance ](#mass-balance)
   * [4.1 Mass Balance for Raltegravir 100 mg filmcoated tablet md ](#mass-balance-Raltegravir_100_mg_filmcoated_tablet_md)
 * [5 Time profiles and residual plots ](#time-profiles)
   * [5.1 Time profiles and residual plots for Raltegravir 100 mg filmcoated tablet md ](#time-profiles-Raltegravir_100_mg_filmcoated_tablet_md)
     * [5.1.1 For total simulation time range ](#goodness-of-fit-Raltegravir_100_mg_filmcoated_tablet_md-total)
     * [5.1.2 For first application range ](#goodness-of-fit-Raltegravir_100_mg_filmcoated_tablet_md-first)
     * [5.1.3 For last application range ](#goodness-of-fit-Raltegravir_100_mg_filmcoated_tablet_md-last)





# 1 Sensitivity Analysis <a id="sensitivity-analysis"></a>


## 1.1 Sensitivity Analysis for Raltegravir 100 mg filmcoated tablet md <a id="sensitivity-analysis-Raltegravir_100_mg_filmcoated_tablet_md"></a>


<a id="figure-1-1"></a>

![](Sensitivity/Raltegravir_100_mg_filmcoated_tablet_md-1_sensitivity_C_max.png)



**Figure 1-1: Most sensitive parameters for C_max of Raltegravir.**


<br>
<br>


<a id="figure-1-2"></a>

![](Sensitivity/Raltegravir_100_mg_filmcoated_tablet_md-2_sensitivity_AUC_tD1_tD2.png)



**Figure 1-2: Most sensitive parameters for AUC_t1_t2 of Raltegravir.**


<br>
<br>





# 2 PK parameters <a id="pk-parameters"></a>


## 2.1 PK parameters for Raltegravir 100 mg filmcoated tablet md <a id="pk-parameters-Raltegravir_100_mg_filmcoated_tablet_md"></a>


<a id="table-2-1"></a>

**Table 2-1: PK parameters for Scenario Raltegravir 100 mg filmcoated tablet md**


|Path        |Parameter |Value   |Unit   |
|:-----------|:---------|:-------|:------|
|Raltegravir |C_max     |894.09  |µg/l   |
|Raltegravir |AUC_t1_t2 |1963.32 |µg*h/l |


<br>
<br>





# 3 Absorption <a id="absorption"></a>


## 3.1 Absorption for Raltegravir 100 mg filmcoated tablet md <a id="absorption-Raltegravir_100_mg_filmcoated_tablet_md"></a>


<a id="figure-3-1"></a>

![](Absorption/Raltegravir_100_mg_filmcoated_tablet_md-1_absorption_Raltegravir.png)



**Figure 3-1: Absorption of Raltegravir**


<br>
<br>





# 4 Mass Balance <a id="mass-balance"></a>


## 4.1 Mass Balance for Raltegravir 100 mg filmcoated tablet md <a id="mass-balance-Raltegravir_100_mg_filmcoated_tablet_md"></a>


<a id="figure-4-1"></a>

![](MassBalance/Raltegravir_100_mg_filmcoated_tablet_md-1_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md.png)



**Figure 4-1: Amount of drug vs time within the different compartments**


<br>
<br>


<a id="figure-4-2"></a>

![](MassBalance/Raltegravir_100_mg_filmcoated_tablet_md-2_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md.png)



**Figure 4-2: Cumulated amount of drug vs time within the different compartments**


<br>
<br>


<a id="figure-4-3"></a>

![](MassBalance/Raltegravir_100_mg_filmcoated_tablet_md-3_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md.png)



**Figure 4-3: Amount of drug vs time within the different compartments normalized to applicated drugmass**


<br>
<br>


<a id="figure-4-4"></a>

![](MassBalance/Raltegravir_100_mg_filmcoated_tablet_md-4_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md.png)



**Figure 4-4: Cumulated amount of drug vs time within the different compartments normalized to applicated drugmass**


<br>
<br>


<a id="figure-4-5"></a>

![](MassBalance/Raltegravir_100_mg_filmcoated_tablet_md-5_mass_balance_Raltegravir_100_mg_filmcoated_tablet_md.png)



**Figure 4-5: Fraction of drug within the different compartments at 240.00h**


<br>
<br>





# 5 Time profiles and residual plots <a id="time-profiles"></a>


## 5.1 Time profiles and residual plots for Raltegravir 100 mg filmcoated tablet md <a id="time-profiles-Raltegravir_100_mg_filmcoated_tablet_md"></a>


### 5.1.1 For total simulation time range <a id="goodness-of-fit-Raltegravir_100_mg_filmcoated_tablet_md-total"></a>


<a id="figure-5-1"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-4_timeProfile_Concentration_total.png)



**Figure 5-1: Time profiles for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Time profiles are plotted in a linear scale.**


<br>
<br>


<a id="figure-5-2"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-5_timeProfileLog_Concentration_total.png)



**Figure 5-2: Time profiles for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Time profiles are plotted in a logarithmic scale.**


<br>
<br>


<a id="figure-5-3"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-6_obsVsPred_Concentration_total.png)



**Figure 5-3: Predicted vs observed for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Predictions and observations are plotted in a linear scale.**


<br>
<br>


<a id="figure-5-4"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-7_obsVsPredLog_Concentration_total.png)



**Figure 5-4: Predicted vs observed for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Predictions and observations are plotted in a logarithmic scale.**


<br>
<br>


<a id="figure-5-5"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-8_resVsPred_total.png)



**Figure 5-5: Logarithmic residuals vs predicted values for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


<a id="figure-5-6"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-9_resVsTime_total.png)



**Figure 5-6: Logarithmic residuals vs time values for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


<a id="figure-5-7"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-10_resHisto_total.png)



**Figure 5-7: Logarithmic residuals distribution (stacked) for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


<a id="figure-5-8"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-11_resQQPlot_total.png)



**Figure 5-8: Logarithmic residuals for Scenario Raltegravir 100 mg filmcoated tablet md as quantile-quantile plot. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


### 5.1.2 For first application range <a id="goodness-of-fit-Raltegravir_100_mg_filmcoated_tablet_md-first"></a>


<a id="figure-5-9"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-13_timeProfile_Concentration_firstApplication.png)



**Figure 5-9: Time profiles for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Time profiles are plotted in a linear scale.**


<br>
<br>


<a id="figure-5-10"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-14_timeProfileLog_Concentration_firstApplication.png)



**Figure 5-10: Time profiles for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Time profiles are plotted in a logarithmic scale.**


<br>
<br>


### 5.1.3 For last application range <a id="goodness-of-fit-Raltegravir_100_mg_filmcoated_tablet_md-last"></a>


<a id="figure-5-11"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-16_timeProfile_Concentration_lastApplication.png)



**Figure 5-11: Time profiles for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Time profiles are plotted in a linear scale.**


<br>
<br>


<a id="figure-5-12"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-17_timeProfileLog_Concentration_lastApplication.png)



**Figure 5-12: Time profiles for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Time profiles are plotted in a logarithmic scale.**


<br>
<br>


<a id="figure-5-13"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-18_obsVsPred_Concentration_lastApplication.png)



**Figure 5-13: Predicted vs observed for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Predictions and observations are plotted in a linear scale.**


<br>
<br>


<a id="figure-5-14"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-19_obsVsPredLog_Concentration_lastApplication.png)



**Figure 5-14: Predicted vs observed for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.. Predictions and observations are plotted in a logarithmic scale.**


<br>
<br>


<a id="figure-5-15"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-20_resVsPred_lastApplication.png)



**Figure 5-15: Logarithmic residuals vs predicted values for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


<a id="figure-5-16"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-21_resVsTime_lastApplication.png)



**Figure 5-16: Logarithmic residuals vs time values for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


<a id="figure-5-17"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-22_resHisto_lastApplication.png)



**Figure 5-17: Logarithmic residuals distribution (stacked) for Scenario Raltegravir 100 mg filmcoated tablet md. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>


<a id="figure-5-18"></a>

![](TimeProfiles/Raltegravir_100_mg_filmcoated_tablet_md-23_resQQPlot_lastApplication.png)



**Figure 5-18: Logarithmic residuals for Scenario Raltegravir 100 mg filmcoated tablet md as quantile-quantile plot. Data source: Data/Raltegravir_PK.txt.**


<br>
<br>

**Comment by pchelle** [comment]
I am wondering if this is because of the outline feature of the markdown view that may overwrite our tags ?

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/45343665/4f5ccb3d-f20d-44a7-b34f-426070e3ff3d)

**Comment by Yuri05** [comment]
hmm, but all those problematic links actually refer to our own anchors.

![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/0eb2552c-dace-4d08-a325-ef119966adf7)

just tested the anchor referencing in a test file here: still works. Not sure why it stopped working in our reports...
https://github.com/Yuri05/TestReport/blob/main/test2.md

**Comment by Yuri05** [comment]
works also in other (quali) reports, e.g. here: https://github.com/Yuri05/TestReport/blob/main/Report_10_DDI_UGT/report.md 
hmm

**Comment by Yuri05** [comment]
It seems that GitHub has now problems with ids containing letters in **upper case**
After I changed the first problematic anchor in https://github.com/Yuri05/TestReport/blob/main/Report_12_MeanModel_Raltegravir/Report.md to the lower case: it works

![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/8dc7a541-d055-42a2-87da-57db9208f3c8)
