### ISSUE TITLE
Qualification report: duplicated anchors for the "static" figures

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1154]
compare the report https://github.com/Yuri05/Qualification-CKD/blob/review/Qualification/report/report.md
Input static content:

```
|![test image](images/fig1_paper.png)|
|:-:|
|       *Figure 2-1: Simulated kidney volumes (left) and simulated renal cortex perfusion rates (right) in a population of adults aged 30-70 years with varying degrees of renal impairment compared with observed data from the literature.<sup>3-8</sup> Diamonds represent individual data, whereas error bars represent the range in a study. In order to assign realistic physiological parameters to virtual individuals, quadratic equations for kidney volume and renal cortex perfusion rates were optimized to log-transformed data.*         |

|![test image](images/fig2_paper.png)|
|:-:|
|       *Figure 2-2: Algorithm for generation of virtual individuals with CKD while accounting for the effects of aging*         |

```

RE creates from this:
```
<a id="figure-2-1"></a>

|![test image](images/fig1_paper.png)|
|:-:|
|       *Figure 2-1: Simulated kidney volumes (left) and simulated renal cortex perfusion rates (right) in a population of adults aged 30-70 years with varying degrees of renal impairment compared with observed data from the literature.<sup>3-8</sup> Diamonds represent individual data, whereas error bars represent the range in a study. In order to assign realistic physiological parameters to virtual individuals, quadratic equations for kidney volume and renal cortex perfusion rates were optimized to log-transformed data.*         |

<a id="figure-2-1"></a>

|![test image](images/fig2_paper.png)|
|:-:|
|       *Figure 2-2: Algorithm for generation of virtual individuals with CKD while accounting for the effects of aging*         |

```

Both figures got the same anchor `<a id="figure-2-1"></a>`

**Comment by pchelle** [comment]
This bug is due to a mismatch between dynamic and user-defined the nomenclatures.

The current algorithm does
1. Check for a reference to an image as first element of the line 
* [x] If found, provides an anchor for the link with current figure numbering
> (Here, `![` pattern found for both figures because there is no space with the table in `![`)

2. Check for the pattern `Figure:` in a caption
* [x] If found, 
   - Add the same number as the anchor
   - __Update the figure numbering__
> (Here, the pattern does not follow the nomenclature, should be `|*Figure: ...` to leverage the dynamic naming)

Since the figure caption is not found, the algorithm did not update the dynamic figure count.
Besides, since the figure caption was user-defined, there is currently no guaranty to map the figure caption to the dynamic anchor.

**Comment by pchelle** [comment]
@Yuri05 
Thoughts ?
Should we try to update the anchoring/numerbering system or maybe provide warnings stating that we did not find a caption matching the anchor ?

The documentation site already defines the rules for the leveraging static and dynamic [references](https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/qualification-workflow.html#dynamic-references)

**Comment by Yuri05** [comment]
I don't get this.
RE has obviously recognized both static figures and inserted the anchor `<a id="figure-2-1"></a>` 2 times.
So in my understanding, "anchor inserted" should automatically lead to "figure number increased".

**Comment by pchelle** [comment]
My bad, 
I meant that the captions "Figure 2-1" and "Figure 2-2" are user-defined and not from the dynamic naming

**Comment by Yuri05** [comment]
> My bad, I meant that the captions ["Figure 2-1"](https://github.com/Yuri05/Qualification-CKD/blob/f899a1cc16c741a26283fea2abb5932039c4c399/Qualification/Input/Content/Section2_Model.md?plain=1#L5) and ["Figure 2-2"](https://github.com/Yuri05/Qualification-CKD/blob/f899a1cc16c741a26283fea2abb5932039c4c399/Qualification/Input/Content/Section2_Model.md?plain=1#L9) are user-defined and not from the dynamic naming

OK, but RE recognized both static figures and added figure anchors, both times `<a id="figure-2-1"></a>`.
Instead, figure anchors should be automatically **incremented** each time when a figure was recognized.

Here, user-defined figure captions were correct (`Figure 2-1:...` and `Figure 2-1:...`) and so automatically incremented figure anchors would match the static figures.
If the user defined static figure captions were incorrect (e.g. just `Figure 1` and `Figure 2`) - the anchors would not match the figures (which is a user error in this case and must be fixed by the user manually) - but at least they would be **unique**.

**Comment by pchelle** [comment]
Got it, the algorithm needs to increment the anchor regardless when it finds a new figure.
