### ISSUE TITLE
Meanmodel-Workflow: Residuals vs. Simulated plots: Plot caption not properly formatted

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1199]
e.g. https://github.com/Yuri05/TestReport/blob/main/Report_17_MeanModel_Raltegravir/Report.md#figure-5-5
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/12d9b6e4-d27e-4edf-b61f-b5469b38cdb3)

**Comment by pchelle** [comment]
Because of the space between the end of the text and the `**` the formatting is not taken into account

**Comment by Yuri05** [comment]
> Because of the space between the end of the text and the `**` the formatting is not taken into account

Meaning that the caption should be always trimmed 😉
