### ISSUE TITLE
Crash of DDIRatio calculation

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1208]
getPKRatioSummaryStatistics <- function(pkData, referencePKData)   
expects that pkData and referencePKData have the same dimension.
If some of the simulations failed the pkParameter for the individuals which failed are missing.
A merge with individual ID must be implemented

(It was tested with Version 2.2.311)

**Comment by Yuri05** [comment]
@KatrinCoboeken Do you mean, that if an individual is missing in either `pkData `or in `referencePKData` then `getPKRatioSummaryStatistics ` crashes? And you would expect, that missing individuals are filtered out and ratios are then built by matching of individual ids?

**Comment by KatrinCoboeken** [comment]
In my example I had a  population of 1000 individuals. In the controll all went well, so referencePKdata had the dimension 1000 x nPar. In the DDI simulation for some individuals the simulation failed. So PKdata had the dimension 997 x nPar. 
Within the function the matrices referencePKdata and PKdata are divided, which does not work, as they do not have the same dimension.  The function has to make sure, that the 997 succeses individuals  of PKdata are divided by the corresponding 997 reference individuals

**Comment by Yuri05** [comment]
ok, so we should build an intersection of individual ids in both results and keep only the individuals which are present in both.
would you expect a warning that some individuals are missing?

**Comment by KatrinCoboeken** [comment]
A warning would be good.
