### ISSUE TITLE
Crash of PlotPKParameter because of different outputs in simulations

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1209]
In my example I have a workflow with simulations with one out put and simulations with two outputs.
That crashes in the function validateSameOutputsBetweenSets in the line 
"if (all(pkParametersTable$path == pkParametersTableRef$path)) "  as the data.frames have a different size, "==" does not work. The error message is "longer object length is not a multiple of shorter object length"

But why do we have this condition on same outputs between sets.
We produce one plot per simualtion and output.  I do not see a reason why we can not mix simulations with different output numbers.
Also the number of PK Parameter per output shoudn't be an issue. Why can we not have some plots with e.g. 6 simulations on the x-axis, and some with e.g. 4?

**Comment by Yuri05** [comment]
@KatrinCoboeken Questions: 
* should we produce warnings for outputs available not in all sets?
* what should happen if 2 sets have no common outputs at all?

**Comment by KatrinCoboeken** [comment]
I would not produce warnings. 
I think it is a common case. Eg if we have  for some studies mesaurements of parent and metabolites and for some only of parent.

If 2 sets have no common output at all, then we get the plots for set 1 with the outputs of set 1 and the plots for set 2 with the outputs of set 2

**Comment by Yuri05** [comment]
* different outputs possible with warnings
* if the same output is available but with different pk parameters - continue with warning
