### ISSUE TITLE
Documentation of the release refers a template from the `develop` branch

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1212]
Here: https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/qualification-workflow.html#template

It says 

> A template R script for qualification workflows is available below. You can also download it from [GitHub](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/inst/extdata/qualification-workflow-template.R).

The linke leads to the develop branch.

**Comment by Yuri05** [comment]
You are right, release version should point to the **main** branch instead.
(And dev version to the develop branch)
