### ISSUE TITLE
Report generation fails for GOF plots

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1213]
When I try to execute a qualification plan with GOF plots defined like this:

```
"Plots": {
"AxesSettings": {"GOFMergedPlotsPredictedVsObserved": [                 {
    "Type": "X",
    "Dimension": "Concentration (mass)",
    "Unit": "µg/l",
    "GridLines": false,
    "Scaling": "Log"
},
{
    "Type": "Y",
    "Dimension": "Concentration (mass)",
    "Unit": "µg/l",
    "GridLines": false,
    "Scaling": "Log"
}]},

"PlotSettings": {
"ChartWidth": 500,
"ChartHeight": 400,
"Fonts": {
"AxisSize": 11,
"LegendSize": 9,
"OriginSize": 9,
"FontFamilyName": "Arial",
"WatermarkSize": 40
}
},
"AllPlots": [{
"Project":  "Fluvoxamine",
"Simulation":  "Spigset 1997, 50 mg SD PM",
"SectionReference":  "fluvoxamine-ct-profiles"
}],
"GOFMergedPlots": [{
"Title":  "Goodness of fit plot for concentration in plasma",
"SectionReference":  "gof-plots",
"Artifacts": ["GMFE", "Measure", "Plot"],
"PlotTypes":  ["predictedVsObserved", "residualsOverTime"],
"Groups":  [{
"Caption":  "training dataset",
"Symbol":  "Circle",
"OutputMappings":  [{
    "Project": "Fluvoxamine",
    "Simulation": "Japanese Society of Hospital Pharmacists 2015, 30 mg iv",
    "Output": "Organism|PeripheralVenousBlood|Fluvoxamine|Plasma (Peripheral Venous Blood)",
    "ObservedData": "Japanese Society 2015.30 mg iv",
    "Color": "#0000FF"
}]
}]
}],
"ComparisonTimeProfilePlots": [],
"DDIRatioPlots": [],
"PKRatioPlots": []
},
```

I get an error

<html>
<body>
<pre tabindex="0" aria-label="Console Output" role="document" class="GNVWDDMDN3B" id="rstudio_console_output" style="font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; line-height: 1.2; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span tabindex="-1" class="GNVWDDMDO3B" role="document" style="outline: none;"><span class="GNVWDDMDN3B xtermColor2 xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; color: rgb(78, 154, 6) !important;">i Info	</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">Starting run of </span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Plot Merged Goodness of Fit task</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">
04/04/2024 - 18:30:55
</span><span class="GNVWDDMDN3B xtermColor3 xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; color: rgb(196, 160, 0) !important;">! Warning	</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">argument is not a character vector
</span><span class="GNVWDDMDN3B xtermColor3 xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; color: rgb(196, 160, 0) !important;">Configuration Plan Information:</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">
</span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Title</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">: Goodness of fit plot for concentration in plasma
</span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">SectionReference</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">: gof-plots
</span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Artifacts</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">: GMFE, Measure, Plot
</span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">PlotTypes</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">: predictedVsObserved, residualsOverTime
</span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Groups</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">: list(...)
</span><span class="GNVWDDMDN3B xtermColor6 xtermBold xtermItalic" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">PlotNumber</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">: 0 (json numbering starting at 0);  1 (actual plot index)

	
</span><span class="GNVWDDMDN3B xtermColor3 xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold; color: rgb(196, 160, 0) !important;">&gt; Error Trace</span><span class="GNVWDDMDN3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">
	 ↪ createQualificationReport(qualificationRunnerFolder = "c:\\Program Files\\Open Systems Pharmacology\\QualificationRunner 11.1.130\\")
	  ↪ workflow$runWorkflow()
	   ↪ self[[plotTask]]$runTask(self$configurationPlan)
	    ↪ self$getTaskResults(configurationPlan, self$settings)
	     ↪ getQualificationGOFData(gofPlan, configurationPlan, gofAxesUnits)
	      ↪ getGOFDataForMapping(outputMapping, configurationPlan, axesUnits)
	       ↪ ospsuite::toUnit("Time", simulationPathResults$data[, "Time"], 
	        ↪ .encodeUnit(targetUnit)
</span><div class="GNVWDDMDJID ace_console_error" style="position: relative; overflow: hidden; margin: 5px 5px 5px 0px; padding: 5px 0px 5px 10px; white-space: pre-line; background-color: rgb(230, 230, 230);"><div class="GNVWDDMDKID" style="top: 5px; float: right; margin-right: 10px; margin-left: 5px; margin-bottom: 15px; line-height: 10.6667px; position: relative; user-select: none;"><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAaElEQVR42mNgwAXWv8sEY4rA2vd+DOve/wFjEJsssOGjOdCA/ygYJEYS2PhRBcMQGAbJEQVWfRbFaQgMg9TgBZufcRE0BIZBarG75D8z0YbAXQbUgwFINQSGCQKyNY4aRLoFw9iggQYAE6xnKErSS9EAAAAASUVORK5CYII=" width="18" height="18" class="GNVWDDMDLID show_traceback_image" alt="" aria-hidden="true" style="cursor: pointer; width: 9px !important; height: 9px !important;"> <a class="GNVWDDMDMID show_traceback_text" style="font-family: &quot;Segoe UI&quot;, serif; font-size: 10.6667px; opacity: 0.5; cursor: pointer;">Show Traceback</a></div><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABU0lEQVR42pWUP0vEMBjGo4uz2rQO4iS66KCC4OSoi99C/ATu9zn8AKII16QOgoLgoCD+WR28tUnuThQUp0OvPm+8P9ZrSxJ4hjZ9fn2TPG8YKxlT9XQ2FPqAC6O40B3oKojNJvMZ08Ksw/gGZf/0FUi16wSZPFVzMLQLIH11wjjdGDEGdbXKatn44FloUQHp634AgNcy8PKCS30dyeYyT9SKA8SKlh/FzSXyEoOxLBtDFXu95dy5ggKhbslD3r8rYmHSijDx7gqyPz5pz4zuMqh0Kh6gl5zfw1ipXAA9zd+F+Zk/a0xgsusKQupfS8OIdmh4VPRYCPk9NS/QM3mGhGGOWij30B1kjsljcwQGndo5dEPJtpUJdekAeqK42G6A1yYbxLVcr8XpAiY+KyDdUOqtXK8Ro3DTY71dAgPE7HvdSUGiFrk0RzB/9BL/gLtop+z7HzowRJ/sYbqcAAAAAElFTkSuQmCC" width="18" height="18" class="GNVWDDMDLID rerun_image" alt="" style="cursor: pointer; width: 9px !important; height: 9px !important;"> <a class="GNVWDDMDMID rerun_text" style="font-family: &quot;Segoe UI&quot;, serif; font-size: 10.6667px; opacity: 0.5; cursor: pointer;">Rerun with Debug</a></div></div><div class="GNVWDDMDNID GNVWDDMDH3B  ace_constant" style="white-space: pre; display: inline; overflow-wrap: break-word; word-break: break-word; color: rgb(197, 6, 11);"><span>Error: argument is not a character vector
</span><span class="xtermColor3 xtermBold" style="font-weight: bold; color: rgb(196, 160, 0) !important;">Configuration Plan Information:</span><span>
</span><span class="xtermColor6 xtermBold xtermItalic" style="font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Title</span><span>: Goodness of fit plot for concentration in plasma
</span><span class="xtermColor6 xtermBold xtermItalic" style="font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">SectionReference</span><span>: gof-plots
</span><span class="xtermColor6 xtermBold xtermItalic" style="font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Artifacts</span><span>: GMFE, Measure, Plot
</span><span class="xtermColor6 xtermBold xtermItalic" style="font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">PlotTypes</span><span>: predictedVsObserved, residualsOverTime
</span><span class="xtermColor6 xtermBold xtermItalic" style="font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">Groups</span><span>: list(...)
</span><span class="xtermColor6 xtermBold xtermItalic" style="font-weight: bold; font-style: italic; color: rgb(6, 152, 154) !important;">PlotNumber</span><span>: 0 (json numbering starting at 0);  1 (actual plot index)</span></div><div class="GNVWDDMDOID stack_trace" aria-hidden="true" style="margin-top: 0.5em; margin-left: 0.3em; display: block;">
8. | stop(errorCondition$message, call. = FALSE)
-- | --

</div></div></span></pre>
</body>
</html>

The time unit is `NULL` because it is not defined anywhere.

**Comment by pchelle** [comment]
It seems that the exported plot types also include residuals vs time plots:

> `"PlotTypes":  ["predictedVsObserved", "residualsOverTime"]`

**Comment by PavelBal** [comment]
> It seems that the exported plot types also include residuals vs time plots:

Is this an issue?

**Comment by pchelle** [comment]
> > It seems that the exported plot types also include residuals vs time plots:
> 
> Is this an issue?

I need to check the configuration plan created by the qualification runner to check what happened in more details (usually named `report-configuration-plan.json` in the `re_input` folder).

The code crashed because it was not able to convert the time unit. This plot should be the place where such unit conversion would happen.

**Comment by PavelBal** [comment]
Here is the report configuration plan:

[report-configuration-plan.json](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/14918687/report-configuration-plan.json)
