### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1218]
due to 1 failing test
```
== Failed tests ================================================================
  -- Failure ('test-absorption.R:21:3'): Workflow generates appropriate number of files --
  list.files(workflowAbs$workflowFolder, pattern = ".txt") has length 3, not length 2.
  
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 656 ]
```

**Comment by pchelle** [comment]
@Yuri05 
Could you let me know the session info ? I am not able to reproduce.

The test was assessing which log files were created, thus it means a new warning is created and caught by the reporting engine.
I am suspecting the warning comes from an update in a package such as `ggplot2` or `dplyr` package, likely stating a function was deprecated.

If this is the case, we may want to generalize the silent log of such warnings about deprecate functions (currently, only account for ggplot2)

**Comment by Yuri05** [comment]
It's from the AppVeyor build

**Comment by pchelle** [comment]
As suspected a warning from a deprecated function.
However, I was not expected that the deprecated function was from ospsuite ! :)

```
! Warning	`runSimulation()` was deprecated in ospsuite 12.0.0.
	Please use `runSimulations()` instead
```
