### ISSUE TITLE
TimeOffset of a simulation is applied twice

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1230]
Within a poulation workflow the timeoffset is used in the function getSimulationTimeRanges to shift the timeranges.
Later it is used in the function  getTimeProfilePlotResults to shift the data for the shifted timeranges. 
That are two shifts  and leads to an error with missing data. 

I commented the second shift as shown below, and got good results:

getTimeProfilePlotResults <- function(workflowType, timeRange, simulatedData, observedData = NULL, metaDataFrame, timeProfileMapping, structureSet, settings = NULL) {
  goodnessOfFitPlots <- list()
  goodnessOfFitCaptions <- list()

  -# Add reference simulated data, if any, to the existing data
  -# rbind.data.frame enforces data.frame type and nrow can be used as is
  -# Reset time based on timeOffset or application range
  simulatedData <- rbind.data.frame(
    asTimeAfterDose(
      settings$referenceData$simulatedData,
      min(timeRange),# + settings$referenceData$timeOffset,
      max(timeRange) #+ settings$referenceData$timeOffset
    ),
    asTimeAfterDose(
      simulatedData,
      min(timeRange),# + structureSet$simulationSet$timeOffset,
      max(timeRange) #+ structureSet$simulationSet$timeOffset
    )
  )
  if (nrow(simulatedData) == 0) {
    stop(messages$dataIncludedInTimeRange(
      nrow(simulatedData),
      timeRange + structureSet$simulationSet$timeOffset,
      structureSet$simulationSet$timeUnit, "simulated"
    ))
  }
  observedData <- asTimeAfterDose(
    observedData,
    min(timeRange),# + structureSet$simulationSet$timeOffset,
    max(timeRange) #+ structureSet$simulationSet$timeOffset
  )

**Comment by pchelle** [comment]
@KatrinCoboeken 
The function `getSimulationTimeRanges()` calculates the time ranges for total, first and last application.

- For total (all applications), time range corresponds to time of first application until end of simulation irrespective of `timeOffset`. The time offset is applied only in `asTimeAfterDose()`.
- For first application, the time range corresponds to time of first application __after time offset__ to time of second application __after time offset__. The time offset is applied only in `asTimeAfterDose()`, __but the time range may start later than actual first application__
- For last application, time range corresponds to time of last application until end of simulation irrespective of `timeOffset` (which may lead to issues ?). The time offset is applied only in `asTimeAfterDose()`

### For total time range

In case an application is out of the total time range + offset, a warning is thrown but the time is not shift
-

**Comment by pchelle** [comment]
I have started adding tests in `testthat`, this way we'll get reproducible cases of what we want in case of offsets and multiple time ranges

**Comment by KatrinCoboeken** [comment]
If we have a simulations with:

- applications at 0,24,48,72,96 h
- simulation time 120 h
- timeoffset = 48h

Then the time ranges of interest would be:
first 48 - 72
last 96 - 120
total 24 - 120

That means asTimeAfterDose() should look for values within these ranges.
In the current version it looks in the ranges + timeoffset

asTimeAfterDose(
   simulatedData,
   min(timeRange) + structureSet$simulationSet$timeOffset,
   max(timeRange)+ structureSet$simulationSet$timeOffset
)

for last that would be c(96 + 48, 120 + 48) = c(144, 168) 
That leads to an error, as there is no data available

It should be :

asTimeAfterDose(
   simulatedData,
   min(timeRange),
   max(timeRange)
)

**Comment by pchelle** [comment]
Okay, then the offset is relevant only for first and total.

In the case where the offset does not correspond to an application.
For instance, the user had defined `timeOffset=40` instead of 48.
Should the time ranges be `c(40, 72)` for first application or `c(48, 72)` ? Likewise with total ?

**Comment by KatrinCoboeken** [comment]
@pchelle 
The offset is relevant for ALL ranges.   The offset shift the ranges, and then you select the data of the shifted ranges WITHOUT another shift.  


If the offset does not correspond to an application I would say first application range still starts at an application. 
(@AnnikaRPS your thoughts ?)
In the example the ranges would be:
first 48-72
last 96-120
total 40- 120
