### ISSUE TITLE
Check if the time point of the offset should be included in the list of the output time points

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1237]
Another question: is it guaranteed that the time point of the offset is included in the list of the output time points?
E.g. if my initial output raster is 0h, 1h, 2h, ... and my time offset is 30 min: will 30min be included in the output time points?

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/1232#discussion_r1648967062_

**Comment by pchelle** [comment]
> @pchelle Btw, it is indeed possible to add single time points to the simulation output schema via https://www.open-systems-pharmacology.org/OSPSuite-R/dev/reference/OutputSchema.html#method-addtimepoints- However it's not quite clear for me, if the added values are automatically assumed as the internal time unit ([min]) or units can be passed additionally (just created issues for this in ospsuite-r)

Tried it on a simulation, timePoints are using base unit
