### ISSUE TITLE
Pred. vs. obs. figures in qualification report not quadratic

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1248]
In the test qualification report run with the Reporting Engine Version 2.2, predicted vs. observed plots e.g. Figure 2-1 and Figure 2-3 are not quadratic although they should be. 

https://github.com/Yuri05/TestReport/blob/main/Report_19_DDI_CYP3A4/report.md

**Comment by Yuri05** [comment]
https://github.com/Yuri05/TestReport/blob/main/Report_19_DDI_CYP3A4/report.md#figure-2-1
https://github.com/Yuri05/TestReport/blob/main/Report_19_DDI_CYP3A4/report.md#figure-2-3
