### ISSUE TITLE
"Residuals across all simulations in reporting engine report

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1249]
When looking at the section "Residuals across all simulations" generated with the Reporting engine version 2.2, I have the following remarks:

- The use of capital letters in axis labels is not standardized, e.g. it is "Quantities of residuals" or "Relative frequency" but "Standard Normal Quantiles" and "Residuals Observed-Simulated". (not only in this report section)
-The pred-vs-obs plots are not quadratic although they should be. (not only in this report section)
- According to the axis lables, for single simulation sets, the residulas are calculated as "log(observed)-log(simulated)" whereas for the overall residuals it is "observed-simulated". Is there a reason for that or is this a bug? ==> Issue https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/1251

**Comment by AnnikaRPS** [comment]
I would tend towards the "Quantities of residuals" version.

**Comment by Yuri05** [comment]
> * According to the axis lables, for single simulation sets, the residulas are calculated as "log(observed)-log(simulated)" whereas for the overall residuals it is "observed-simulated". Is there a reason for that or is this a bug?

create N plots, separated by groupID.
linlog depending on the dimension of the output: Fraction: lin, conc / amount: log, others - log (for now: later: user option)
