### ISSUE TITLE
Line break in residual plots

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1252]
In the resulting reports of the reporting engine, the residuals plots for single simulation sets have a line break in the ylabel, the plots in the residuals acrross all simulatios don't. I would consistently add a linebreak between "Residuals" and "log(simulated)-log(observed)" or "simulated-observed"

e.g. in this test repost:
https://github.com/Yuri05/TestReport/blob/main/Report_20_MeanModel_Raltegravir/Report.md#time-profiles-raltegravir_10_mg__lactose_formulation_
 Figure 5-5 vs. Figure 5-97
 
For the x-axis there is no line break at all: Figure 5-7 and  Figure 5-99 - I would also use the same line break here

**Comment by pchelle** [comment]
Actually the issue is a side effect of a function called by `tlf`: `stringr::str_wrap()` originally adopted to better handle long captions: [#474](https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/474).
> [!CAUTION]
> The function actually removes the previous line breaks and place its own instead !
