### ISSUE TITLE
Sensitivity plots destroyed by `<br>` 

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1260]
Sensitivity plots are now totally corrupted, because for whatever reason `<br>`  is **not** translated to new line in the captions.
Residual plots seem to be OK though

![Raltegravir_10_mg__lactose_formulation_-4_sensitivity_AUC_tEnd](https://github.com/user-attachments/assets/a5304183-61e3-45c4-813e-dcd6416275cc)

**Comment by pchelle** [comment]
`{tlf}` does not use the same functions for both [#518](https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/518). 
If there is no reason for that I'll provide consistent methods otherwise, ticklabels will have to go back and use the `\n` line breaks.
