### ISSUE TITLE
Input string 'Âµ|Î¼|µ' cannot be translated to UTF-8

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1261]
While executing the attached workflow, I got the warnings below.
[MeanModel_Raltegravir_inclSens.zip](https://github.com/user-attachments/files/16416718/MeanModel_Raltegravir_inclSens.zip)
Did not these warnings in the past, particularly not with the attached workflow.

```
3: In ospsuite::getDimensionForUnit(unit) :
  strings not representable in native encoding will be translated to UTF-8
4: In ospsuite::getDimensionForUnit(unit) :
  input string 'Âµ|Î¼|µ' cannot be translated to UTF-8, is it valid in 'UTF-8' ?
5: In ospsuite::getDimensionForUnit(unit) :
  input string 'Âµ|Î¼|µ' cannot be translated to UTF-8, is it valid in 'UTF-8' ?
```

**Comment by pchelle** [comment]
Was the file `Raltegravir_PK.txt` modified at some point ?
The __Unit__ column includes `�g/L`

When trying to read it I actually directly get an error :

``` r
obsFile <- "MeanModel_Raltegravir_inclSens/Data/Raltegravir_PK.txt"
ospsuite.reportingengine::readObservedDataFile(obsFile)
#> Error in type.convert.default(data[[i]], as.is = as.is[i], dec = dec, : invalid multibyte string at '<b5>g/L'
```

**Comment by Yuri05** [comment]
The file did not change since 2020.
I also can read it via `ospsuite.reportingengine::readObservedDataFile()`

However, when checking the file: it was not UTF-8 encoded. When saving it as UTF-8 - the workflow runs through without warnings.

While wrong encoding of the data file can be considered as a bug/user error, quite a few questions come up:
1) Why does `ospsuite.reportingengine::readObservedDataFile()` behaves differently on our systems?
2) Why did RE become less robust?
3) Those warnings reported in the issue look for me more as errors than warnings. I would expect that the unit conversion failed and the workflow stops with an error.
4) Can we check programmatically, if the (data) files are UTF-8 encoded?

**Comment by pchelle** [comment]
> 4. Can we check programmatically, if the (data) files are UTF-8 encoded?

R has the `iconv` function that returns `NA` when non unicode characters are encountered.
I can include a validate function in reporting engine unless it may be more appropriate to migrate the validate function to `{ospsuite.utils}`

``` r
obsDataFile <- "MeanModel_Raltegravir_inclSens/Data/Raltegravir_PK.txt"
any(is.na(iconv(readLines(obsDataFile), from = "UTF-8")))
#> [1] TRUE
```

<sup>Created on 2024-08-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Yuri05** [comment]
> > 4. Can we check programmatically, if the (data) files are UTF-8 encoded?
> 
> R has the `iconv` function that returns `NA` when non unicode characters are encountered. I can include a validate function in reporting engine unless it may be more appropriate to migrate the validate function to `{ospsuite.utils}`
> 
> ```r
> obsDataFile <- "MeanModel_Raltegravir_inclSens/Data/Raltegravir_PK.txt"
> any(is.na(iconv(readLines(obsDataFile), from = "UTF-8")))
> #> [1] TRUE
> ```
> 
> Created on 2024-08-01 with [reprex v2.0.2](https://reprex.tidyverse.org)

looks good. let's add the function to the **ospsuite.utils**.

**Comment by Yuri05** [comment]
@pchelle 
With the current RE and after I converted the data file to UTF-8 - I still get the warnings regarding the wrong encoding in the units!!!  [4mail.zip](https://github.com/user-attachments/files/16612914/4mail.zip)
```
OSP Suite Package version: 12.1.0
OSP Reporting Engine version: 2.2.360
tlf version: 1.5.170
```

**Comment by Yuri05** [comment]
The warnings come from the function `.encodeUnit` in the ospsuite package.
```
> ospsuite:::.encodeUnit("year(s)")
[1] "year(s)"
Warning messages:
1: strings not representable in native encoding will be translated to UTF-8 
2: input string 'Âµ|Î¼|µ' cannot be translated to UTF-8, is it valid in 'UTF-8' ? 
3: input string 'Âµ|Î¼|µ' cannot be translated to UTF-8, is it valid in 'UTF-8' ? 
```
Also for me, reproducible only on some systems, not on all. 
And the warnings come only the very first time when the function is called. After that you need to restart R to get them again.
Have created an issue for this in ospsuite-R: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1480

**Comment by Yuri05** [comment]
should be fixed now via workaround (s. the discussion in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1480)
