### ISSUE TITLE
MeanModelWF: PlotPKParameters Crashes

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#131]
Error in self$getTaskResults(set, self$workflowFolder, self$settings) : 
  unused argument (self$settings)

meanModelWF <- MeanModelWorkflow$new(simulationSets = meanModelSet,workflowFolder = outputDir)

meanModelWF$inactivateTasks()
meanModelWF$activateTasks(c("simulate","plotGoF","meanModelPKParameters","plotPKParameters"))
meanModelWF$runWorkflow()

**Comment by Yuri05** [comment]
@ThomasGaub Please attach used inputs

**Comment by ThomasGaub** [comment]
[
[test_no7.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4486747/test_no7.zip)
](url)
done
