### ISSUE TITLE
Coding Standard in Reporting Engine

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#138]
I have added a task in the Suite repo (https://github.com/Open-Systems-Pharmacology/developer-docs/issues/30)  to clarify the indentation of the code. 
At the moment, there is no consistency in the reporting engine code.  A styler should take care of this for us. But clearly this does not exist or work as expected so we need to be mindful of this

**Comment by pchelle** [comment]
This is now detailed in its [CODING_STANDARDS_R](https://github.com/Open-Systems-Pharmacology/developer-docs/blob/main/ospsuite-r-specifics/CODING_STANDARDS_R.md) document.
