### ISSUE TITLE
Error when running sensitivity analysis using 4 cores (population parallelcomparison workflow)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#140]
Error when running sensitivity analysis using 4 cores (population parallelcomparison workflow)

Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In dir.create(file.path(self$workflowFolder, self$outputFolder)) :
  'C:\temp\Iba\Workflow_population_parallelcomparison\..\Output\SimulationResults' already exists
2: In file(con, "r") :
  cannot open file 'C:/Users/GEMUH/Documents/logDebug-core-sensitivity-analysis1': No such file or directory

[Workflow_population_parallelcomparison_sensitivity.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4508798/Workflow_population_parallelcomparison_sensitivity.zip)

**Comment by abdullahhamadeh** [comment]
This has been resolved.  

With the latest update, the example in the zip file now needs a mandatory `simulationSetName` to initialize the simulation sets.  The simulation set constructor no longer has a `pathID` argument; instead it has an `output` argument, which takes an `Output` object.  
For example:
`popSimSet1 <- PopulationSimulationSet$new(simulationSetName = "ss1", simulationFile = simFilePath1, populationFile = popFilePath1 , output = Output$new(path = "Organism|Heart|Plasma|Raltegravir|Concentration"))`
