### ISSUE TITLE
Error sensitivity analysis switching to 1 core (population parallelcomparison workflow)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#141]
Sensitivity number of cores set from 4 to 1. Without restarting Rstudio, I get an error:

Error in Rmpi::mpi.spawn.Rslaves(nslaves = numberOfCores) : 
  It seems there are some slaves running on comm  1

[Workflow_population_parallelcomparison.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4508831/Workflow_population_parallelcomparison.zip)

**Comment by msevestre** [comment]
@abdullahhamadeh numberOfCoresToUse was renamed to numberOfCores a while back.

**Comment by abdullahhamadeh** [comment]
As with #140 :

This has been resolved.

With the latest update, the example in the zip file now needs a mandatory simulationSetName to initialize the simulation sets. The simulation set constructor no longer has a pathID argument; instead it has an output argument, which takes an Output object.
For example:
popSimSet1 <- PopulationSimulationSet$new(simulationSetName = "ss1", simulationFile = simFilePath1, populationFile = popFilePath1 , output = Output$new(path = "Organism|Heart|Plasma|Raltegravir|Concentration"))
