### ISSUE TITLE
Sensitivty analysis will not start using 1 core (population parallelcomparison workflow)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#142]
Sensitivty analysis will not start using 1 core (population parallelcomparison workflow):

Error in .subset2(public_bind_env, "initialize")(...) : 
  unused argument (numberOfCoresToUse = numberOfCoresToUse)

[Workflow_population_parallelcomparison.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4508850/Workflow_population_parallelcomparison.zip)

**Comment by Yuri05** [comment]
Fixed in the meanwhile
