### ISSUE TITLE
PKParameter options Ignored

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#144]
In my Mean Model WF I defined pk-parameters to compute like here:
   pkParameters =c('C_max','t_max','C_tEnd','AUC'),
   pkParametersUnits = c('mg/l','h','mg/l','mg*h/l'),
in results I have all PK Parameters with other Units as given in my options.
Used same Workflow as in #131

**Comment by msevestre** [comment]
This is obsolete
Are you using the latest version?
@abdullahhamadeh @pchelle can you confirm that this was removed?

**Comment by pchelle** [comment]
I haven't removed it yet from the SimulationSet class,
I wanted to provide a script example first to show how to do it based on the one in ospsuite.

**Comment by ThomasGaub** [comment]
Always testing on latest version.

**Comment by ThomasGaub** [comment]
What is then the new way to define PK-Parameters and Units?

**Comment by msevestre** [comment]
something like this
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/dev/script-pk-analyses.R#L6

You define your PK Parameter (display unit, display name) BEFORE starting the workflow. This is more or less updating the definition of PK Parameters globally

This is also how you can define user define pk parameters
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/dev/script-pk-analyses.R#L12

**Comment by ThomasGaub** [comment]
Thank You. Was very helpfull, worked fine.

One additional question, how to restrict the list of computed PKValues.

**Comment by msevestre** [comment]
Everything is computed at the moment. Is this an issue?

**Comment by ThomasGaub** [comment]
Was specified so in #32 (PK Parameter of intrest). I will double check with power users if this really needed.
Matlab Version has this feature.

**Comment by ThomasGaub** [comment]
Update, after discussion with @sfrechen . 
Restriction makes sense as some "Standard PK parameters" will not make sense in every szenario or may be missleading

**Comment by sfrechen** [comment]
I would eben say, the user should provide a white list (instead of a black list [restrictions]).

**Comment by msevestre** [comment]
Parameter that do not make sense are not calculated. We are talking about the dump of PKparameter to a csv file correct?
Then in the plot, you will be able to select what you want to see obviously. But for the calculation, it's much easier at the moment to dump everything.

@Yuri05 If not, we need to update ospsuite.core

**Comment by ThomasGaub** [comment]
Yes, I want to just list some in the "plot" but this is not possible at the moment

**Comment by msevestre** [comment]
Ok selection of PKparameter of interest should be possible for the plots 

Which plots are we talking about?
@abdullahhamadeh isn't it supported ?


@sfrechen I like the idea or a white list. What if the parameter is left empty or ignored? Export all or error?

**Comment by ThomasGaub** [comment]
May be it is supported, but I have no information how.
