### ISSUE TITLE
Relative Path names in definition of Working Folder

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#145]
Relative Path names may lead to corrupted outputs, e.g. empty report files.

Example: 
testFolder <- "../tests/dev/01_MeanModel_Raltegravir"
workflowFolder = file.path(testFolder, "WorkflowTest01"))

**Comment by msevestre** [comment]
Looks like R code so I am assuming this is for the new repository. Transferring

**Comment by Yuri05** [comment]
Fixed in the meanwhile
