### ISSUE TITLE
Add display name for parameters used in SA

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#151]
At the moment, the full path of the parameter is used which can become very long

1. When a discrete list is used, we could also support a list of parameter display name (same length) or we create a small structure (path, display)

1. When the list is created dynamically, there has to be away to specify parameter display for a path (for example using a table etc...

Maybe first option is not needed then if we support nr 2?

**Comment by Yuri05** [comment]
> 2. When the list is created dynamically, there has to be away to specify parameter display for a path (for example using a table etc...

Not sure if it's possible to define such a table for all possible parameters here. Maybe we need just some general replacement rules which will apply to all paths, e.g.
* `Replace "Organism-" with ""` (e.g. use `"Skin-Volume"` instead of `"Organism-Skin-Volume"`) etc.

@sfrechen @twendl @incei FYI

**Comment by Yuri05** [comment]
Done in the meanwhile (using ospsuite default naming).

**Comment by Yuri05** [comment]
>When a discrete list is used, we could also support a list of parameter display name (same length) or we create a small structure (path, display)

This one is not done yet...

**Comment by Yuri05** [comment]
duplicates #399
