### ISSUE TITLE
Pop sensitivity plots with several populations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#164]
[Sensi.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4550934/Sensi.zip)
2 populations are used, however sensitivity plots show only 1 value for each percentile
![Raltegravir 10 mg   (lactose formulation)-Raltegravir Adult Population-C_max-Organism-Heart-Plasma-Raltegravir-Concentration](https://user-images.githubusercontent.com/25061876/80582831-b0963d00-8a0f-11ea-8b6c-d9a507289117.png)

**Comment by msevestre** [comment]
How should the plot look like? Isn't it going to be impossible to read?

**Comment by Yuri05** [comment]
>Isn't it going to be impossible to read? 

For 2-3 pops should be ok, for 4 or more not really readable indeed. But: it's users problem then:)
In the current Matlab-RE it looks e.g. like this: https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/advanced_examples/07_Population_Pediatric_Raltegavir_inclSens/figures/sensitivity_Appendix.docx

**Comment by Yuri05** [comment]
Fixed with #212
