### ISSUE TITLE
Sensitivity analyses

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#167]
The layout of the output of sensitvity analyses (mean model) looks strange:

![Raltegravir 10 mg   (lactose formulation)-AUC_inf-1](https://user-images.githubusercontent.com/29250436/80648438-78731680-8a70-11ea-89a9-3864166ac9d4.png)

**Comment by msevestre** [comment]
What's wrong with this ? (just kidding)

Can you attach the workflow and folder so that we can reproduce?

**Comment by lkuepfer** [comment]
Freundliche Grüße / Best regards,

Dr. Lars Kuepfer
Scientist Systems Pharmacology

////////////////////

Bayer AG
Research & Development, Pharmaceuticals
Systems Pharmacology & Medicine II
Building B106, 106
51368 Leverkusen, Germany
Tel:       +49 214 30-22745
Mobile: +49 173 24-79088
E-mail:  lars.kuepfer@bayer.com
Web:     http://www.bayer.com
Datenschutzhinweise<https://www.bayer.de/de/datenschutzhinweise-fuer-ausgewaehlte-verarbeitungstaetigkeiten.aspx> // Data privacy information<https://www.bayer.com/en/data-privacy-information-for-specific-processing-activities.aspx>

/// Vorstand: Werner Baumann, Vorsitzender | Liam Condon, Wolfgang Nickl, Stefan Oelrich, Heiko Schipper
/// Vorsitzender des Aufsichtsrats: Werner Wenning
/// Sitz der Gesellschaft: Leverkusen | Amtsgericht Köln, HRB 48248

Von: Michael Sevestre <notifications@github.com>
Gesendet: Mittwoch, 29. April 2020 23:31
An: Open-Systems-Pharmacology/OSPSuite.ReportingEngine <OSPSuite.ReportingEngine@noreply.github.com>
Cc: Lars Kuepfer <lars.kuepfer@bayer.com>; Author <author@noreply.github.com>
Betreff: Re: [Open-Systems-Pharmacology/OSPSuite.ReportingEngine] Sensitivity analyses (#167)


What's wrong with this ? (just kidding)

Can you attach the workflow and folder so that we can reproduce?

**Comment by Yuri05** [comment]
Closing in favor of #201 and #202
