### ISSUE TITLE
totalSensitivityThreshold: Should it be used when the list of variable parameters is predefined by the user?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#171]
It might make sense to only consider the parameter when the list of variable parameters is retrieved automatically from the simulation

If the list is preset by the user, the threshold parameter would be set to 1?

FYI @Yuri05

**Comment by Yuri05** [comment]
@sfrechen @TWendl @Incei @lkuepfer @ThomasGaub please comment

**Comment by Incei** [comment]
I dont understand the question...what do you mean with theshold?

**Comment by Yuri05** [comment]
Threshold = "cut-off" used for plots of the most sensitive parameters (https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis#tab-sensitivity-analysis)

**Comment by Incei** [comment]
I don't have a strong preference. Perhaps @KatrinCoboeken ?

**Comment by KatrinCoboeken** [comment]
The threshold makes sense if the parameter list is very long. 
So my favorite option would be that user can change this manually, with default:
 use it for automatically parameter selection, 
 do not use it for user defined selection

**Comment by Yuri05** [comment]
That means, that:
* the **default** for the cut-off would be:
  * 1 in case sensitivity parameters list was provided by user
  * 0.9 otherwise
* default cut-off can be overwritten by user in both cases

**Comment by KatrinCoboeken** [comment]
yes

**Comment by TWendl** [comment]
agree with @Yuri05 on threshold default settings!

**Comment by abdullahhamadeh** [comment]
Is there a preferred default threshold for the population sensitivity plot, o

**Comment by abdullahhamadeh** [comment]
Is there a different default for the population sensitivity plot, or 1 as well?

**Comment by Yuri05** [comment]
>or 0.9/1 as well?

Yes.

**Comment by abdullahhamadeh** [comment]
In the sensitivity results CSV file, do we want all sensitivity results or just those within the threshold?

**Comment by Yuri05** [comment]
I would say: all. Plot just does not look good with too many points, but I don't see any reason why we should exclude this information from the csv.

**Comment by abdullahhamadeh** [comment]
For now I am manually selecting the top X% most sensitive parameters, where X is the threshold.  Is there a way to use ospsuite totalSensitivityThreshold feature?  I would need a way to import to/export from a CSV SA result file the SA results falling within totalSensitivityThreshold.

**Comment by msevestre** [comment]
What do you mean manually?

This is a feature backed in OSPSuite-r. Look at the sensitivity analysis
results object.

**Comment by abdullahhamadeh** [comment]
Yes, totalSensitivityThreshold  is an argument allPKParameterSensitivitiesFor, which returns a list.  Is it used elsewhere?

I was thinking more along the lines of using totalSensitivityThreshold as an input to importSensitivityAnalysisResultsFromCSV

**Comment by abdullahhamadeh** [comment]
To elaborate, the SA results are saved as CSV.  Then a plot sensitivity task is started.  The plot task reads the CSVs as a dataframe (using read.csv) from which it creates the plot.  

The other option is to use importSensitivityAnalysisResultsFromCSV into an object, then use totalSensitivityThreshold to return a list of filtered results, and loop thru that list to create the dataframe.

**Comment by abdullahhamadeh** [comment]
@msevestre is the list returned after applying totalSensitivityThreshold always sorted max sensivitity to min?

**Comment by Yuri05** [comment]
Done in the meanwhile. Closing..
