### ISSUE TITLE
simulationSetName must be mandatory and unique

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#175]
At the moment `simulationSetName` is optional when creating a _SimulationSet_ or a _PopulationSimulationSet_. 
However it must be **mandatory**, **non-empty** and (if there are >1 simulation/population sets per workflow) **unique**.

**Comment by msevestre** [comment]
In general, there is a lack of validation of input parameters (e.g type check for example).
Because our users are not used to work with object, and because of the lack of type safety and intellisence (subpart even in r studio), we need to validate inputs

See vallidateIsxxxx in ospsuite-r
