### ISSUE TITLE
Population plots and tables: Time profiles and Residuals

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#18]
# Inputs
  * Output folder of the _Simulate population_ task (with calculated simulation results)
  * Output Folder for results (all results will be generated here)
  * OPTIONAL Number of Cores
  * Type. One of:
      * **Pediatric**: one population _may be_ marked as (adult) reference
      * **Parallel comparison**: no population is marked as special.
      * **Ratio comparison**:
        * special case for analysis of one property of a population (e.g. GFR)
        * one population (e.g. "healthy") is marked as reference
        * for all other (e.g. "diseased") populations: ratios of all PK Parameters to the corresponding healthy one is calculated and plotted as Box-Whisker plot
  * 1 or more populations
  * List of datasets
  * Settings (s. also #13):
      * Reference population ( may be empty)
        * OPTIONAL Time offset
      * display Unit for time. **Default: h**
      * List of time Time ranges.  One plot per time range
         * Single dose: Default total range
         * For multiple dose additionally: first and last application 
      * scale of y axes (lin/log/both). **Default: both**
      * Aggregation type for Residuals. One of {_Mean_, _Geomean_, _Median_}. Default: Median 
      * Types of Plot. **Default: all 6 plot types**. For each plot: plot per pop or for all pops or both
        1. Simulated time profile: Mean, Median and 5th - 95th percentile range of the simulated time profiles (if available with data). If a reference population is defined, it is also plotted.
        2. Residuals (based on population mean or geomean or median (depending on the aggregation type) ) vs time
        3. Residuals (based on population mean or geomean or median (depending on the aggregation type) ) vs simulated output
        4. Predicted (population mean or geomean or median (depending on the aggregation type)) vs observed
        5. Histogram of residuals (**For all outputs together**)
        6. qq-plot of residuals (**For all outputs together**)

# Outputs
In the output folder: all plots/tables as specified in the settings
* one subsection for each population, reference population is plotted in each population as reference
* **(for all plot types except for time profiles)** if specified in the settings: one section for merged plots (= all pops in one plot)
<img height="200" src="https://user-images.githubusercontent.com/25061876/69337957-6e97ec80-0c62-11ea-9c3e-c189a75a7a47.png"><img height="200" src="https://user-images.githubusercontent.com/25061876/69338190-e6661700-0c62-11ea-9af7-fb00597a8b7a.png"><img height="200" src="https://user-images.githubusercontent.com/25061876/69338292-20371d80-0c63-11ea-86a4-a39b0a7c0463.png"><img height="200" src="https://user-images.githubusercontent.com/25061876/69338475-96d41b00-0c63-11ea-8ad7-90af4437814c.png"><img height="200" src="https://user-images.githubusercontent.com/25061876/69338623-df8bd400-0c63-11ea-8995-31acc1387a77.png"><img height="200" src="https://user-images.githubusercontent.com/25061876/69338764-25489c80-0c64-11ea-85b0-aedaedfd2600.png">
* Tables: currently NONE

**Comment by sfrechen** [comment]
Please note:

Simulated time profile: Mean, Median and 5th - 95th percentile range of the simulated time profiles (if available with data). If a reference population is defined, it is also plotted (**if available with data**).
