### ISSUE TITLE
Histo plots for categorical parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#185]
In this example population was exported from PK-Sim9; Gender is now explicitly exported as "MALE/FEMALE" and not 1/2 as before. This results in empty Gender histo plot
[newPop.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4629819/newPop.zip)
![Gender-TestPop](https://user-images.githubusercontent.com/25061876/81963143-fe689300-9614-11ea-911e-6d00bb734513.png)

**Comment by pchelle** [comment]
@Yuri05 , do the population covariates (Gender, Race and Population) are the only parameters expected to be categorical ?
If so, we will need to define a slightly different method for histogram (and range plots?) and use it if the parameter is included in one of the population covariates.

**Comment by Yuri05** [comment]
In the old population file format (<= V8) it's `"Gender","RaceIndex","Population Name"`
In the new popultion format (V9) it's `"Gender","Population","Population Name"`
I am not aware of any other categorical parameters.
[pop_example.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4651061/pop_example.zip)

**Comment by msevestre** [comment]
### IMPORTANT: This should not be static but dynamic
That's why there is the covariate method
any entry that is not a parameter will be assumed to be a covariate . So a user can typically create his or her own covariate (by adding a column)
