### ISSUE TITLE
Pop PK analysis: unnecessary unit conversion?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#189]
The example attached crashes during the unit conversion. While the unit conversion indeed would not be possible (in this artificial test case molecules do not have a molecular weight), the question is: why is this conversion required at all?
In the workflow all units are molar, e.g. CMax must be output in µmol.

[23_189.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6035175/23_189.zip)

<details><summary>Workflow</summary>

```
rootDir <- getwd()
#source("install_packages.R")

library(ospsuite.reportingengine)

cmax <- PkParameterInfo$new(pkParameter = "C_max", displayName = "CMax", displayUnit = "µmol")
tmax <- PkParameterInfo$new(pkParameter = "t_max", displayName = "TMax", displayUnit = "h")

myOutput <- Output$new(path = "Organism|A", displayName = "A", displayUnit = "µmol", pkParameters = c(cmax, tmax))

# Setup workflow using two simulation sets
popSimSet1 <- PopulationSimulationSet$new(
	simulationFile = file.path(rootDir, "MiniModel.pkml"), 
	populationFile = file.path(rootDir, "Pop500_p1p2p3.csv"), 
	outputs = myOutput,
	simulationSetName = "Set1"
)

popWorkFlow <- PopulationWorkflow$new(workflowType = PopulationWorkflowTypes$parallelComparison, simulationSets = list(popSimSet1), workflowFolder = file.path(rootDir, "Output"))

# Number of cores for population simulation
popWorkFlow$simulatePopulation$settings$numberOfCores <- 1

inactivateWorkflowTasks(popWorkFlow, tasks = c("plotDemography", "plotGoF", "populationSensitivityAnalysis", "plotSensitivity", "populationPKParameters", "plotPKParameters")) 
activateWorkflowTasks(popWorkFlow, tasks = c("simulatePopulation", "populationPKParameters", "plotPKParameters"))

popWorkFlow$runWorkflow()
```
</details>

```
[1] "18/05/2020 - 12:26:32 : Starting Calculate PK parameters task"
[1] "18/05/2020 - 12:26:32 : Calculate PK parameters for simulation set Set1"
[1] "18/05/2020 - 12:26:32 : PK parameter calculation completed."
[1] "18/05/2020 - 12:26:32 : Starting: Get tables of PK parameters task in Alpha Testing"
Error in rClr::clrCall(pkAnalysisTask, "ImportPKAnalysesFromCSV", filePath,  :
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Error: Unable to convert to mg/l.
Molecular Weight not available.
Method:  Void ThrowOnError()
Stack trace:
  at OSPSuite.Infrastructure.Import.Services.ImportLogger.ThrowOnError () [0x0001b] in <d5d71b0936894ccd963ee55016fea839>:0
  at OSPSuite.R.Services.PKAnalysisTask.ImportPKAnalysesFromCSV (System.String fileName, OSPSuite.Core.Domain.IModelCoreSimulation simulation) [0x0001f] in <cb99a11108b647a59940d5b0cd2788f5>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <661ac729a4044e1ba201a46a16246771>:0
```

**Comment by msevestre** [comment]
I don't think there are unnecessary conversions. The tool should always convert no matter what. Clearly, somewhere, mg/l is asked for and that's why it does not work

>Message: Error: Unable to convert to mg/l.

**Comment by msevestre** [comment]
@Yuri05 Where is this unit used?

**Comment by Yuri05** [comment]
lol, that's exactly my question. All units in the workflow are **molar**, all base units are **molar**, I don't see any place where mg/l would be asked for.
Even more interesting: the original model does not contain any _concentration_ at all, only **amounts**:
![grafik](https://user-images.githubusercontent.com/25061876/82242338-f2930e80-993d-11ea-9647-26ae6f4dce9e.png)

**Comment by msevestre** [comment]
PKAnalysis
ImportPKAnalysesFromCSV

**Comment by Yuri05** [comment]
OK, there are 2 problems here:
1. The user tried to define Cmax for a curve which dimension is Amount. Base Unit of Cmax is [µmol/l], so actually an error should be produced. Instead, PK-Values where calculated and somehow interpreted as Molar Concentration (just noticed that **Output\PKAnalysisResults\Set1-PKAnalysisResults.csv** exported CMax in the Unit **[µmol/l]** )
2. The conversion between [µmol/l] and [mg/l] occurs in somewhere in ImportPKAnalysesFromCSV. Why? PKAnalysis is saved in [µmol/l] and Base unit of Cmax is [µmol/l].

**Comment by pchelle** [comment]
>     1. The user tried to define Cmax for a curve which dimension is Amount. Base Unit of Cmax is [µmol/l], so actually an error should be produced. Instead, PK-Values where calculated and somehow interpreted as Molar Concentration (just noticed that **Output\PKAnalysisResults\Set1-PKAnalysisResults.csv** exported CMax in the Unit **[µmol/l]** )

If my understanding is correct, `C_max` PK Parameter is a necessarily a concentration. 
So, RE will throw an error because the unit is not from the correct dimension.
User will need to define their own PK parameter using the function `addUserDefinedPKParameter`.

>     2. The conversion between [µmol/l] and [mg/l] occurs in somewhere in ImportPKAnalysesFromCSV. Why? PKAnalysis is saved in [µmol/l] and Base unit of Cmax is [µmol/l].

Since this is something happening within `importPKAnalysesFromCSV`, should the issue be moved to `ospsuite` ?
Just out of curiosity, is the conversion happening during import because you can export with a certain `displayUnit`. So you would need to ensure that your PKAnalysis object get at least baseUnit of what was exported ?

**Comment by Yuri05** [comment]
>If my understanding is correct, C_max PK Parameter is necessarily a concentration.
So, RE will throw an error because the unit is not from the correct dimension.
User will need to define their own PK parameter using the function addUserDefinedPKParameter.

So now the error is thrown? If yes: this is the corect behaviour, as expected. Because in the past it was not he case.

**Comment by pchelle** [comment]
It will with PR #1034

**Comment by Yuri05** [comment]
ok, I created the issue https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1242 for the 2nd part and closing this issue now

**Comment by Yuri05** [comment]
let the PR close :)
