### ISSUE TITLE
Error when try to plot in PopWorkFlow

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#191]
I settet up a Popworkflow, then trun it with default tasks. 
Afterthat, I recreate the WF and activate all the plot tasks deactivate the allready run tasks. 
Something crashed
> popModelWF$runWorkflow()
[1] "18/05/2020 - 13:43:10 : Starting run of population workflow"
[1] "18/05/2020 - 13:43:10 : Report './Output/Report.md' was initialized successfully."
[1] "18/05/2020 - 13:43:10 : Starting: Plot Sensitivity task in Alpha Testing"
[1] "18/05/2020 - 13:43:10 : Plot Sensitivity task in Alpha Testing for Rifampin po, 450 mg, Bioequivalence - PopSim"
[1] "18/05/2020 - 13:43:10 : Starting: Get tables of PK parameters task in Alpha Testing"
Error in validateIsOfType(object, c("numeric", "integer"), nullAllowed) : 
  $: argument 'object' is of type 'logical', but expected 'numeric, or integer'!popModelWF: argument 'object' is of type 'logical', but expected 'numeric, or integer'!runWorkflow: argument 'object' is of type 'logical', but expected 'numeric, or integer'!

[Model.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4644139/Model.zip)

**Comment by Yuri05** [comment]
@ThomasGaub 
I could reproduce the error here (but was not able to reproduce with a smaller simple example).

However with the smaller example I saw another problem.

```
pkFtend <- PkParameterInfo$new(pkParameter = "C_tEnd", displayName = "F_tend", displayUnit = '%')
outUrine <- Output$new(path = 'Organism|Kidney|Urine|Rifampicin|Fraction excreted to urine',
                       displayName = 'excreted to urine',
                       displayUnit = '%',
                       pkParameters = c(pkFtend))
```

This would not work. Because C_tEnd has the dimension "concentration", which cannot be converted to "%"

For this you would need to define a user defined pk parameter, e.g.
```
F_tend <- ospsuite::addUserDefinedPKParameter("F_tend", standardPKParameter = StandardPKParameter$C_trough, displayUnit = "%")
F_tend$dimension = "Fraction"
pkFtend <- PkParameterInfo$new(pkParameter = "F_tend", displayName = "F_tend", displayUnit = '%')
```
(however at the moment this would not work due to https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/192)

**Comment by Yuri05** [comment]
@ThomasGaub Sensitivity calculation for this example took more than 5 hours on a 8-Core PC.
Are you sure you want include sensitivity into this "standard" test example?

**Comment by ThomasGaub** [comment]
F_tend is then a goog canidate to add, was there in matlab

@ testcase: Only done once, then just doing plots

**Comment by ThomasGaub** [comment]
Fixed in current version thx
