### ISSUE TITLE
Pop PK-Parameters wrongly calculated in case of >1 output per simulation set

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#194]
[09_pk.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4653695/09_pk.zip)
In the example attached (pop with **500** individuals) 2 curves are selected for output.
```
popSimSet1 <- PopulationSimulationSet$new(
        simulationSetName = "Set1",
	simulationFile = file.path(rootDir, "MiniModel2.pkml"), 
	populationFile = file.path(rootDir, "Pop500_p1p2p3.csv"), 
        outputs = c(concentrationA,fractionA)
)
```
Report says now "1000 individuals" and all pk numbers are wrong.
![grafik](https://user-images.githubusercontent.com/25061876/82386481-cd34fc00-9a34-11ea-8d22-7713cee42b72.png)

If I remove the second curve from the simulation set, the numbers are correct (verified via [PK-Sim project](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4653729/MiniModel2_02.zip))

```
popSimSet1 <- PopulationSimulationSet$new(
        simulationSetName = "Set1",
	simulationFile = file.path(rootDir, "MiniModel2.pkml"), 
	populationFile = file.path(rootDir, "Pop500_p1p2p3.csv"), 
        outputs = concentrationA
)
```
![grafik](https://user-images.githubusercontent.com/25061876/82386525-efc71500-9a34-11ea-9b94-caecac92bffe.png)

Seems that PK-calculation does not filter by curve and uses the data from ALL curves of a simulation set.

**Comment by msevestre** [comment]
I don't understand the issue
What pk calculation are you referring to?

**Comment by Yuri05** [comment]
All pk parameters calculated for the report.

**Comment by msevestre** [comment]
But what is the issue? Is this the usage of the PK Parameters or the calculation of the PK Parameters
@abdullahhamadeh Can you please look at that asap please? This could be a major issue if we need to work in OSPSuite.Core to fix this

**Comment by msevestre** [comment]
@Yuri05  Actually looking at the table, it looks like a bug in the reporting engine correct?

**Comment by Yuri05** [comment]
>Actually looking at the table, it looks like a bug in the reporting engine correct?

Yes. Seems that the filtering by output is missing, that's why we get 1000 individuals (pop with 500 individuals and data from 2 outputs)

**Comment by abdullahhamadeh** [comment]
@pchelle from which functions are these tables generated? aggregationSummary?

**Comment by pchelle** [comment]
I found the issue: the selection was supposed to look for the QuantityPaths in output path but I inverted them in the code. So the solution was always true and took it all.
I also noticed and fixed the unit conversion in the process.
I'm adding the fix to the current PR
