### ISSUE TITLE
Error reading observed data in POP GoF task

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#199]
[GOF_Data_Crash.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4671720/GOF_Data_Crash.zip)
```
[1] "23/05/2020 - 14:02:30 : Plot Goodness of Fit task in Alpha Testing for Rifampin po, 450 mg, Bioequivalence - PopSim"
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 1 did not have 13 elements
```

**Comment by abdullahhamadeh** [comment]
I think the HGHT column is missing in the nmdat file

**Comment by msevestre** [comment]
Ok it's important that we get better error messages when a file does not have the right format

**Comment by Yuri05** [comment]
@abdullahhamadeh yep, you are right - observed data file is corrupted.
I have added missing data [Rifampicin_NMdat.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4672354/Rifampicin_NMdat.zip)

With this modified dat file I got another error: 
```
[1] "23/05/2020 - 20:51:28 : Plot Goodness of Fit task in Alpha Testing for Rifampin po, 450 mg, Bioequivalence - PopSim"
Error in `[.data.frame`(dictionary, , "ID") : undefined columns selected
```
Any idea if something is wrong in the data and/or dictionary or it's a bug?

**Comment by pchelle** [comment]
The R function `read.csv` uses a comma as the default separator while the dictionary of this test uses a semi-colon.

**Comment by Yuri05** [comment]
Yep, that did the trick. Closing
