### ISSUE TITLE
Sorting of "Input"-section elements

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#200]
I don't know if it belongs to the Reporting Engine or the QualificationRunner.

The "Input"-section of the report (`    "Inputs": [`) in the qualification plan is currently (in Matlab) sorted alphabetically and not by the order of their definition in the import. So

```
    "Inputs": [
        {
            "Project": "MyProject",
            "Name": "Standard European Male for DDI",
            "Type": "Individual",
            "SectionId": 31
        },
        {
            "Project": "MyProject",
            "Name": "AbcPop",
            "Type": "Population",
            "SectionId": 31
        },
        {
            "Project": "MyProject",
            "Name": "S-Compound",
            "Type": "Compound",
            "SectionId": 31
        }
    ]
```

creates a report where the building blocks are listed in the following order: Population, Compound, Individual. It would be better if the order would be as defined in the json.

**Comment by Yuri05** [comment]
supposed to be fixed in R-RE
