### ISSUE TITLE
What parameters to display in sensitivity plots?

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#204]
ospsuite has its rules for determining what sensitivities to return.  Sometimes, parameters with low sensitivity may not be returned in the sensitivity analysis results.  We need to decide, for reporting engine, do we follow the same rules or not?

ie we have two choices:

1) If we specify a set of paths to perturb, the sensitivity analysis result CSV will include all of those parameters unless they are zero in the simulation. We can then apply a filter that picks the top x% most sensititve parameters in the CSV. If we set x=100 then all the parameters will show up in the sensitivity plot.

2) If we use the ospsuite rules (function `allPKParameterSensitivitiesFor`) then it may return only a subset of those parameters and only those will show up in the plot. Even if totalSensitivityThreshold = 1.
Using option 2 we might get the following outcome:
![image](https://user-images.githubusercontent.com/18409098/82836575-bd824100-9e94-11ea-8808-f00e7602163a.png)

The sensitivity for individual at quantile 0.05 is zero with respect to all parameters.  ospsuite returns all five (red) sensitivities.  For the individual at quantile 0.95,  the sensitivity is non zero with respect to liver, kidney and muscle, and zero wrt lung an heart.  In this case, for this individual,  ospsuite only returns the sensitivities that are non-zero (blue).

**Comment by msevestre** [comment]
Not that this case with the red dots is like that because NONE of those parameters are sensitive for the red simulation.

**Comment by Yuri05** [comment]
I think all the questions here are clarified now.
@abdullahhamadeh @msevestre Please reopen if not.
