### ISSUE TITLE
Markdwon report: Links in TOC are invalid

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#219]
s. e.g. https://github.com/Yuri05/RE-Advanced-Examples/blob/master/02_MeanModel_Raltegravir_inclSens/Report/Report.md

Links are missing chapter numbers in the URL
![grafik](https://user-images.githubusercontent.com/25061876/84281936-74d7b280-ab39-11ea-8fcf-695d28e870f5.png)

![grafik](https://user-images.githubusercontent.com/25061876/84282053-92a51780-ab39-11ea-820a-3705895607df.png)

**Comment by Yuri05** [comment]
not fixed

**Comment by pchelle** [comment]
Can you confirm the logic of the markdown link:
Spaces need to be replaced by "-" and special characters (e.g. "." or "(" ) should be removed to get a valid link correct ?

**Comment by Yuri05** [comment]
@pchelle yes.
1. Replace all spaces by "-"
2. Remove all chars which are not letters, digits or "-".
3. Downcast the string
Then it should be fine
