### ISSUE TITLE
Calculate Population PK Parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#23]
# Inputs
* Output folder of the Simulate population task (with calculated simulation results)
* Output Folder for results (all results will be generated here)
* OPTIONAL Number of Cores
* List of populations (this also includes definition of PK-Parameters of interest)
* OPTIONAL Name of the user-defined function for calculation of "non-standard" PK-Parameters

# Outputs
* For each combination of `{Population, PK-Parameter, Model output}` 
  * PK-Parameter is calculated for all Individuals and stored in the output folder

# Remarks
Sometimes it's required to calculate "non-standard" PK-Parameter which are not part of the basis toolbox. In such a case user MUST provide a function for calculation. 
Function template for the current implementation in Matlab: https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/src/code/templates/myCalculatePKParameterForApplicationProtocol.m

**Comment by msevestre** [comment]
>Sometimes it's required to calculate "non-standard" PK-Parameter which are not part of the basis toolbox. In such a case user MUST provide a function for calculation.

This won't be compatible with Sensitivity Analysis. I am not sure if this is required but if it is, we will have to rethink the whole concept

**Comment by Yuri05** [comment]
I think we can reach it with a small extension:
* Provide functions, which return Time values array and for the given model output: all simulated value arrays calculated for this output (`2*NumberOfSteps+1` arrays)
* Extend the function `allPKParameterSensitivitiesFor `with an optionally passed array of **precalulated** PK-Values (if not passed: OSPSuiteCore will calculate PK-Values; otherwise: just directly use passed PK-Values)

(I guess providing an R-Callback via rClr is not possible?)

**Comment by Yuri05** [comment]
Regarding "required or not": I don't think it will be possible to include every potentially required PK-Parameter into a "standard" calculation.
I am even not sure, if we should include the "standard RE PK-parameters" (calculated [here](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/src/code/templates/myCalculatePKParameterForApplicationProtocol.m)) into OSPSuiteCore.

**Comment by msevestre** [comment]
>xtend the function allPKParameterSensitivitiesFor with an optionally passed array of precalulated PK-Values (if not passed: OSPSuiteCore will calculate PK-Values; otherwise: just directly use passed PK-Values)

That won't work like that. The pK values are used already beforehand as soon as the sensitivity calculation is finished. But I guess we can implement another method for R that will not calculate those parameters. That would be a 3 steps process for R
=> Run all SA in .NET
=> Return to R, calculate the PK somehow
=> Pass the PK back to .NET and we put everything together again

Doable probably but not straight forward 

>(I guess providing an R-Callback via rClr is not possible?)
