### ISSUE TITLE
Error in seq.default(-xmax, xmax, 2 * xmax/100) :    'from' must be a finite number

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#240]
During the execution of attached Workflow, I get the following error message:
Error in seq.default(-xmax, xmax, 2 * xmax/100) : 
  'from' must be a finite number

An version of this workflow worked, before the LLOQ was integrated into the GoF plots

[Test_NO11_LLOQ.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4785448/Test_NO11_LLOQ.zip)

**Comment by Yuri05** [comment]
Fixed with one of the last PRs
