### ISSUE TITLE
Time profiles disappeared

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#243]
After integration of the PR #223: all time profile plots are not there (both for Population and MeanModel-workflows). Only residual plots show up in the "Time profile and residual" section.

(s. e.g. reports under https://github.com/Yuri05/RE-Advanced-Examples/ )

**Comment by pchelle** [comment]
There were so many plots in the advanced examples I did not notice time profiles were missing...
The residual plots were overwriting the time profiles within the list of plots
Fixing this in PR#244
