### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#248]
Goal: at least 60-70%
![grafik](https://user-images.githubusercontent.com/25061876/85425942-1e776480-b57a-11ea-9081-5310f51140ba.png)

**Comment by msevestre** [comment]
@Yuri05 not for milestone 1 right?

**Comment by ThomasGaub** [comment]
We need definetive more coverage to use it in a validated Environment.

**Comment by msevestre** [comment]
Interesting. I can't remember any automated  unit test in the old version?,🤔

**Comment by ThomasGaub** [comment]
That lead to more documentation effort. 
But with >40% I think we are OK for the Moment.
