### ISSUE TITLE
Remove tracelib debug output

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#257]
![grafik](https://user-images.githubusercontent.com/25061876/86359809-c9baa480-bc71-11ea-8118-aeafbbc355a2.png)

**Comment by msevestre** [comment]
Just to be sure. tracelib is optional right?

**Comment by Yuri05** [comment]
yes, is optional. If not installed: nothing will happen, all tracelib calls will just stop, e.g.
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/2cdbd476123d82d94b6d61e78435c42b2c2c47ec/R/utilities-tracelib.R#L1-L10
