### ISSUE TITLE
Pop-workflow: crash in Plot PK parameters task

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#265]
[17.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4890243/17.zip)
```
[1] "08/07/2020 - 13:06:26 : Starting: Plot PK parameters task"
Error in if (pkParametersMetaDataAcrossPopulations[[demographyParameter]]$class %in%  : 
  argument is of length zero
In addition: Warning message:
In if (yAxis$ticks %in% "default") { :
  the condition has length > 1 and only the first element will be used
```

**Comment by pchelle** [comment]
Default parameters for range plots are 'Organism|Age', 'Organism|Height', 'Organism|Weight', 'Organism|BMI', 'Gender' but only 'Gender' is included in the population.
I can either add a method validateIsIncluded here to check if these parameters are in the population and throw an error if not.
Or I can only select the intersection while sending a warning for unselected parameters.
Let me know which one you prefer

**Comment by Yuri05** [comment]
>Or I can only select the intersection while sending a warning for unselected parameters.

Would prefer this solution. If one day we create a RE workflow for e.g. an animal population, some of the "standard" covariates (Age, Height, ...) will be missing as well.
