### ISSUE TITLE
Pop-workflow: crash in PK parameters task #2

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#266]
[18.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4890277/18.zip)
Worked with RE 1.0.42. Now:
```
[1] "08/07/2020 - 13:15:52 : Starting: Plot PK parameters task"
Error in if (diff(log10(boxRange)) >= 1) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(values) : no non-missing arguments to min; returning Inf
2: In max(values) : no non-missing arguments to max; returning -Inf
3: In diff(log10(boxRange)) : NaNs produced
```

**Comment by pchelle** [comment]
AUC_inf values are all 0 for every individual of the population... Is this normal ?
As a consequence, I am adding another check which will prevent plots of log scale boxplots. 
The RE warning message would end up the following: 
`"AUC_inf of Organism|A|Concentration does not include any positive data. Logarithmic scale plot cannot be output"`
Let me know if this is okay.

**Comment by Yuri05** [comment]
>AUC_inf values are all 0 for every individual of the population... Is this normal ?

Usually not. Well, this is an artificial example. For some other parameters however this still could happen (e.g. t_max).

>The RE warning message would end up the following:
"AUC_inf of Organism|A|Concentration does not include any positive data. Logarithmic scale plot cannot be output"
Let me know if this is okay.

Fine with that.
