### ISSUE TITLE
Sensitivity plots: parameter display names in RE and in MoBi differ

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#278]
E.g. take the example from #276. RE parameter paths contain "Organism", MoBi parameter paths do not.

<img width = "400" src="https://user-images.githubusercontent.com/25061876/88276655-b7b3ab00-ccdf-11ea-8330-28c3e8a1b127.png"><img width = "400" src="https://user-images.githubusercontent.com/25061876/88276867-0d885300-cce0-11ea-949d-6e2a5a7e11db.png">

**Comment by msevestre** [comment]
@Yuri05 Is the right plot from MoBi or PKSim? MoBi uses exactly the same code so I am a bit puzzled

**Comment by msevestre** [comment]
oh ok found it.We have a special implementation for R: e.g. what to show  in path

**Comment by msevestre** [comment]
and I copied the implementation from PKSim which adds organism I believe

![image](https://user-images.githubusercontent.com/1041237/101024241-d0f81e00-3541-11eb-9201-032209da7f23.png)

**Comment by msevestre** [comment]
Ok so I can make sure R and MoBi have the same behavior. Then we should decide if we should also update PK-Sim
