### ISSUE TITLE
Height plots have Wrong Unit

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#279]
![image](https://user-images.githubusercontent.com/25481071/88376962-b2696580-cd9e-11ea-9e2f-ec37e8c8e4ac.png)

The Values in the Tables are in dm and not cm. Unit Conversion would be helpfull

**Comment by pchelle** [comment]
@msevestre @Yuri05 
I noticed that parameters like `Organism|Height` have `unit` and `displayUnit`. 
However, it seems like `displayUnit` is not actually used, especially when extracting the data with `populationAsDataFrame`.
Do you want to update or create a method that will show the population values in their displayUnit directly from `ospsuite` ? 
Do you prefer I do the conversion with the Reporting Engine ? or do you prefer I use only `unit` (= PK Sim base unit) for such plots ?

**Comment by msevestre** [comment]
@pchelle populationAsDataFrame should return, in my opintion, the exact same values as the population but in the data frame
No conversion performed in this case
The fact that you have the displayUnit available is a way for you to display the values in a unit that makes sense to the user. 


>Do you want to update or create a method that will show the population values in their displayUnit directly from ospsuite ?

We might do it eventually but not at the moment. There is a method that converts an array to a unit to it's very easy to wrap anyways

>Do you prefer I do the conversion with the Reporting Engine ? 

Yes

>or do you prefer I use only unit (= PK Sim base unit) for such plots ?

No. Height in dm does not mean much to anyone but us :)
