### ISSUE TITLE
Crash in PopWorkflow/PlotGoF

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#286]
[14_12_Population.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/4990254/14_12_Population.zip)
```
[1] "28/07/2020 - 19:56:10 : Plot Goodness of Fit task for Larson 2013 8-18y meal"
Error in parse(text = paste0(variableName, "<- data[,\"", variableName,  : 
  <text>:1:1: unexpected '<'
1: <
    ^
```

**Comment by pchelle** [comment]
There seems to be a weird encoding issue here:
The first variable from the Nonmem dataset "ID" is read as "<U+FEFF>ID" instead.
The error then happens in the preparation step of the Nonmem dataset variables: the parsed expression should be `ID <- data[,\"ID\"]` but instead became: `<U+FEFF>ID <- data[,\"<U+FEFF>ID\"]`

I can think of two ways to fix this type of errors, let me know which seems better 
1) Add another checking of the Nonmem dataset when creating the `SimulationSet` which throws an error or warning if Nonmem variables include forbidden characters
2) Remove forbidden characters as they are read from the Nonmem dataset (and maybe also throw a warning if forbidden characters were removed)

**Comment by Yuri05** [comment]
@pchelle Please remove `<U+FEFF>` **without** warning.

The file is UTF-8 encoded. After some research: `<U+FEFF>` is byte order mark (BOM) which might be added by some applications (e.g. Excel) when writing a csv.
