### ISSUE TITLE
Standardization of workflow task names

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#293]
@msevestre @Yuri05 @abdullahhamadeh @ThomasGaub 
I created an issue to let you know that with the last PR, some of the task names have changed. 
The goal is to have clearer understanding of what they do as well as to standardize the nomenclature between population and mean model workflows.
- The common simulation tasks are now the same for both type of workflows: `simulate`, `calculatePKParameters` and `calculateSensitivity`.
- I also created the enum `StandardSimulationTasks` so they can be called more easily.
- Similarly, common plot tasks for both workflows are: `plotTimeProfilesAndResiduals`, `plotPKParameters` and `plotSensitivity`.
You can notice that `plotTimeProfilesAndResiduals` replaces `plotGoF`.
- I also created the enum `StandardPlotTasks` so they can be called more easily.
- The other tasks, which did not change, are specific to their workflow so they don't appear in these enums: `plotMassBalance`, `plotAbsorption` and `plotDemography`.

Let me know if you are okay with this new nomenclature.

**Comment by Yuri05** [comment]
>Let me know if you are okay with this new nomenclature.

yes!!
