### ISSUE TITLE
Histogram of Residuals and NA

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#307]
With the latest RE, the standard distribution graph has slightly changed in the histogram of residuals plot.
Has probably to do with the number of residuals. 
Should be checked

[Input.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5103508/Input.zip)
[Report_OLD.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5103507/Report_OLD.zip)
[Report_NEW.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5103509/Report_NEW.zip)

![grafik](https://user-images.githubusercontent.com/25061876/90778589-1bd88780-e2fd-11ea-8fc5-adcab2b664c6.png)
![grafik](https://user-images.githubusercontent.com/25061876/90778707-40346400-e2fd-11ea-9650-49cdcc24b5bb.png)

**Comment by pchelle** [comment]
Good catch.
Unlike Matlab which includes a function that "fits" the density curve to the histogram, `ggplot2` or `stats` only provides a function to get the raw density curve of a normal distribution (the profile does not account for different bins or number of bins).
Currently, I need to manually scale the curve by a factor of __Number of residuals / Number of bins__ (to transform into non NA residuals), but I don't think this is the most appropriate for the plot. 
I can estimate the scaling value by optimization, but I don't know if this is okay.
Thoughts ?

**Comment by pchelle** [comment]
While searching on the topic, I found another way which might be better.
The function `hist` from the base package `graphics` gets the histogram counts and corresponding density values based on the input data and bins. The scaling factor of the density curve I needed can be calculated directly from these 2 outputs.

**Comment by sfrechen** [comment]
@pchelle @Yuri05 @abdullahhamadeh 
I think you should normalize each group of residuals (for each source) before plotting by the respecive standard deviation of the residuals of the respective source. That makes the residuals comparable:

```
for ii = 1:length(uniqueSourceIndices)
    residuals(ii==sourceIndex) = residuals(ii==sourceIndex)/std(residuals(ii==sourceIndex));
end
```

I am actually not sure whether this was the case before (though it should) in RE 2.0. I remember that I once implemented/fixed it manually to RE 1.0.

**Comment by pchelle** [comment]
I have a few questions regarding what you suggest:
1) Plots of Residuals appear at 2 levels: do we need to normalize at both levels or just at the level between simulations ?
Level 1 is within simulation sets residuals can be associated to specific output paths
Level 2 is between simulation sets residuals can be associated to specific simulations
2) In the plot, we define Residuals = log(Obs)-log(Sim); I think we should change the nomenclature for such plots ?
It can become Normalized Residuals or Weighted Residuals instead with a definition like Normalized Residuals = (log(Obs)-log(Sim)/ StD Residuals ?
3) Do we want to keep both versions of residual plots ?
4) I think the normalized/weighted residuals should also be saved in the csv, then. But let me know if I am wrong.

**Comment by sfrechen** [comment]
> Plots of Residuals appear at 2 levels: do we need to normalize at both levels or just at the level between simulations ?

Suggest to normalize only at Level 1. If output (observer) is the same between simulations, no normalization needed at this level.

> In the plot, we define Residuals = log(Obs)-log(Sim); I think we should change the nomenclature for such plots ?

Yes. Normalized Residuals is fine for me.

> Do we want to keep both versions of residual plots ?

What is the second version? Just plot the nornalized one (I would say). I thought plotting raw residuals does not make sense in case of multiple outputs.

> I think the normalized/weighted residuals should also be saved in the csv, then. But let me know if I am wrong.

Yes. Please save both.
