### ISSUE TITLE
Inconsistent path handling when calling addTableChunk and addFigureChunk

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#310]
When calling `addFigureChunk` in plot-task$saveResults or population-plot-task$saveResults or gof-plot-task$saveResults,
the workflowFolder IS NOT included into the figureFile path.

When calling `addTableChunk` in  in plot-task$saveResults or population-plot-task$saveResults or
calling  addFigureChunk in  gof-plot-task$runTask,
the workflowFolder IS included into the figureFile path.

Is there a specific reason for that?

This behaviour makes it difficult to provide a consistent handling on paths in renderWordReport to add file metadata to tracelib.
Currently here the path is expected without workflowFolder and that is added here:
` re.tStoreFileMetadata(access = "read", filePath = file.path(logFolder, usedFile))`

If consistent usage of absolute paths (including the workflow folder) in all `addFigureChunk` and `addTableChunk` calls is possible, this would be the preferred way, then the line in renderWordReport should be changed to 
` re.tStoreFileMetadata(access = "read", filePath = usedFile)`

**Comment by pchelle** [comment]
Yes, the reason is that I have not found a way to include a table using its file path in the markdown report as it can be done for the figure.
Consequently, I need R to search for the file, read it and print the markdown table directly in the report which is why it includes the workflowFolder. 
For the figures, the path needs to be seen from the markdown file and consequently should not include the workflowFolder.

**Comment by ju-rgen** [comment]
Hm. 
1) Don't you include the workflowFolder into the markdown file in gof-plot-task$runTask calling addFigureChunk?
2) What would be the problem using absolute paths (including workflow folder) everywhere? Perhaps because the Report directory with the md file is intended to be transportable?
3) Could you then use consistently the relative Path below the workflow folder also when calling addTableChunk in plot-task$saveResults and population-plot-task$saveResults (and calling addFigureChunk in gof-plot-task$runTask )?
Because you pass the workflowFolder as logFolder anyway, inside addTableChunk the path could be concatenized.

**Comment by Yuri05** [comment]
>What would be the problem using absolute paths (including workflow folder) everywhere? Perhaps because the Report directory with the md file is intended to be transportable?

Of course it must be portable. So no absolute paths for sure.

**Comment by ju-rgen** [comment]
Hi Abdullah,

to summarize the demand:
Currently in addFigureChunk and addTableChunk the (relative) used file paths are collected (in temporary files) and used later in renderWordReport to specify the inputFiles for the report.
**At that point of time the (relative) file paths need to point to the plot- and table files.**
(so the base for the relative paths must be the working folder here)

Possibly here these relative file paths need to be extended (which is currently done by the logFolder).

*BTW: If there were a global object accessible (to store an actionToken) in addFigureChunk, addTableChunk and renderWordReport, then we could even get rid of the temporary files.*

In case of any questions, you can of course contact me.
