### ISSUE TITLE
PKParameterPlot crashes for 2 SimulationSets

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#312]
Error when executing attached Workflow
[1] "26/08/2020 - 17:09:09 : Starting: Plot PK parameters task"
Fehler in names(summary) <- c("N", sapply(quantiles, function(x) { : 
  Attribut 'names' [10] muss dieselbe Länge haben wie der Vektor [2]
[Test_NO8.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5130702/Test_NO8.zip)

**Comment by pchelle** [comment]
This is an interesting bug.
The Plot PK Parameters task is designed to plot boxplots comparing the __same__ PK parameters from the __same__ output paths among different simulations/populations.
Here, the output paths are not the same which ends up crashing the task, I will integrate a checking of this prior the plots.
The workflow would have passed if `outputs = c(outPlasma, outBone)` was used in both simulation sets.

This brings me another question: Is the comparison of the different paths an intended use of the PK parameters plot task ?

**Comment by Yuri05** [comment]
>This brings me another question: Is the comparison of the different paths an intended use of the PK parameters plot task ?

I would say: no. At least I don't see any use cases for this.

Interestingly, the workflow above does not crash if one of the populations has `outputs = c(outPlasma, outBone)` and another one just `outputs = outPlasma`

**Comment by ThomasGaub** [comment]
The intend of spliting the outputs was to seperate the TimeProfile Plots for each output.  
Then removing PK for the 2nd output everything works. 
So from my perspective we can depriotise this bug for a later Version or even close then TimeProfile plotting has some more options
