### ISSUE TITLE
dataDisplayName should be set on simulation level and not on output level

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#315]
Data selection (e.g. filter for study number XYZ) is done on simulation level, therefore, dataDisplayName should be set on this this level as well (e.g. 'Data from study XYZ')

**Comment by Yuri05** [comment]
Nothing to do here.
This must be done outside of RE when e.g. generating workflow.R from an Excel-Template
