### ISSUE TITLE
default SA plots generated when no pk specified in output

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#322]
When a simulation set has an output object with no PK parameters specified, the SA is evaluated for all valid PK parameters.  But for the SA plots:

- no plots are generated in the mean model workflow

- plots are generated for all valid pk parameters in the population workflow

Would it be better if the behavior is consistent, or is this by design?

**Comment by msevestre** [comment]
From @TWendl 
If not PK-Parameters are specified, we do not plot anything

@sfrechen What is your opinion

Does it need to be fixed for v1?

**Comment by msevestre** [comment]
@pchelle to check whether we can align behavior for v1 (e.g do not plot anything for now) until we have a maybe better solution for v2
