### ISSUE TITLE
pkParameters in Excel Workflow Input

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#334]
Currently pkParameters are set as individual entries in output with only a display unit.
The OSPSuiteR allows the global definition of display name and display unit for PK parameters.
An additional sheet name __pkParametersUpdate__ or something else could be created setting these values.
The output sheets would then only the names of the selected pkParameters to be shown by the workflow.
Thoughts ?

**Comment by Yuri05** [comment]
@pchelle I think with the new template we can close this issue?

**Comment by pchelle** [comment]
Yes, and we can also close the other issues related to the Excel inputs
