### ISSUE TITLE
Exception while using pie chart

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#335]
As already mentioned in https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/321 I still (mostly) experience an exception at this location (using v74 of RE now):
![grafik](https://user-images.githubusercontent.com/25579536/94435125-0592d680-019b-11eb-819a-d0465d62e4dd.png)

The scenario is this 
[12_tracelibMeanModel.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5292413/12_tracelibMeanModel.zip)

I add some sreenshots from the environments during debugging - hopefully that helps you to find the problem.
![grafik](https://user-images.githubusercontent.com/25579536/94430246-e04e9a00-0193-11eb-941a-90387bf68c3a.png)
![grafik](https://user-images.githubusercontent.com/25579536/94430272-e6447b00-0193-11eb-97d6-60958ff53eff.png)
![grafik](https://user-images.githubusercontent.com/25579536/94430338-ffe5c280-0193-11eb-987f-78256042d930.png)
![grafik](https://user-images.githubusercontent.com/25579536/94430352-07a56700-0194-11eb-884b-4f57b36a850e.png)
![grafik](https://user-images.githubusercontent.com/25579536/94430373-13912900-0194-11eb-860c-412de1bbbed1.png)

**Comment by pchelle** [comment]
I could not reproduce the bug, I am suspecting it is due to the version of `ggplot2` or `tlf`.
Can you specify which versions are used here ?

**Comment by ju-rgen** [comment]
tlf: 1.0.65
ggplot2 : 3.1.0

**Comment by pchelle** [comment]
The latest version for tlf is 1.0.68; I think updating the package should fix the issue.

One other note is that there was an update between ggplot2 version 3.1.0 and 3.3.0 which changed the behavior of some of the tlf functions. As a consequence, we decided to fix the lowest version of ggplot2 to 3.3.0 which is supposed to be a version encompassed by validR (PR 129 of tlf package). So, installing tlf 1.0.68 won't work if ggplot2 version is lower than 3.3.0.

@msevestre should we also fix the lowest required version of `tlf` and `ospsuite` for installation of `ospsuite.reportingengine`  ?

**Comment by ju-rgen** [comment]
Ok, this reinstallation seem to have finally resolved the issue.
I am still wondering, why 2 weeks ago sometimes it worked, sometimes not.
Hope, now it is stable.

**Comment by msevestre** [comment]
@pchelle 
> should we also fix the lowest required version of tlf and ospsuite for installation of ospsuite.reportingengine 

Yes this should be done. Can you create an issue for this, create one PR for this only fix on develop and we can decide whether to port it to the prerelease branch or not on Thursday
