### ISSUE TITLE
AUC and Cmax predicted/observed ratio

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#338]
Tables comparing predicted and observed AUC and Cmax values are required by regulatory agencies in evaluation/qualification reports. Will this kind of performance assessment be available in the reporting engine? I know that the Matlab-Engine is offering the Cmax pred/obs (didn't try it out, though), but I could not find such a functionality for the Cmax values.

**Comment by Yuri05** [comment]
Look e.g. at the plot and table comparing predicted AUC vs. observed AUC (same would be possible for Cmax):
https://github.com/Open-Systems-Pharmacology/OSP-Qualification-Reports/blob/master/Pediatric_Qualification_Package_CYP2C8_Ontogeny/report.md#evaluation-of-pediatric-translation
Isn't this what you are asking for?

**Comment by Yuri05** [comment]
>...but it is extremelly buggy

What exactly is buggy?

>... and undocumented

https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/qualification#plots 
(s. e.g. the subsection **PKRatioPlots**)

>Just wanted to check whether it is planned for the new engine.

Yes.

**Comment by PavelBal** [comment]
>What exactly is buggy?

The plots are always generated for the age, 

`GMFE = 10.^(sum(abs(log10(YallValues)))./size(YallValues, 1));`

fails (at least for me) when using "AUC|CMAX" as PK-Parameters. Actually here:

```
for k=1:length(PKParameter)
    fprintf('%s: GMFE = %f \n', PKParameter{k}, GMFE(k));
end
```
but if GMFE is calculated as above, its dimension is only dependent on `length(PKRatioGroups)` as in 

```
for i=1:length(PKRatioGroups)
    XallValues = [XallValues; XcellValues{i}];
    YallValues = [YallValues; YcellValues{i}];
    ObsallValues = [ObsallValues; ObscellValues{i}];
    PredallValues = [PredallValues; PredcellValues{i}];
    StudyallValues = [StudyallValues; StudycellValues{i}];
    AGEallValues = [AGEallValues; AGEcellValues{i}];
    BWallValues = [BWallValues; BWcellValues{i}];
end
```
and not on `length(PKParameter)`.

> (s. e.g. the subsection PKRatioPlots)
There is no word about how to define Cmax, no description on what inputs are supported (e.g., types of AUC), not how e.g. defining start and end times in the CSV document are handled, and so on...

**Comment by Yuri05** [comment]
Feel free to create bug reports and feature requests for the documentation.

**Comment by Yuri05** [comment]
@PavelBal The requirement regarding definition of additional PK parameters is defined in #655 and will be part of RE 2.0
For the requirement "Not only Age on the X-axis" please create a new issue and describe the expectation.
After that you can close this issue (the GMFE bug will hopefully not appear now due to complete reimplementation in R anyway)
