### ISSUE TITLE
User defined PK parameters in Excel Template

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#340]
Include functions to print definition of user-defined PK parameters

**Comment by pchelle** [comment]
@msevestre and @Yuri05 
I tried to run an example with the user defined PK parameters provided in the template. 
This creates: `F_tEnd <- addUserDefinedPKParameter("F_tEnd", standardPKParameter = StandardPKParameter$C_trough, displayUnit = "%")`
However, display unit is '%' while the dimension is a Concentration (inherited from C_trough and read only).

Since the current workflow for converting the unit in the reporting engine is:
1- Get the PK parameter object (`pkParameterObject <- ospsuite::pkParameterByName`)
2- Ensure PK parameter value is in base unit (`valueInBaseUnit <- ospsuite::toBaseUnit(dimension = pkParameterObject$dimension)`)
3- Convert base to display unit (`ospsuite::toUnit(valueInBaseUnit , dimension = pkParameterObject$dimension)`)
(steps 2 and 3 are needed in case users define different display units between different outputs/simulation sets using the object PkParameterInfo).

My test currently fails when calling `ospsuite::toUnit` as step 3 cannot convert a Concentration in %.
Looking at the PKAnalysis file, the units of F_tEnd was in µmol/l.

Can you let me know how unit conversion is supposed to work for user defined PK (maybe I did not define the parameter properly or there is an `ospsuite` function that would need to be called instead in this scenario or simply if it is user defined, base unit = display unit, so dimension = getDimensionForUnit(displayUnit) )

**Comment by Yuri05** [comment]
@pchelle Tried this, dimension is correctly set to "Fraction" then:
![grafik](https://user-images.githubusercontent.com/25061876/100437785-8e49c800-30a1-11eb-9db1-0c9b3212ecae.png)

Version of the ospsuite-package is 9.1.2

**Comment by pchelle** [comment]
Got it ! 
I was setting the display unit only from `updatePKParameter` but it is needed in `addUserDefinedPKParameter` to set the dimension. Thanks.
