### ISSUE TITLE
Estimate max. Cores per Session

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#347]
When running in "non-MPI" mode: estimate max. number of cores (threads) available in the user session and pass it to .NET
(use default if this estimation fails)

```
getAllowedCores <- function() {
  cores <- tryCatch({
    # get cpu allowance from files
    cfs_quota_us <- as.numeric(system("cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us", intern = T))
    cfs_period_us <- as.numeric(system("cat /sys/fs/cgroup/cpu/cpu.cfs_period_us", intern = T))
    cfs_quota_us / cfs_period_us
  },
  error = function(cond) {
    message("Error getting allowed cpu cores")
    return(NULL)
  },
  warning = function(cond) {
    message("Warning getting allowed cpu cores")
    return(NULL)
  })
}
```

**Comment by msevestre** [comment]
Return null??? What about all other use cases where this won't work?

**Comment by Yuri05** [comment]
Depends how the caller will use it. If the caller e.g. checks for null and then decides what to do - that's fine.
If the caller passes the return value directly to the ospsuite-r as an option - it should return the default value (e.g. `parallel::detectCores() - 1` )

**Comment by msevestre** [comment]
I dont think it should error or warn. This will only work with a very specific infrastructure and therefore should fail gracefully

**Comment by Yuri05** [comment]
>I dont think it should error or warn. This will only work with a very specific infrastructure and therefore should fail gracefully

I agree
