### ISSUE TITLE
Pop-workflow: Improve default binning for plotPK/plotDemography

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#383]
In the attached example 4 populations with 500 individuals each were defined: reference adult population for [30 .. 70] years and 3 children populations for [0 .. 3], [3 .. 6], [6 .. 9] years. 
All the age-dependency plots in PK/Demography show nothing for [0 ..3] and [0..6] populations and only very few bins for [6 ..9].

[01_bin.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5553247/01_bin.zip)
<details><summary><b>Expand to see the plots</b></summary>
<img src="https://user-images.githubusercontent.com/25061876/99386240-73719980-28d2-11eb-99a9-ad52d8940cc8.png">
<img src="https://user-images.githubusercontent.com/25061876/99386521-e549e300-28d2-11eb-8378-f26f7f29c7f8.png">
<img src="https://user-images.githubusercontent.com/25061876/99386549-f266d200-28d2-11eb-8db7-14cb59ec8f39.png">
<img src="https://user-images.githubusercontent.com/25061876/99386756-4376c600-28d3-11eb-87ff-e27063113f38.png">
<img src="https://user-images.githubusercontent.com/25061876/99386802-52f60f00-28d3-11eb-9680-49e0b0e22726.png">
</details>

The default binning algorithm should be improved so that every Range plot shows at least N bins per default.
(not sure what the good choice for N is. 10?)

**Comment by Yuri05** [comment]
@pchelle @abdullahhamadeh Same reason as in #318. I have also tried to set the bins **manually** as described in #318 - but did not manage to get any bins for child populations. Can you tell me hot to set the bins properly for the example attached if I want to have e.g. 10 bins in every range plot?

**Comment by pchelle** [comment]
Currently, binning manually 10 bins per population would give:
__`workflow$plotPKParameters$settings$xParametersBreaks[[StandardPath$Age]] <- unique(c(seq(0, 3, length.out=10), 
                                                                              seq(3, 6, length.out=10), 
                                                                              seq(6, 9, length.out=10), 
                                                                              seq(30, 70, length.out=10)))`__

**Comment by pchelle** [comment]
I went back into the code to see if I could find a solution,
currently the binning happens here: 
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/87b1313b59020b8bbc39fdf2ab05426b68267b44/R/utilities-calculate-pk-parameters.R#L263

but I could make it happen after the selection of the population: e.g.
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/87b1313b59020b8bbc39fdf2ab05426b68267b44/R/utilities-calculate-pk-parameters.R#L288

In which case, `settings$xParametersBreaks` can be renamed `settings$bins` for clarity.
And can become a 2-levels list (one level for the x parameter = `StandardPath$Age`, and one for the simulationSetName = "Kids 0-3 years") or an R6 object
Thoughts ?

**Comment by pchelle** [comment]
With the update of PR #387, the aggregation is now performed after the selection of the population.
Consequently, the default binning is performed by population and look much better (see example below).

![Kids 0-3 years-vs-ref-C_max-vs-Age](https://user-images.githubusercontent.com/45343665/99716703-6e4d4f80-2a76-11eb-9cf0-b17ef28d7dea.png)

**Comment by pchelle** [comment]
Moving forward, the setting of the bins will also be easier: 
`workflow$plotPKParameters$settings$bins <- 15 ` and 
`workflow$plotDemography$settings$bins <- 15 `

I also added from our discussion the setting for stairstep plot:
`workflow$plotDemography$settings$stairstep <- TRUE` to have stairstep plot (which is default)
`workflow$plotDemography$settings$stairstep <- FALSE` to link the aggregated values

**Comment by Yuri05** [comment]
really nice!
