### ISSUE TITLE
Display for parameters in Demography and plotPKParameters plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#390]
In a population workflow: display names for parameters used in Demography / plotPKParameters plots should be generated in the same way as in Sensitivity plots (actually exactly the **same function** should be used **in all task**s for this).

At the moment with the **default** parameters (weight, height, age, ...) it's not a problem (because they are unique). However as soon as I add e.g. any organ-specific parameters (e.g. Volume, etc.) - currently it's not clear which parameter is plotted.

E.g. `setYParametersForDemogrpahyPlot(workflow, c(getYParametersForDemogrpahyPlot(workflow), "Organism|Spleen|Volume")) `results in: 
![grafik](https://user-images.githubusercontent.com/25061876/100106312-b13d6780-2e68-11eb-8171-22c3a041f805.png)

Compare sensitivity plot:
![grafik](https://user-images.githubusercontent.com/25061876/100106648-185b1c00-2e69-11eb-840b-89f0e8371ea2.png)

**Comment by pchelle** [comment]
Now that `ospsuite` has the function `getParameterDisplayPaths`, this should be rather straightforward.
