### ISSUE TITLE
Option for residuals

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#395]
Residuals are currently log, need option for lin

**Comment by Yuri05** [comment]
Residual type should be defined per Output as additional constructor argument (optional; **log** as per default), e.g.

Output$new(
  path,
  displayName = NULL,
  displayUnit = NULL,
  dataSelection = DataSelectionKeys$NONE,
  dataDisplayName = NULL,
  pkParameters = NULL,
  **residualScale = ResidualScale$Logarithmic**
)
