### ISSUE TITLE
Dictionary for parameter display names

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#399]
Parameter paths are displayed in different tasks (plotSensitivity, plotDemography, plotPKParameters, ...).
At the moment display paths are retrieved via the ospsuite-function `getParameterDisplayPaths`.
While the result is ok in the most cases, sometimes user would like to override those standard display paths.
(e.g. for application/formulation parameters like below)
![grafik](https://user-images.githubusercontent.com/25061876/101020689-2ac30d00-356f-11eb-921a-b2792aa416ab.png)

For this I would suggest the following:
* Workflow would get a new property **ParameterDisplayPaths** (or **ParameterDisplayNames** or whatever), which is a **dictionary** mapping internal parameter paths to display paths
* User can add mapping via e.g. `workflow$ParameterDisplayPaths$Add(path = "Applications|oral 300mg|Xanthium as weibull|Dissolution time (50% dissolved)", displayName = "50% dissolution time")`
* All workflow tasks which display parameter names would look in the dictionary first. If there is an entry for a parameter path: the dictionary value for the display name is taken. Otherwise: `getParameterDisplayPaths()` is used (like now)

Thoughts?

**Comment by Yuri05** [comment]
@sfrechen @TWendl @msevestre please comment.

**Comment by msevestre** [comment]
I like the idea. I would sugget a different approach for the last part and encapsulate the behavior in a function that would first check in the dictionary and then use the default if not present. `getParameterDisplayPaths` should therefore never be used outside of this one function

**Comment by pchelle** [comment]
@msevestre and @Yuri05 
Currently, I am unable to implement the dictionary for sensitivity plots because pkSensitivities (results from `saResults$allPKParameterSensitivitiesFor`) are objects that internally translate the parameter path to its parameter display path.
Is there a way to get the actual paths from these objects ? Or is there any workflow I can use to get the actual paths ?
