### ISSUE TITLE
Units in data dictionary are ignored

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#413]
Time and measurment units from the data dictionary are ignored.
[mini_ObsData.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5982749/mini_ObsData.zip)
Example: data dictionary and data looks like below

ID|type|nonmenColumn|**nonmemUnit**|reportName|pathID|comment
--|--|--|--|--|--|--
time|timeprofile|TIME|**min**|||
dv|timeprofile|DV|**ng/ml**|||

TIME|DV
--|--
2|0.00559
4|0.0047
6|0.00269
8|0.00163

However observed data in the report is plotted in [h] and [µg/ml]:
![grafik](https://user-images.githubusercontent.com/25061876/107980670-f503c100-6fc0-11eb-9c96-42a95ba5b878.png)

**Comment by Yuri05** [comment]
@abdullahhamadeh @pchelle FYI 
(for some reason I cannot assign you to issues anymore...)

**Comment by Yuri05** [comment]
It does not work.  [25.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6215847/25.zip)

E.g. here data and dictionary are defined as following:
![grafik](https://user-images.githubusercontent.com/25061876/112724428-901e7d80-8f13-11eb-9317-6aa417f4c632.png)
![grafik](https://user-images.githubusercontent.com/25061876/112724436-a3314d80-8f13-11eb-8a36-a290943d84dc.png)

And the output is:
![grafik](https://user-images.githubusercontent.com/25061876/112724532-205cc280-8f14-11eb-91b9-7f05cd989887.png)

**Comment by pchelle** [comment]
@Yuri05 , I just tested the 2 examples and get the correct conversion.
The issue seems the one I identified in #453 which was fixed with PR #454
