### ISSUE TITLE
Allow switching application ranges off

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#419]
For the time profile plots in multiple administration simulation 3 time ranges are plotted: full range, first application range, last application range.
It should be possible to deactivate some of them (e.g. plot last application range only)

**Comment by pchelle** [comment]
@Yuri05 , do you remember which simulation files have multiple applications ?

**Comment by Yuri05** [comment]
@pchelle Here are 2 fast running simulations (1 IV and 1 PO) with 3 administrations each 
[RE_PBPK_Sims_3_Apps.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6182540/RE_PBPK_Sims_3_Apps.zip)

**Comment by pchelle** [comment]
Great. Thanks !

**Comment by Yuri05** [comment]
Turning application ranges on/off must be done per simulation set, not per wokflow.
At the moment it's done on the workflow level. Which (apart from missing flexibility) also results in some side effects. E.g. if I have 2 simulation sets in my workflow - one for a single administration and one for multiple - and I set the **total** application range to false: no time profiles are plotted for the single simulation at all.

**Comment by pchelle** [comment]
My bad, I thought it was supposed to be common between the simulations.
So, it means the option should be defined directly as an input/option of the `SimulationSet` objects, correct ?

**Comment by Yuri05** [comment]
>So, it means the option should be defined directly as an input/option of the SimulationSet objects, correct ?

yes, applicationRanges should become an optional input of a simulation set

**Comment by Yuri05** [comment]
[bug.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6317918/bug.zip)
```
Warning: 15/04/2021 - 14:37:27 : source: argument 'c(applicationRanges)' is of type 'character', but expected 'logical'!
Error: source: argument 'c(applicationRanges)' is of type 'character', but expected 'logical'!
```
