### ISSUE TITLE
Number of decimal places

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#424]
Especially in PK-Parameter-Tables there are sometimes too many decimal places which results in not so nice looking tables in Word reports. It should be possible to change the default number of decimal places.

![grafik](https://user-images.githubusercontent.com/25061876/108353194-24e0dd80-71e8-11eb-9e4d-add2a78b6a87.png)

**Comment by Yuri05** [comment]
Should "Number of decimal places" be defined on the **workflow** level (same for all tasks then) or on the **task** level?
@TWendl @Christoph27 @sfrechen

**Comment by pchelle** [comment]
I found the perfect function for this one: `format(x, nsmall, scientific)` with nsmall the number of decimals and scientific a logical defining if writing the numbers using a scientific notation.
I intend to pass the parameters using the Task settings objects
@Yuri05 what should be the default values for this feature ?

**Comment by msevestre** [comment]
check it out here
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/R/ospsuite-env.R#L18

**Comment by msevestre** [comment]
specifically
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/ecb2bb490e98dab0d1960ca30503629962ff03bc/R/messages.R#L99

**Comment by pchelle** [comment]
Awesome ! I'll add scientific to the argument for the re version.
Thanks @msevestre

**Comment by Yuri05** [comment]
sounds good! 
@pchelle Regarding the **default** for the scientific option: I would set it to **NA** which is the default of the format function.
https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/format

**Comment by pchelle** [comment]
I just pushed PR #436  
The format can either be modified in the field `settings` of `plotPKParameters` task (by updating `digits`, `nsmall` or/and `scientific`)
I have also added the function `setDefaultNumericFormat()` which modifies the global settings of those parameters.
I'll create a separate issue for documenting this
