### ISSUE TITLE
Improvement of warnings

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#428]
Currently a lot of warnings are created; many of them are unclear for users.

TODOs: 
- [x] Systematically go through all warnings created by ospsuite.reportingengine and check if the warning message can be improved (or the warning can be completely supressed)
- [x] For the warnings created e.g. by ggplot: check if they can be supressed

**Comment by pchelle** [comment]
Now errors and warnings are caught by function `logCatch()` which checks the content and log silently the unwanted warnings:

https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/6e5f92ecb73a91edebba22df9a5a7d300ddce2e0/R/utilities-logging.R#L172-L181
