### ISSUE TITLE
List (intermediate) output files whose names will change in RE 1.2

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#446]
Let's list here all (intermediate) output files (e.g. simulation results csv) whose file names will change in RE 1.2

**Comment by pchelle** [comment]
From issue #419 /PR #442 , all plot names in time profiles and residuals task have a shorter application range id. 
This affects intermediate files created and removed in 
- `tests/testthat/test-mean-model-gof.R` 
   - "A-timeProfile-Concentration-totalRange.png" ->"A-timeProfile-Concentration-total.png"
   - "A-timeProfileLog-Concentration-totalRange.png" -> "A-timeProfileLog-Concentration-total.png"
   - "A-obsVsPred-Concentration-totalRange.png" -> "A-obsVsPred-Concentration-total.png"
   - "A-obsVsPredLog-Concentration-totalRange.png" -> "A-obsVsPredLog-Concentration-total.png"
   - "A-resHisto-totalRange.png" -> "A-resHisto-total.png"
   - "A-resQQPlot-totalRange.png" -> "A-resQQPlot-total.png"
   - "A-resVsPred-Concentration-totalRange.png" -> "A-resVsPred-Concentration-total.png"
   - "A-resVsTime-totalRange.png" -> "A-resVsTime-total.png"
- `tests/testthat/test-pop-gof.R`
   - "A-timeProfile-Concentration-totalRange.png" ->"A-timeProfile-Concentration-total.png"
   - "A-timeProfileLog-Concentration-totalRange.png" -> "A-timeProfileLog-Concentration-total.png"
   - "A-obsVsPred-Concentration-totalRange.png" -> "A-obsVsPred-Concentration-total.png"
   - "A-obsVsPredLog-Concentration-totalRange.png" -> "A-obsVsPredLog-Concentration-total.png"
   - "A-resHisto-totalRange.png" -> "A-resHisto-total.png"
   - "A-resQQPlot-totalRange.png" -> "A-resQQPlot-total.png"
   - "A-resVsPred-Concentration-totalRange.png" -> "A-resVsPred-Concentration-total.png"
   - "A-resVsTime-totalRange.png" -> "A-resVsTime-total.png"

**Comment by pchelle** [comment]
From issue #395 / PR #430 :
- file `tests/data/mean-gof/All-Obs-residuals-lin.csv` was added to test **Linear residual scale**

**Comment by pchelle** [comment]
From issue #423 / PR #443 , tables use descriptor instead of `Population` as header of table.
This affects the following intermediate files: 
- `Plasma-AUC_tEnd-ratio.csv`
- `Plasma-AUC_tEnd.csv`
- `Plasma-C_max-ratio.csv`
- `Plasma-C_max.csv`

**Comment by pchelle** [comment]
From issue / PR: dictionary needs to include a unit in `nonmemUnit` or an `ID` for mapping unit to a data column
This affects the following intermediate file:
- `tests/data/input-data/tpDictionary.csv`

**Comment by pchelle** [comment]
> 
> 
> From issue #423 / PR #443 , tables use descriptor instead of `Population` as header of table.
> This affects the following intermediate files:
> 
>     * `Plasma-AUC_tEnd-ratio.csv`
> 
>     * `Plasma-AUC_tEnd.csv`
> 
>     * `Plasma-C_max-ratio.csv`
> 
>     * `Plasma-C_max.csv`

In the last PR, the default descriptor in the table was defined as "Population" which is now re-included in the header of these files

**Comment by pchelle** [comment]
From issue #463 /PR #466 , legends for time profile plots were adjusted
This affects the legend values in intermediate files:
* tests/data/mean-gof/
   * All-Obs-timeProfileData.csv
   * No-Obs-timeProfileData.csv
   * Select-Obs-timeProfileData.csv
* tests/data/pop-gof/
   * All-Obs-simulatedData.csv
   * No-Obs-simulatedData.csv
   * Select-Obs-simulatedData.csv
