### ISSUE TITLE
Sensitivity analysis requirements

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#45]
1) Need a method to extract a list of model parameters that are constant and that it makes sense to perturb (ie not gender, discrete variables)

2) Need a method to select a subset of the list in 1

3) Need a method to covert the subset of parameters (from 2) to a base R list of strings of paths for each parameter

4) Need a method to divide the list (from 3) among N cores, returning a base R list of strings of parameter paths (like in 3) that will be perturbed by each core.

5) Need a method to save the output of sensitivity analysis to CSV.

**Comment by msevestre** [comment]
@abdullahhamadeh all but 1 and 5 are reporting engine tasks, right?

**Comment by abdullahhamadeh** [comment]
Yes.  But I noticed that there is a numberOfCoresToUse option in SensitivityAnalysisRunOptions.  It seems like the goal there was for ospsuite to determine which parameters to assign to each core, so we wouldn't need step 4 if that's the case.

**Comment by msevestre** [comment]
hum no. `numberOfCoresToUse` will have to be set to 1 in your case as you are in charge for parallelization. The same goes for population simulation. It needs to be set to 1 to avoid over parallelization which would result in potential waste of time.

**Comment by Yuri05** [comment]
@abdullahhamadeh Closing. Please reopen if something is still missing on the ospsuite side.
