### ISSUE TITLE
Sensitivity plots: Simulation set desriptor not used in the plot legend

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#458]
In the example below simulation set descriptor was set to "Scenario". It is correctly used in the plot caption, but in the plot legend still "population" is used.
![grafik](https://user-images.githubusercontent.com/25061876/114305443-8a5e9580-9ad8-11eb-83f1-a4343d2d76aa.png)

**Comment by Yuri05** [comment]
now if the simulation set descriptor was not set (thus "Population" must be used) - no descriptor is shown at all
![grafik](https://user-images.githubusercontent.com/25061876/114764399-310a9680-9d64-11eb-81b2-4299114605a7.png)

if the simulation set descriptor was set - it's shown
![grafik](https://user-images.githubusercontent.com/25061876/114764573-66af7f80-9d64-11eb-95b7-71ae7131f86d.png)

**Comment by pchelle** [comment]
Okay. On it.
For the tables of population PK parameters, I removed the term "Population" if no descriptor was used.
Should I update them the same way or leave it empty if no descriptor is provided ?

**Comment by Yuri05** [comment]
>Should I update them the same way

Yes, if no descriptor was provided "Population" should be used
