### ISSUE TITLE
Sensitivity plot: legend cut off

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#459]
The legend is cut off. Is it possible to display the legend at least left-aligned?
![grafik](https://user-images.githubusercontent.com/25061876/114305569-f6d99480-9ad8-11eb-9b65-dc069fc0e770.png)

**Comment by pchelle** [comment]
This should be fixed or at least better displayed with PR #461 because descriptor and percentiles are indicated by columns instead of lines.
Below is a sample on one of my tests;

**Comment by pchelle** [comment]
![AUC_tEnd_Organism-A-Concentration in container](https://user-images.githubusercontent.com/45343665/114571763-e6dec380-9c44-11eb-9883-624f570bf649.png)

**Comment by Yuri05** [comment]
nice!

**Comment by Yuri05** [comment]
Still cut off is parapeter names are long. is it possible to align the legend on the left of the picture?

![grafik](https://user-images.githubusercontent.com/25061876/114764620-77f88c00-9d64-11eb-8793-10fd9da55786.png)

**Comment by pchelle** [comment]
@abdullahhamadeh , any luck on the issue ?

I may have found something that could work from https://stackoverflow.com/questions/25401111/left-adjust-title-in-ggplot2-or-absolute-position-for-ggtitle
The idea is to use the concept of grobs, in which positions are "absolute", so you know where the legend is within the whole figure.
My only issue in using this, is that "once you go grob, you never go back".
The plot cannot have any additional data or modifications of the plot content (so I would use it only in the RE for some restricted cases).

If you want to test,  here is the process:
```
# Get the grob object
grobObject <- ggplot2::ggplotGrob(plotObject)
# Current legend position ("l" means left side of the layout)
grobObject$layout$l[grobObject$layout$name == "guide-box"]
# Set legend position to left of the figure
grobObject$layout$l[grobObject$layout$name == "guide-box"] <- 1
```

**Comment by pchelle** [comment]
@Yuri05 can you remind me what should be the new default for the maximum number of parameters ?

**Comment by Yuri05** [comment]
@pchelle let's say 25.

**Comment by pchelle** [comment]
To fix the issue, I have included 2 new fields in the plotSensitivity task settings: `maxWidthPerParameter` and `maxLinesPerParameter`
* `maxLinesPerParameter` is the maximum number of lines for the display parameters. Default is 3 lines.
* `maxWidthPerParameter` is the maximum width for the display parameters. Parameters longer than that will have line breaks. Default is 25 characters.

If parameters are longer than `maxLinesPerParameter*maxWidthPerParameter`, they will only respect the maximum number of allowed lines.
Below is the result sensitivity plot using the example:

**Comment by pchelle** [comment]
![C_max_Organism-PeripheralVenousBlood-Raltegravir-Plasma (Peripheral Venous Blood)](https://user-images.githubusercontent.com/45343665/115852055-a70e9d80-a3f5-11eb-81ee-3f01dad41dba.png)

**Comment by Yuri05** [comment]
@pchelle Looks very nice - I like!
@TWendl @sfrechen FYI
