### ISSUE TITLE
RE 1.2: Time profiles crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#476]
Running this example [01_OrigDictionary.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6390302/01_OrigDictionary.zip) I get the crash below (would expect the explicit error message "units not set" instead):
```
[1] "28/04/2021 - 10:26:40 : Plot Time profiles and Residuals task for Theophylline"
Error in data.frame(Time = ospsuite::toUnit("Time", data[selectedRows,  : 
  arguments imply differing number of rows: 132, 0, 1
```
Now I adjust the dictionary (the unit for DV was missing in the data dictionary) and run it [02_dvunit.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6390353/02_dvunit.zip): another crash
```
[1] "28/04/2021 - 10:35:20 : Plot Time profiles and Residuals task for Theophylline"
Error in x[[jj]][iseq] <- vjj : replacement has length zero
```

**Comment by pchelle** [comment]
I have re-run with latest version (updating script to use DataSource and column names in dictionary) and got the following messages :

<details><summary>01_OrigDictionary.zip</summary>

```r
! Warning	In source:
'LOQ' column is not present in observed dataset columns: 'ID', 'STUD', 'SID', 'TIME', 'TAD', 'DV', 'CMT', 'MDV', 'AMT', 'WGHT', 'HGHT', 'SEX', 'AGE'.

Error: In source:
No definition provided for units of observed dataset.
Units for both dependent variable (dv) and time are required when using observed data.
Please make sure that a unit definition does not use multiple methods or that the methods define consistent units.
Available methods for units definition of observed data:
1) Define units directly in dictionary (metaDataFile) by providing the units in column 'datasetUnit' of your dictionary for ID(s) 'time' and/or 'dv'
2) Define units in your dataFile by including dedicated columns.
Then, provide the corresponding column name in the column 'datasetColumn' of your dictionary for ID(s) 'time_unit' and/or 'dv_unit'
3) Only for 'dv', define units in field 'dataUnit' when creating an
```

</details>

- RE spotted and just warned that **lloq** was defined but not used.
- RE crashed and warned that there was no unit for **dv** or **time** while providing the 3 available methods for their definition.
- 02_dvunit.zip worked with only the lloq warning message

**Comment by Yuri05** [comment]
sounds good. let's assume as fixed then :)
