### ISSUE TITLE
Garbage in population time profile under Linux

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#490]
Probably due to the fix of https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/429: under **Linux** some garbage symbols are inserted into the legend and into the plot of lines. Under **Windows** it does not happen!

E.g. compare the attached workflow. Under Linux it looks like this: 
[01_Windows_Output.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6630132/01_Windows_Output.zip) 
[02_Linux_Output.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/6630133/02_Linux_Output.zip)

![Filmcoated_tablet_400mg_sd-timeProfileLog-Concentration-total](https://user-images.githubusercontent.com/25061876/121501678-be264080-c9df-11eb-97b8-45ab196608c3.png)
<img width="500" src="https://user-images.githubusercontent.com/25061876/121501878-ec0b8500-c9df-11eb-8eff-75172bbc98c1.png">

And under Windows all good
![Filmcoated_tablet_400mg_sd-timeProfileLog-Concentration-total](https://user-images.githubusercontent.com/25061876/121501969-004f8200-c9e0-11eb-87df-40ceabe0af5e.png)

**Comment by pchelle** [comment]
@Yuri05 
The issue is the ggplot coding for shapes.
Unlike linetypes which uses actual names, shapes use an integer which might be encoded differently in Linux.
If there is someone with a linux environment, I could test other shape numbers that could work to map a "blank" shape.

**Comment by Yuri05** [comment]
@pchelle If you create a PR into the [v1.2Fixes](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/tree/v1.2_Fixes)-branch - I can test it under Linux.

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/145
