### ISSUE TITLE
Mapping of observed data with simulation results

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#498]
@abdullahhamadeh @pchelle could you point me to the place in code where simulation outputs are mapped to observed data and everything is passed to TLF to create the figures? I think we can create a generic structure for this and implement it in ospsuite-r.

**Comment by pchelle** [comment]
@PavelBal 
The mapping is done using `SimulationSet` and `Output` objects.
`SimulationSet` (from simulation-set.R) includes the knowledge of the simulation and observed data through the simulation file and observed data file.
`SimulationSet` also includes a list of `Output` objects. Each `Output` includes an output path which can be mapped to a selected part of the observed data.

In the function `plotMeanGoodnessOfFit` (from file utilities-goodness-of-fit.R) simulation results are read, formatted and sent to tlf functions to create all the goodness of fit plots for each `SimulationSet`.
