### ISSUE TITLE
User defined PK Parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#5]
In many Reporting Engine functions it is desired to have an option for providing **user defined** PK parameters.
How should the interface look like?

**Comment by KatrinCoboeken** [comment]
The current Matlab implementation uses a function for PK parameter calculation, which can be exchanged by a function handle.
The output of the function provides identifier like 'Cmax' which can the be used to refer to this parameter.

**Comment by sfrechen** [comment]
Are we talking about a GUI like interface?

**Comment by Yuri05** [comment]
>Are we talking about a GUI like interface?

No. About user defined functions for pk values.

**Comment by sfrechen** [comment]
Then I don't understand the exact question.

(Though I know what Katrin refers to (and also know how to use it).)

**Comment by Yuri05** [comment]
Closing in favor of #23
