### ISSUE TITLE
(More) tests fail when running under R4 (Linux)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#506]
Additionally to the failing tests specified in #505 some unit tests which succeed under R3 fail under R4.
S. the full log [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/504/checks?check_run_id=3030309587) or [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/504/checks?check_run_id=3030309616)

At the moment it's not urgent, however we should figure out what the problem is.

```
#15 1341.9 ══ Failed ══════════════════════════════════════════════════════════════════════
#15 1341.9 ── 1. Failure (test-configuration-plan.R:47:3): Sections field works appropriate
#15 1341.9 "test-configuration-plan/002_Chapter 2/003_Chapter 2_1" not equal to minimalPlan$getSectionPath(id = "3").
#15 1341.9 1/1 mismatches
#15 1341.9 x[1]: "test-configuration-plan/002_Chapter 2/003_Chapter 2_1"
#15 1341.9 y[1]: "test-configuration-plan/002_Chapter 2/003_Chapter 2_1/"
#15 1341.9 
#15 1341.9 ── 2. Failure (test-configuration-plan.R:51:3): Sections field works appropriate
#15 1341.9 "test-configuration-plan/002_Chapter 2/003_Chapter 2_1" not equal to minimalPlan$getSectionPath(id = 3).
#15 1341.9 1/1 mismatches
#15 1341.9 x[1]: "test-configuration-plan/002_Chapter 2/003_Chapter 2_1"
#15 1341.9 y[1]: "test-configuration-plan/002_Chapter 2/003_Chapter 2_1/"
#15 1341.9 
#15 1341.9 ── 3. Failure (test-output.R:12:3): Output requires a 'path' as a single charact
#15 1341.9 `Output$new(path = data.frame(testPath))` did not throw an error.
#15 1341.9 
#15 1341.9 ── 4. Failure (test-output.R:57:3): Output 'dataDisplayName' is checked and set 
#15 1341.9 `Output$new(path = testPath, dataDisplayName = data.frame(testDataDisplayName))` did not throw an error.
#15 1341.9 
#15 1341.9 ── 5. Failure (test-output.R:76:3): Output 'dataSelection' is checked and set pr
#15 1341.9 `Output$new(path = testPath, dataSelection = data.frame(testDataSelection))` did not throw an error.
#15 1341.9 
#15 1341.9 ── 6. Failure (test-output.R:118:3): 'PkParameterInfo' works properly ──────────
#15 1341.9 `PkParameterInfo$new(pkParameter = myTestCmaxName, displayName = data.frame(myTestCmaxDisplayName))` did not throw an error.
#15 1341.9 
#15 1341.9 ── 7. Failure (test-output.R:119:3): 'PkParameterInfo' works properly ──────────
#15 1341.9 `PkParameterInfo$new(pkParameter = myTestCmaxName, displayUnit = data.frame(myTestCmaxDisplayUnit))` did not throw an error.
#15 1341.9 
#15 1341.9 ── 8. Failure (test-output.R:136:3): Output 'pkParameters' are checked and set p
#15 1341.9 `Output$new(path = testPath, pkParameters = data.frame(myTestAUCName))` did not throw an error.
#15 1341.9 
#15 1341.9 ══ DONE ════════════════════════════════════════════════════════════════════════
```

**Comment by Yuri05** [comment]
Most of the tests fail because the RE function `isOfType `behaves differently under R3 and under R4!?
E.g. the code below returns FALSE under R3 and TRUE under R4.

```
isOfType <- function(object, type) {

  inheritType <- function(x) {
    inherits(x, type)
  }
  if (inheritType(object)) {
    return(TRUE)
  }

  object <- c(object)
  all(sapply(object, inheritType))
}

isOfType(data.frame("testPath"), "character")
```

That's why the tests like below pass under R3 but fail under R4:
```
testPath <- "Organism|PeripheralVenousBlood|Raltegravir|Plasma (Peripheral Venous Blood)"
expect_error(Output$new(path = data.frame(testPath)))
```

Not sure if it's enough just to disable those test for R4 or if there are further implications.

@PavelBal @msevestre FYI

**Comment by PavelBal** [comment]
What exactly are you trying to do here?

> `expect_error(Output$new(path = data.frame(testPath)))`

In R3, there is obviously a bug in determining the type of data.frame contents:

```
> typeof(data.frame("testPath")[[1]])
[1] "integer
```

The same code in R4 produces the expected result:

```
> typeof(data.frame("testPath")[[1]])
[1] "character"
```

**Comment by pchelle** [comment]
In the test, Output expects a "character" for path, and I wanted it throw an error if a class "data.frame" is provided instead.
Why do we get "integer" or "character" instead of "data.frame" ?

**Comment by PavelBal** [comment]
isOfType also checks if a list of objects is of certain type, e.g. isOfType (c("a", "b"), "character") should be true.

A data.frame is a list (a special one, but still). In case of a list, we iterate through all the objects within the list.

**Comment by pchelle** [comment]
Hmm... So, isOfType is actually not appropriate for validating such input parameters
Just out of curiosity, what is supposed to give back for a data.frame or a list with different classes within ?

**Comment by Yuri05** [comment]
should we just extend the isOfType function with e.g.
```
if (is.data.frame(object)) {
    return(FALSE)
  }
```
?

**Comment by PavelBal** [comment]
> So, isOfType is actually not appropriate for validating such input parameters

Why? If the data.frame (i.e., a list) contains something else than character entries, it will fail.

> Just out of curiosity, what is supposed to give back for a data.frame or a list with different classes within ?
FALSE

> should we just extend the isOfType function with e.g.

Strongly against! Why? E.g., a data.frame with multiple paths is a set of paths and this is a valid input.

**Comment by Yuri05** [comment]
if a single string as expected as input - why would I pass a dataframe? E.g. why would I do something like below?
`Output$new(path = data.frame('Organism|Liver|Plasma|C1')))`

**Comment by PavelBal** [comment]
This is a very good question - why would you do that? ;) Indeed a very strange case, but from the technical point I do not see a reason why this should fail. `Output$new(path = data.frame('Organism|Liver|Plasma|C1')))` is equal to `Output$new(path = list('Organism|Liver|Plasma|C1')))` and `isOftype` is just designed to return "TRUE" in this case. It does not check for the length.

If only single value is expected, this has to be checked separately by `length(object) == x`.

**Comment by Yuri05** [comment]
>isOftype is just designed to return "TRUE" in this case. It does not check for the length. 

The "whole" validation does
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/b495366b2d18c3c8253a5b6029a530eae168fdf1/R/output.R#L48-L56

**Comment by Yuri05** [comment]
I mean, we can just remove the tests like `expect_error(Output$new(path = data.frame(testPath)))`
If somebody will try this in R3 (passing a dataframe with a string inside) - in R3 it will crash anyway. In R4 - no idea, maybe it will work, maybe it will crash elsewhere.

**Comment by PavelBal** [comment]
Why don't you just replace 

`expect_error(Output$new(path = data.frame(testPath)))`

by something like 

`expect_error(Output$new(path = 2))`

? You will be checking exactly what you want to - that the input is of the correct type. Additionally, you should have a test for the length `(expect_error(Output$new(path = list(testPath, testPath)))`. Wrong type and wrong length are two different errors and should be tested separately.

**Comment by Yuri05** [comment]
How will e.g. the code below react if `output$path` is a dataframe (containing a single striong)?
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/b495366b2d18c3c8253a5b6029a530eae168fdf1/R/utilities-goodness-of-fit.R#L50

**Comment by PavelBal** [comment]
```
getQuantity(path = data.frame("Organism|Age"), sim)
Quantity: 
  Path: Organism|Age
  Value: 25.70 [year(s)]
  isConstant: TRUE
  Quantity Type: Parameter
```

**Comment by Yuri05** [comment]
ok, then I would suggest just to remove the tests expecting error in such cases.
Other tests (e.g. wrong length etc.) are already in place.
