### ISSUE TITLE
Dictionary of Qualification -> OSP PK parameter names

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#520]
In qualification configuration plans, PK parameters are specified as:

![image](https://user-images.githubusercontent.com/18409098/129032071-2fa67c36-7930-4d11-b206-1e7102c9ad38.png)

The corresponding PK parameter names in OSP are "AUC_tEnd" "C_max".  

Need a dictionary to map between the two sets of names for other PK parameters.

**Comment by msevestre** [comment]
We need to remove the | here too
Agreed @Yuri05 ?
