### ISSUE TITLE
Add third option to specify unit of dv of observed data via a field 'dataUnit' of the 'Output' object class

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#533]
Two options are currently available:

1. Specfiy `nonmemUnit` in the `dv` line of the dictionary. **This implies one unit for all outputs.**

2. Specify unit via a dedicated unit column in the dataset and add specific line `dv_unit` in dictionary,e.g.
![image](https://user-images.githubusercontent.com/26569320/133102176-47db80dc-9b96-4aad-84af-180509cf3fe1.png)
![image](https://user-images.githubusercontent.com/26569320/133102216-bee25372-5eba-408e-b775-c341a8b37957.png)
**Allows various units for outputs but requires unit column to be present in datasets.**

A **third** option to specify the unit of dv of the observed data for a particular output via a field 'dataUnit' of the 'Output' object class should be made available, e.g.:
```
Output$new(
  path = 'Organism|PeripheralVenousBlood|Raltegravir|Plasma (Peripheral Venous Blood)',
  displayName = 'Rifampicin Plasma Concentration',
  displayUnit = 'mg/l',
  dataSelection = DataSelectionKeys$ALL,
  dataDisplayName = 'Wiesinger et al. 2020',
  dataUnit = 'µg/l',
  pkParameters = 'PK Conc Single',
  residualScale = ResidualScales$Logarithmic
)
```
**This allows then also various units for outputs but does not require a unit column to be present in datasets. A unit column is often missing in datasets. And datasets whichhave been validated before should not be reopened for this purpose only in many settings, e.g. regulatory context in pharmaceutical industry etc.**

The Excel spreadsheet `WorkflowInput.xlsx` would need to be adjusted accordingly in the Outputs sheets:
![image](https://user-images.githubusercontent.com/26569320/133118560-1d3c0945-36a4-4daa-a8a9-b027609ce8d6.png)
Here, one might leave it empty to use option 1 or 2 (see above), or one might even introduce a fixed term here to put in like `readFromDictionaryOrDataset`...

@Christoph27 @AnnikaRPS @Yuri05

**Comment by Yuri05** [comment]
what should happen if the data unit is passed as an argument to the ouput and is available in the data dictionaryat the same time?

**Comment by sfrechen** [comment]
> what should happen if the data unit is passed as an argument to the output and is available in the data dictionary at the same time?

Throw error.
Or wee need to introduce a hierarchy and throw warnings...

**Comment by AnnikaRPS** [comment]
I can support this request - a third option would be appreciated, especially when dealing with multiple outputs.

**Comment by Yuri05** [comment]
ok, we will implement. However: **double dislike from me for this option**. 

If the proper units definition is missing in the data dictionary, then the data providers just did not do their job well and the data set is not fully described. I don't know where the person who sets up the workflow takes the knowledge about the data units in such a case - but this is very error prone.

**Comment by sfrechen** [comment]
> If the proper units definition is missing in the data dictionary, then the data providers just did not do their job well and the data set is not fully described. I don't know where the person who sets up a RE-workflow takes the knowledge about the data units in such a case - but this is very error prone.

Strongly disagree. Usually units are stored in files next to the dataset (so called data item specification lists). Thus,  the units are not part of the dataset itself. And in that case the current implementation using the dictionary only allows one dv unit (but multiple dv units is the usual case).
