### ISSUE TITLE
Demography plots should contain observed data for comparison

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#535]
See examples here from Matlab Reporting Engine 2.1:

## **Age**
![image](https://user-images.githubusercontent.com/26569320/133122945-0fdf021d-b63a-4281-869b-c157148e68d9.png)

## **Body weight**
![image](https://user-images.githubusercontent.com/26569320/133122984-ed95c2e6-0800-4681-992a-f90f5c1789dd.png)

## **Body height**
![image](https://user-images.githubusercontent.com/26569320/133123034-e4ecc010-d9c9-4652-8c75-dffb1de6e32c.png)

## **BMI**
![image](https://user-images.githubusercontent.com/26569320/133123065-895eb6e7-c0a5-4af1-8e60-2831f57986e1.png)

## **Gender**
![image](https://user-images.githubusercontent.com/26569320/133123101-ea428b05-20b2-4a71-bd95-3cc96cd78f6d.png)

@AnnikaRPS  @Christoph27 @Yuri05

**Comment by sfrechen** [comment]
Actually, this is high prio as this is expected from reports to regulatory agencies.

**Comment by Yuri05** [comment]
@sfrechen For the demography data selection from the data files: which data filter should be used?
At the moment, when creating a workflow from excel, we have 2 data filters:
* on the simulation set level
* on the output level

In a created workflow, data filter is defined per output and is the concatenation of the 2 data filters above.
For the demography data:
* should it be the "simulation set" filter?
* or a **new** "demography data" filter?

**Comment by sfrechen** [comment]
@Yuri05 
It should be the "simulation set" filter.

**Comment by pchelle** [comment]
From issue #17 , there are a few types of plots exported by the demography task.
@sfrechen could you confirm which ones need observed data (if not all) and how you wish it to be displayed.

- **Pediatric histograms**
   - [ ] observed **not** included
   - [ ] observed included within same plot
   - [ ] addition of a comparison histogram only between observed
- **Parallel/Ratio comparison histograms**: 
   - [ ] observed **not** included
   - [x] observed included
- **Range plots**
   - [ ] observed **not** included
   - [ ] observed included as scatter points
   - [ ] observed included as range plot

**Comment by pchelle** [comment]
Also I've noticed that the histograms display the number of virtual subjects (without ylabel) but not frequency within their respective population. I'll also fix this while adding the observed data.

**Comment by pchelle** [comment]
Last question regarding the *dodging* of the histogram bars.
The histograms look good for categorical variables such as Gender, but not so good when continuous variables are displayed along many populations

<details><summary>Example</summary>

![8_demography_Organism_BMI](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/45343665/504e9828-2577-4f53-9d9e-f8f997f96fcd)

</details>

Let me know if you wish an option that prevents the *dodging* and display the histograms on top of each other with transparency.

**Comment by sfrechen** [comment]
> Let me know if you wish an option that prevents the _dodging_ and display the histograms on top of each other with transparency.

Sounds reasonable to me!

**Comment by sfrechen** [comment]
My proposal:

> * **Pediatric histograms**
>   
>   * [ ]  observed **not** included
>   * [ ]  observed included within same plot
>   * [ x]  addition of a comparison histogram only between observed
> * **Parallel/Ratio comparison histograms**:
>   
>   * [ ]  observed **not** included
>   * [x]  observed included
> * **Range plots**
>   
>   * [ ]  observed **not** included
>   * [ ]  observed included as scatter points
>   * [ x]  observed included as range plot
