### ISSUE TITLE
Dependency between workflow tasks and model sets

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#56]
The Worklfow class needs to loop on both tasks and model sets, however we are not sure which should be the primary and secondary loop

The following example may help to us to decide which will be which: @Yuri05 , for every task (e.g. plot time profile, calculate sensitivity), is it performed on all the simulation sets or only on some of them ?

**Comment by Yuri05** [comment]
ALL

**Comment by sfrechen** [comment]
Primary: task
Secondary: model sets

**Comment by sfrechen** [comment]
a task should be executed for all models sets
