### ISSUE TITLE
PK Parameters timeOffset

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#578]
To enable this feature, `PkParameterInfo` objects would require an `id` field.
Ratio or pediatric comparison will use the `id` instead of `name` (because `ospsuite` defines `PKParameters` names globally), 
allowing the same `id` to get different PK Parameters for such a comparison.

Then, users can create their own PK Parameters that accounts for `timeOffset` with the function `ospsuite::addUserDefinedPKParameter()`

@Yuri05 @sfrechen 
Let me know if this would work for you

**Comment by pchelle** [comment]
`group` field should replace `id`

**Comment by TWendl** [comment]
For the moment, this would work for us!
