### ISSUE TITLE
Help needed setting up test workflows

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#58]
I'm trying to setup some test cases for reporting engine workflows.
 Can anybody give me an example how I can setup a MeanModelWorklow. Looking through tests,documentation and code does not lead me to a solution how to do this,

**Comment by msevestre** [comment]
This is probably to early here as we are not done with the MeanModelWorkflow. 
I'd suggest to wait /cc @Yuri05

**Comment by ThomasGaub** [comment]
Any I Idea when to start. Or with what. 
I'm not looking for a full solution just looking on how to setup everything. 
We need to start developing tests for the validation.

**Comment by msevestre** [comment]
@abdullahhamadeh @pchelle 
Can you please provide Thomas with the instruction on how to get started?
Best: Add a page in the WIKI and describe how to get started :)

**Comment by ThomasGaub** [comment]
Some Information I need
Interface to create a Workflow (In the moment MeanModelWorkflow has a different Interface in documetation, code and Test)
Inforamtion how Output will look like and saved for each task

**Comment by abdullahhamadeh** [comment]
I have added a wiki page with introductory examples to the mean model and population workflows.

**Comment by ThomasGaub** [comment]
Thanks.  Helpfull information!
Can you please give a rough sketch about how output files (simulation results) look like

**Comment by msevestre** [comment]
Simulation results are exported using the .net implementation. It should be the same format as when you export population results from pksim

**Comment by ThomasGaub** [comment]
Thank you
