### ISSUE TITLE
Wrong artifacts order in Report

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#596]
Based on https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md
The order should be:
1. Plot
2. GMFE
2. Measures
3. Table

Now we have e.g. the plot at the end

**Comment by pchelle** [comment]
In the current version, there is one plot/table per PK parameters for Plot and Measures artifacts but not for GMFE.
The artifact for GMFE is currently a table with 2 columns: PK Parameter and GMFE (which I think is clearer than the Matlab version).

Would it make sense to switch GMFE and Measures, then ?
Or would it make more sense to use one table for all parameters as Measures artifact with 2 columns per PK parameters ?
Unless you prefer to revert and write the GMFE per PK parameter ?
Just let me know

**Comment by Yuri05** [comment]
The representation of GMFE and measures is OK for me.
The main point is: the plot (as the "most interesting" result) should be displayed at the beginning, and the comparison table (which might become very long) at the end.
GMFE and measures in between - in which order, does not really matter.
