### ISSUE TITLE
Wrong PK-parameter units in PK-Ratio table

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#597]
Based on https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md
The units of AUC, etc. are currently not part of a qualification plan - thus they should be taken from the observed data.

In the [observed data set referenced in the quali plan](https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/v1.3/Pediatrics.csv) the AUC units are [mg*min/mL], and in the Matlab-report it was then: 
![grafik](https://user-images.githubusercontent.com/25061876/141528627-1aab7446-554f-4872-8557-ddd543698092.png)

Now:
![grafik](https://user-images.githubusercontent.com/25061876/141528701-5873f7dd-e3d0-473d-b460-1ff6ce2fd083.png)

**Comment by pchelle** [comment]
I see. 
In the observed dataset, the AUC are not all reported with the same unit.
Shall we 
- use the first observed unit as reference unit ?
- add a new column named e.g. `Unit AUC` ?
- paste the units directly within the cells ?

**Comment by Yuri05** [comment]
I would say either the first observed unit or the most frequently used unit.
@Incei Do you have an opinion on this topic?

**Comment by Incei** [comment]
As at the end it is about the ratio. I don't have a strong opinon, however we could define a standard unit to be applied irrespective of the reference unit for all reports. E.g. for AUC µg*h/L (for small molecule concentrations usually µg/L is used for reporting ). Same would be for Clearances (e.g. L/h)
@sfrechen @JanSchlender ?

**Comment by sfrechen** [comment]
Without having a preference:
Either/or:
1. define a standard unit to be applied (@Incei proposal) - (conversion done bei reporting engine)
2. add a new column named e.g. Unit (@pchelle second proposal)
