### ISSUE TITLE
PK Ratio plots: X axis setting are ignored

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#600]
Based on https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md

In the qualification plan:
![grafik](https://user-images.githubusercontent.com/25061876/141535041-21adcc2b-9e64-4fab-9b29-7706489d6051.png)

In the plot: X-Axis is lin, X-grid lines are plotted

**Comment by pchelle** [comment]
Actually, the log scale is taken into account but the breaks are not well spaced by default (issue similar to #603).
