### ISSUE TITLE
Log scaling ticks

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#603]
Based on https://github.com/pchelle/Test-of-Pediatric-Qualification-Workflow/blob/main/Report.md

In the new reports, the axis in the log scale shows not the usual log ticks 10^N:
![grafik](https://user-images.githubusercontent.com/25061876/141537989-febbf599-eadb-4b03-bf28-240345c7d2b0.png)

For comparison, the corresponding Matlab-Plot:
![grafik](https://user-images.githubusercontent.com/25061876/141537817-76e9291c-6712-43c9-9b1a-5aee00629b53.png)

**Comment by pchelle** [comment]
`{ggplot2}` does not use a math format by default.
I noticed that the package `{scales}` (included in validR) with its function `math_format` is a really good solution for that.
https://scales.r-lib.org/

**Comment by pchelle** [comment]
Fixed by PR #[201](https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/201)
