### ISSUE TITLE
Missing picture (GMFE formula)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#618]
Based on https://github.com/pchelle/Test-of-Qualification-DDI-UGT/blob/main/report.md#3-concentration-time-profiles
![grafik](https://user-images.githubusercontent.com/25061876/142611727-4c37eec9-9f4e-42f8-8cf6-12fdb606348a.png)

**Comment by pchelle** [comment]
The images are available in the folder Input/Content/images, but I did not find them in re_input. 
So they are currently accessible for the Qualification Runner but not the RE.
Should we make the Qualification Runner copy them in re_input and the RE takes care of copying the images ?
Or should we add a line in the template qualification workflow script to copy them in the re_output folder ?

**Comment by Yuri05** [comment]
The qualification runner should copy. Which worked in the past - not sure why not anymore. 
@msevestre Any ideas?

**Comment by msevestre** [comment]
> Which worked in the past

are you sure?

**Comment by Yuri05** [comment]
>are you sure?

Well, in the reports created with the Matlab-RE images were displayed correctly.
So either the Matlab-RE copied the images or something changed in the qualification runner.
https://github.com/Open-Systems-Pharmacology/OSP-Qualification-Reports/blob/master/DDI_Qualification_UGT/report.md#3-concentration-time-profiles

![grafik](https://user-images.githubusercontent.com/25061876/142886767-68c253cd-bd0e-4a51-87d0-055b43df0448.png)

**Comment by msevestre** [comment]
@Yuri05 Where is the qualification file? I only see the report here

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Qualification-DDI-UGT/tree/master/Qualification/Input

**Comment by msevestre** [comment]
Nope I don't see it in the code.
We only copy the `content` file. The json report config does not know anything about the "report" folder. Probably it was referenced as internet link in the markdown file. Using it worked before and does not work now in R

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/Qualification-DDI-UGT/blob/v1.1/Qualification/Workflow.m#L83

**Comment by Yuri05** [comment]
Ok, I see. Then indeed, RE should check if `re_input/Content` containes the `images `subfolder and if yes: copy all pictures from to `report/images`
