### ISSUE TITLE
Include option for dose-normalized AUC ratio in DDI Qualification Plan

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#62]
In the Qualification Plan I'd like to include the ratio of dose-normalized AUC in the DDI ratio plots, e.g.:

![Annotation 2020-02-27 085013](https://user-images.githubusercontent.com/26541603/75423036-362d3c00-593e-11ea-84ae-e162fb75d0f2.png)

Ideally, the AUCnorm ratios would be plotted together with AUC ratios in the same plot with e.g. different symbols, so it should be possible to control more specifically at the simulation-level for that option.
Do you have other suggestions/opinions?
@sfrechen @TWendl

**Comment by Yuri05** [comment]
@AndreDlm @sfrechen @TWendl 
with the upcoming R-RE release 2.0 it will be possible to define an **array** of PK parameters, where all standard PK parameters are supported (enter in R `ospsuite::allPKParameterNames()` to see the full list; we also kept "AUC" and "CMAX" as aliases in this list)
![grafik](https://user-images.githubusercontent.com/25061876/149181327-a9e087bb-a515-44df-9876-858c5df4824b.png)

Questions: 
1. Should we allow in this new PK paramater list ALL pk parameters or should we restrict it to {AUC, CMAX, AUC_norm, CMAX_norm, ...(what else?)}
2. How should new pk parameters (AUC_norm etc.) be mapped to the columns of observed data? 
At the moment this mapping is done internally in the reporting engine: AUC Ratio=>AUCR Avg, CMAX Ratio ==> "CmaxR Avg":
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/76332ba6179b8c2ee7553c751661adb727d8f342/R/qualification-outputs.R#L262-L267
Do we want to add new columns with fixed names to the DDI data sheet or do we want to calculate AUC_norm_observed/Cmax_norm_observed from AUC_observed/CMAX_observed on the fly using the dose and the body weight of the simulation?

**Comment by sfrechen** [comment]
> 1. Should we allow in this new PK paramater list ALL pk parameters or should we restrict it to {AUC, CMAX, AUC_norm, CMAX_norm, ...(what else?)}

I see a value in having ALL PK parameters available there.

> 2\. How should new pk parameters (AUC_norm etc.) be mapped to the columns of observed data?
>     At the moment this mapping is done internally in the reporting engine: AUC Ratio=>AUCR Avg, CMAX Ratio ==> "CmaxR Avg":

We should discuss this in the context of INSPIRATION with development of a new database.

**Comment by sfrechen** [comment]
> In the Qualification Plan I'd like to include the ratio of dose-normalized AUC in the DDI ratio plots, e.g.:

Why do you need it now? In the database we have a corresponding factor.

**Comment by Yuri05** [comment]
Closing in favor of #655 (the observed data mapping issue remains open; so even with the implementation of #655 it will still not be possible to plot AUC_Norm ratio with the RE 2.0
