### ISSUE TITLE
Curve not dispalyed

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#623]
[Bug.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/7589494/Bug.zip)
When executing attached qualification plan with the Matlab-RE: 1 curve is missing in the time profile plot (created via `AllPlots`).

In PK-Sim:
![grafik](https://user-images.githubusercontent.com/25061876/143062047-8c990f7a-9db9-45a0-bbc9-e50d68575d7a.png)

In the created report:
![001_plotTimeProfile](https://user-images.githubusercontent.com/25061876/143062092-99dc7205-af61-42bc-8f1f-cdd7a7182fb6.png)
The legend contains both curves, however the first one (`...Blood42-Concentration`) is missing in the plot.

@pchelle @abdullahhamadeh Can you check if the report created with the R-RE produces correct result?

**Comment by Yuri05** [comment]
@Christoph27 FYI

**Comment by abdullahhamadeh** [comment]
@Yuri05 is there a pkml simulation?

**Comment by pchelle** [comment]
I have re-run the `evaluation_plan_bug.json` using the Qualification runner to get the pkml and then the R reporting engine.

**Comment by pchelle** [comment]
I still need to implement the default linetype in `{tlf}` but the curve is here

**Comment by msevestre** [comment]
Why is it a  dash-style line?

**Comment by pchelle** [comment]
It it because the line style is not specified in the configuration plan.
So the `{tlf}` uses the default values which is different line style per new curve.
To fix that, I am hesitating between creating a "reporting engine" theme for `{tlf}` and setting within the qualification a default line styles, colors, sizes (first option is preferable in my opinion).

**Comment by pchelle** [comment]
This issue was already flagged twice: #604 and #620

**Comment by msevestre** [comment]
@pchelle I don't get it. LineStyle should be exported in all plots no? It's coming from PKSim

```
 public class CurveOptions
   {
      public AxisTypes? yAxisType;
      public bool? Visible { get; set; }
      public bool? ShouldShowLLOQ { get; set; }
      public bool? VisibleInLegend { get; set; }
      public InterpolationModes? InterpolationMode { get; set; }
      public Color? Color { get; set; }
      public int? LegendIndex { get; set; }
      public LineStyles? LineStyle { get; set; }
      public Symbols? Symbol { get; set; }
   }
```

The CurveOptions as  a LineStyle

**Comment by msevestre** [comment]
Maybe it's because we do not export if it;s the same as default 
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Core/Snapshots/Mappers/CurveOptionsMapper.cs#L26

So either we always export this, or the reporting engine needs to have the same default as what we create which is

```
      this._interpolationMode = InterpolationModes.xLinear;
      this._yAxisType = AxisTypes.Y;
      this._visible = true;
      this._color = Color.Black;
      this._lineStyle = LineStyles.Solid;
      this._symbol = Symbols.None;
      this._lineThickness = 2;
      this._shouldShowLLOQ = true;
      this._visibleInLegend = true;
```

**Comment by pchelle** [comment]
I think it is indeed not exported if equal to default (because I encountered the same dilemma for color and symbol).
I was planning of creating a `{tlf}` theme to provide all these default values but both ways work for me.

**Comment by msevestre** [comment]
tlf themes is ok as long as this configured automatically and the user does not have to do anything by hand :)

**Comment by Yuri05** [comment]
ok, at least we get 2 curves with the new RE - it's definitely an improvement :)
