### ISSUE TITLE
is it necessary to include user computer name and login in workflow printing method?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#639]
I am not sure in what context these workflows are run, so hard for me to judge how important inclusion of these details is in the printing method.

For example, see here:
https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/pk-parameters.html#11-pk-parameters-for-a

![image](https://user-images.githubusercontent.com/11330453/144453159-839566bd-8100-4618-85e0-1a51e8beb973.png)

**Comment by Yuri05** [comment]
yes, it's necessary , e.g. when executing workflows in validated environments.
