### ISSUE TITLE
PK parameters for PK Ratio and DDI Ratio

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#655]
Field `PKParameter` should be deprecated and replaced by `PKParameters` that would allow arrays of PK parameters.
This field could also include any name available in `ospsuite::allPKParameterNames()` as is besides the ones available in dictionary

**Comment by pchelle** [comment]
What nomenclature would be used in observed data in parameters outside the dictionary  (that only includes `AUC`, `CMAX` and `CL` so far) ?

**Comment by Yuri05** [comment]
[examples.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/7840572/examples.zip)
Examples attached. 
* **Qualification-Ontogeny-UGT1A1** with PK-Ratio plots
![grafik](https://user-images.githubusercontent.com/25061876/148808470-fbfa28d2-0310-482b-9132-3518d31b5e75.png)
* **qualification_plan.json** with DDI ratio plots
![grafik](https://user-images.githubusercontent.com/25061876/148808643-9b78e8b9-6ba6-4da7-81f3-4157a41d0762.png)

@abdullahhamadeh The DDI example has also subunits

**Comment by abdullahhamadeh** [comment]
@Yuri05 

I am getting this error for the DDI example: 
![image](https://user-images.githubusercontent.com/18409098/149080924-d91f618a-2183-429f-8a29-668d48e0089f.png)

Can you reproduce?

**Comment by Yuri05** [comment]
ah, sorry, you need to copy the **Content** folder from https://github.com/Open-Systems-Pharmacology/Qualification-DDI-UGT/tree/master/Qualification/Input 

and for the PK-Ratio plot example the **Content** folder from https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_UGT1A1_Ontogeny/tree/master/Input is required

**Comment by Yuri05** [comment]
fixed
