### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#659]
with the development of qualification workflows code coverage decreased to 49%.

**Comment by pchelle** [comment]
I went through the codecov report and could group the coverage gaps into 3 topics that will need to be tested:
- Qualification workflows (with at least 10 files with low or null coverage)
- Sensitivity analyses (at least 4-5 files with coverage lower than 30%)
- Excel template (2 files without coverage)
