### ISSUE TITLE
RE documentation site

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#675]
@IndrajeetPatil 
Should we use the same github action as in `{tlf}` for automating the updates of documentation site built from `pkgdown` ?

**Comment by IndrajeetPatil** [comment]
I have no idea how to write github actions for codebase that relies on `.NET` code, sorry.

I tried to make this work for a long time, but to no avail.

**Comment by IndrajeetPatil** [comment]
E.g. https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/676
