### ISSUE TITLE
rename MeanModelSet to SimulationSet?

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#68]
@pchelle?  More generic name

**Comment by pchelle** [comment]
Do you mean the R6 class ? 
It was originally to split with population sets, if they are quite similar, we can use a common SimulationSet class for both

**Comment by msevestre** [comment]
I think this has been done correct?
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/tests/dev/test-sa-path-error.R#L31

or do you mean something else @abdullahhamadeh

**Comment by abdullahhamadeh** [comment]
I was suggesting to rename the class MeanModelSet to SimulationSet, but wasn't a priority

**Comment by msevestre** [comment]
I agree this should be removed. The class has nothing to do with the MeanModel
Please do

**Comment by abdullahhamadeh** [comment]
I was actually thinking of making SimulationSet a parent class and MeanModelSet and PopModelSet derived classes because a population set takes a population file whereas a mean model set doesn't.  Should we?

**Comment by abdullahhamadeh** [comment]
Right now MeanModelSet is the parent of PopModelSet, but the latter takes a population as a mandatory input

**Comment by msevestre** [comment]
There is no population in the MeanModelSet (or soon to be SimulationSet)
What would be the difference between a MeanModelSet and SimulationSet

What you could have is SimulationSet as base class and PopulationSimulationSet (No reason to call it PopModelSet)

**Comment by msevestre** [comment]
>Right now MeanModelSet is the parent of PopModelSet, but the latter takes a population as a mandatory input

That makes sense no? (provided that we rename MeanModelSet)

**Comment by abdullahhamadeh** [comment]
MeanModelSet would be == SimulationSet

**Comment by msevestre** [comment]
yep that makes sense

>I was actually thinking of making SimulationSet a parent class and MeanModelSet and PopModelSet derived classes 

not as much as I do not see the difference between SimulationSet and MeanModelSet (yet)

**Comment by abdullahhamadeh** [comment]
Just the naming, just to make it explicit where the two simulation set types would fall within the mean model/population model dichotomy.  Anyway I've made the change.  MeanModelSet is now SimulationSet. Will make a PR.

**Comment by msevestre** [comment]
sounds good. If you expect the class to differ at some point, or if you think that it will makes undertanding better, you can create another class. I don't have enough understanding of the whole process at that stage

**Comment by msevestre** [comment]
The file name has not been changed.

**Comment by msevestre** [comment]
the same goes for population-model-set
