### ISSUE TITLE
qualification workflow: overwriting report.md

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#681]
when I create quali report with the input from https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/678: I always get the warning` ...report.md' already exists. Overwriting`
However the report did not exist before the run (and not even the output folder existed)

```
Executing: pandoc --self-contained --wrap=none --toc --reference-doc="C:/Users/ztsoj/OneDrive - Bayer/Personal Data/R/win-library/3.6/ospsuite.reportingengine/extdata/reference.docx" --lua-filter="C:/Users/ztsoj/OneDrive - Bayer/Personal Data/R/win-library/3.6/ospsuite.reportingengine/extdata/pagebreak.lua" --resource-path="C:/SW-Dev/00/Vancomycin-Model/evaluation/re_output" -t docx -o "C:/SW-Dev/00/Vancomycin-Model/evaluation/re_output/report-word.docx" "C:/SW-Dev/00/Vancomycin-Model/evaluation/re_output/report-word.md"
[1] "27/01/2022 - 14:33:59 : 'C:/Vancomycin/evaluation/re_output/report.md' already exists. Overwriting 'C:/Vancomycin/evaluation/re_output/report.md'."
[1] "Qualification Workflow Total Duration: 1.5 minutes"
```

**Comment by pchelle** [comment]
During the qualification, the intermediate markdown report has the same name as the final report.
Consequently, the function `mergeMarkdowndFiles` - that builds the final report - flags that the file already exists.
I think this checking should only be indicated in the log-debug without any warning.
