### ISSUE TITLE
Qualification workflow / Word report: missing images

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#682]
when I create quali report with the input from https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/678: 
some images are not inserted into the word report (in the md-report they are properly displayed) - some pages in word are just empty.
[report.docx](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/7950850/report.docx)
Maybe it has something to do with https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/681

**Comment by pchelle** [comment]
Need to fix special characters in the file paths created by the qualification workflow
