### ISSUE TITLE
Is the qualificationRunner started with the option  --norun?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#689]
OTherwise all simulations will be calculated...

**Comment by pchelle** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/f6218d3318c18c83abea24b1a27e70d8397a9f4f/R/utilities-qualification.R#L382

**Comment by msevestre** [comment]
asweome
