### ISSUE TITLE
Investigate build issue on Linux (all failing at the moment)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#690]

**Comment by pchelle** [comment]
At long last:
![image](https://user-images.githubusercontent.com/45343665/152502010-3257e7e4-fda3-40d7-9e7b-17c58d43d985.png)

**Comment by pchelle** [comment]
However, this is strange because the lines before I applied the same algorithm that was set and I get the same percentiles between Linux and Windows

**Comment by pchelle** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/f6218d3318c18c83abea24b1a27e70d8397a9f4f/R/utilities-sensitivity-analysis.R#L332

**Comment by pchelle** [comment]
The median Cmax is `(Cmax of Individual 10 + Cmax of Individual 49)/2` which makes individuals 10 and 49 equally close of median Cmax. The function `which.min` is supposed to get the first index found if multiple values are equally close.
So either, the rounding is different which makes individual 10 closer in Linux or they are not ordered the same way in Linux.
