### ISSUE TITLE
package name/version

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#70]
Currently package created is `ospsuite.reportingengine_0.1.0.XXX` (e.g. `ospsuite.reportingengine_0.1.0.zip`) and the build number is not included at all.
Let's rename it to `ospsuite.reportingengine_1.0.<buildNumber>.XXX`

**Comment by msevestre** [comment]
I need to implement the same hack has for OSPSuite
