### ISSUE TITLE
simple way to change all plots (line & dot-sizes)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#701]
Dear all,

Is there a simple way to change all plots (line & dot-sizes)? I would like all plotted datapoint to have a large size. I hope that there is a quick way of doing it , since the TLF (ThemeMaker) is not working currently..?

Cheers

**Comment by pchelle** [comment]
The simplest way is to copy and update directly a json file that includes a template theme.
```r
file.copy(system.file("themes", "template-theme.json", package = "tlf"), "working/directory")
```
If you have the latest version of the `tlf` package, this [link](https://www.open-systems-pharmacology.org/TLF-Library/articles/plot-configuration.html#default-plot-configuration-theme-objects) provides the list of available templates.

Then, the updated theme can be included as input when initializing a Workflow:
```r
updatedTheme <- loadThemeFromJson("updated-theme.json")

workflow <- MeanModelWorkflow$new(
simulationSets = listOfSimulationSets , 
workflowFolder = "working/directory", 
theme = updatedTheme
)
```

**Comment by pchelle** [comment]
Within the json file, there is a field named `"plotConfigurations"` in which each property of atom and molecule plots are defined (e.g. below `"first"` means that the first value in `"aestheticMaps$size"` will be used). 
You can replace the fields `"size"` by whatever size you want (e.g. `"size": 2` the unit is `ggplot2` unit which should pts) and sizes can be different between lines and dots.
```json
"plotConfigurations": {
    "addScatter": {
      "color": "next",
      "fill": "NA",
      "shape": "next",
      "linetype": "blank",
      "size": "first",
      "alpha": 1
    },
    "addLine": {
      "color": "next",
      "fill": "NA",
      "shape": "blank",
      "linetype": "same",
      "size": "first",
      "alpha": 1
    },
    "addRibbon": {
      "color": "next",
      "fill": "next",
      "shape": "blank",
      "linetype": "same",
      "size": "first",
      "alpha": "first"
    },
    "addErrorbar": {
      "color": "next",
      "fill": "NA",
      "shape": "blank",
      "linetype": "first",
      "size": "first",
      "alpha": 1
    },
    "plotPKRatio": {
      "points": {
        "color": "reset",
        "fill": "NA",
        "shape": "reset",
        "linetype": "blank",
        "size": 4,
        "alpha": 1
      },
      "lines": {
        "color": [
          "#000000",
          "#0078D7",
          "#D83B01"
        ],
        "fill": "NA",
        "shape": "blank",
        "linetype": "longdash",
        "size": 1,
        "alpha": 1
      },
      "errorbars": {
        "color": "reset",
        "fill": "NA",
        "shape": "blank",
        "linetype": "solid",
        "size": 1,
        "alpha": 1
      }
    },
...
  }
```

**Comment by Yuri05** [comment]
@Incei Can we close the issue?

**Comment by Incei** [comment]
@Yuri05 Yes we can, Thanks.
