### ISSUE TITLE
Incorporate new PKParameter logic

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#71]
and review the need for an enum for predefined parameters. This may not be required/desired
see discussion in #69

**Comment by msevestre** [comment]
FYI @abdullahhamadeh . Core is not ready yet so no need to start working on that until I give you the thumbs up

**Comment by msevestre** [comment]
@abdullahhamadeh In fact, I am not sure a static list is a good idea here as the list is read dynamically from a file which somewhat defeat the purpose 

I can return the list of all avaliable parameters in a array.  How would we create a enum for this (very similar to what you did with the tree structure for sim)?

Say we have a method in core

pkParmas <- getAllStandardPKParameterNames()

How to move from there and create a list that can be used?

**Comment by abdullahhamadeh** [comment]
I need more info.  Is this just a straightforward array of unrelated strings?  The paths one had a tree structure that had to be maintained.  If it is a simple array then I think @pchelle wrote an exported function called enum() for reporting engine. Is this what you need?

**Comment by msevestre** [comment]
Enum is something we have as well for core. But this is created based on a static list. Here we have a dynamic list (but flat indeed)

Anyways, let me update the code and once I have it ready, we can look at what you have. I am still not convinced that we need this enum at all

**Comment by msevestre** [comment]
see here on how to update pk parameters and defined user defined pk parmaeters
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/dev/script-sensitivity-analysis.R#L6

**Comment by msevestre** [comment]
The enum is gone. User can defined own pk parameters  and some pk parameter do not make sense depending on context (single vs multiple). Therefor enum probably not needed or could be constructed on the fly fro the list of pkParameters
