### ISSUE TITLE
Qualification reports: Time profile legend looks "bad"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#743]
E.g. 
![grafik](https://user-images.githubusercontent.com/25061876/160642625-4e7f78ac-cf1f-4fc7-9f7e-caa26b6248b7.png)

Compare output of the Matlab-RE for the same plot:
https://raw.githubusercontent.com/Open-Systems-Pharmacology/OSP-Qualification-Reports/master/DDI_Qualification_CYP3A4/images/003_3_Concentration-Time_Profiles/025_3_12_Fluconazole_-_Alfentanil_DDI/001_plotComparisonTimeProfile.png

* Question 1: The legend uses not the whole width of the plot area. Why? Even with this big legend font size we would avoid line breaks if it would be the case.
* Question 2: Was the font size from the report configuration plan used? Again looking on the Matlab plot: legend size is significantly smaller than the axes captions size; in the R plot the difference between those 2 sizes seems to be smaller
* Question 3: is it actually possible to display the legend entries without that "background"?
![grafik](https://user-images.githubusercontent.com/25061876/160645603-0685ae03-9f81-4e2b-85fb-e16b56800f2a.png)

**Comment by pchelle** [comment]
>     * Question 1: The legend uses not the whole width of the plot area. Why? Even with this big legend font size we would avoid line breaks if it would be the case.

Line breaks in the legend are driven by the default parameter `reEnv$maxWidthPerLegendCaption`
Its current value is fixed to 50 characters, thus neither accounting for font size nor plot width.
There is definitely room for improvement here by defining this parameter as a function of font size and plot width.

**Comment by pchelle** [comment]
> Question 2: Was the font size from the report configuration plan used? Again looking on the Matlab plot: legend size is significantly smaller than the axes captions size; in the R plot the difference between those 2 sizes seems to be smaller

It is supposed to account for legend size from configuration plan.
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/06c9154203a447b0308f2964422d56ff958a4ab9/R/utilities-plots.R#L107
I need to check if that `{tlf}` also handles this info appropriately

**Comment by Yuri05** [comment]
>Line breaks in the legend are driven by the default parameter reEnv$maxWidthPerLegendCaption

Did not know we have this in the **reEnv**. Anyway this parameter makes sense only if the legend is **on the left/on the right** of the plot area (like in sensitivity plots of MeanModel/Pop-workflows). If the legend is **above/below** the plot area (like here) - don't see any reason why we should not use the whole width of the plot.

**Comment by Yuri05** [comment]
>If you mean the grey background behind the legend symbols

Yes :)

>I can either make it a separate parameter in the PlotConfiguration objects or I can use the same color as the legend background all the time.

Yep, same color as the legend background - no need for a parameter

**Comment by pchelle** [comment]
> > Line breaks in the legend are driven by the default parameter reEnv$maxWidthPerLegendCaption
> 
> Did not know we have this in the **reEnv**. Anyway this parameter makes sense only if the legend is **on the left/on the right** of the plot area (like in sensitivity plots of MeanModel/Pop-workflows). If the legend is **above/below** the plot area (like here) - don't see any reason why we should not use the whole width of the plot.

The initial issue, #602 , had a legend above the plot but it was still not fully displayed and needed line breaks.
In my opinion, legend position can be an additional parameter of such a function that guesses when to use line breaks.

**Comment by pchelle** [comment]
@Yuri05 
Following up on `maxWidthPerLegendCaption`
After testing the correlation between legend font size and plot width (in inches), 
the max width should be `round(120*width/font size)` for a legend above/below or within plot.

If the legend is left/right, we can set the max width to a third of that value

**Comment by Yuri05** [comment]
mm.. ok 🙂
