### ISSUE TITLE
Word report: line spacing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#746]
Maybe increase to 1.5 lines (single line currently):

![image](https://user-images.githubusercontent.com/25903040/161031998-6852d77e-9dd4-4443-af66-8ee1681b1641.png)

vs 

![image](https://user-images.githubusercontent.com/25903040/161032021-0af706c4-9e52-43eb-ac04-eba1636cd871.png)

**Comment by Yuri05** [comment]
not sure if it's possible. But ok, needs to be checked

**Comment by Yuri05** [comment]
s. https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/748#issuecomment-1084426873
