### ISSUE TITLE
Word report: inconsistent fonts

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#749]
Arial and Cambria:

![image](https://user-images.githubusercontent.com/25903040/161032373-cb638a12-7806-4b5a-8132-1a3d83ab3a7c.png)

**Comment by Yuri05** [comment]
s. https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/748#issuecomment-1084426873

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/965
