### ISSUE TITLE
masked enum

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#75]
when loading reportin engine after tlf: 
![grafik](https://user-images.githubusercontent.com/25061876/76711995-f2e01500-6714-11ea-928e-2660d8a0d2a5.png)

**Comment by abdullahhamadeh** [comment]
I suspect we can resolve this one if we just export enum from ospsuite and remove it from both tlf and reportingengine (the tlf and reportingengine enum functions are identical, I'm assuming the ospsuite one does the same job).

**Comment by msevestre** [comment]
I don't think they should be exported anyways. At least not in the tlf

**Comment by msevestre** [comment]
I am not exporting enum anymore in the TLF. 
As soon as the latest tlf is used, this issue can be closed

**Comment by msevestre** [comment]
this is done
