### ISSUE TITLE
Word report: use borders in tables

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#750]
![image](https://user-images.githubusercontent.com/25903040/161032453-f3c3370a-dfcf-4aab-ad22-fb2a81790ca8.png)

vs

![image](https://user-images.githubusercontent.com/25903040/161032470-25ad7742-91ed-4bb7-98a3-5834b03f88b5.png)

**Comment by Yuri05** [comment]
s. https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/748#issuecomment-1084426873

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/965
