### ISSUE TITLE
Report: add plot type to the captions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#751]
•	Figure captions – add type of the plot (e.g. Observed-vs-Predicted AUC Ratio – Guest):

![image](https://user-images.githubusercontent.com/25903040/161032589-6346bedf-da01-4ce8-ba65-44c022bb2b80.png)

**Comment by Yuri05** [comment]
" – Guest" is not required in my opinion. Apart from that: agree.
So I would change it to: `<Title from report configuration plan>: <PK Parameter> Ratio - <Plot type>`
E.g. `CYP3A4 DDI: AUC Ratio - Predicted vs. Observed`

**Comment by sfrechen** [comment]
ok. But remember: we have the "subunits". So these plots would have identical caption? Should be different for each plot...

**Comment by Yuri05** [comment]
> So these plots would have identical caption?

No, for the subunits it would contain the corresponding "subunit description"

At the moment it is e.g.
![grafik](https://user-images.githubusercontent.com/25061876/161048804-4b566302-cc58-49ca-869b-878c798e6d39.png)

And with the proposed adjustment it would become
Figure 6: `CYP3A4-DDI-Reversible Inhibition: AUC Ratio - Predicted vs. Observed`

@abdullahhamadeh Btw, why do we have an underscore in the "Reversible_Inhibition" in that caption? Should be removed

**Comment by sfrechen** [comment]
Parfait

**Comment by abdullahhamadeh** [comment]
To identify the subplot type in the caption without needing to scroll up to find what subsection it is, I would propose this caption: 
![image](https://user-images.githubusercontent.com/18409098/161313516-5f10b044-9227-4c09-af5e-79de4c60ea81.png)

The previous suggestion would display 'Cimetidine' without clarifying whether it is perpetrator or victim.  Word report (for DDI plots only) attached.

[Report-ddi-only.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/8399837/Report-ddi-only.zip)

**Comment by Yuri05** [comment]
looks good!
@sfrechen FYI

**Comment by Yuri05** [comment]
Actually "Residuals vs. Observed" is wrong. We plot not the residuals ("Predicted - Observed") but **Predicted/Observed**  - so should we formulate the figure caption accordingly?
E.g. `CYP3A4 DDI. Perpetrator: Cimetidine. Predicted/Observed vs. Observed CMAX Ratio`
@sfrechen

**Comment by abdullahhamadeh** [comment]
Fixed:

[Report-ddi-only.docx](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/8401280/Report-ddi-only.docx)
