### ISSUE TITLE
Report: add blank lines between tables

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#752]
Before and after each table, add blank lines:

![image](https://user-images.githubusercontent.com/25903040/161032689-8d46f089-291c-4248-98cf-e3f7ac648c06.png)

vs

![image](https://user-images.githubusercontent.com/25903040/161032717-6b38b2db-d76a-4583-829f-cb19ae8fa577.png)

**Comment by Yuri05** [comment]
@PavelBal Does it apply to Word only or to the MD-Report as well?

**Comment by Yuri05** [comment]
ok, let's remove "Word report" from the issue title then.
