### ISSUE TITLE
Word report: references section should not be bold

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#754]
Maybe only the first author name in bold. Currently, everything is bold

![image](https://user-images.githubusercontent.com/25903040/161033065-77cd80f4-e3d5-469f-8664-889f07772721.png)

**Comment by Yuri05** [comment]
s. https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/748#issuecomment-1084426873

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/965
