### ISSUE TITLE
Table in Word report are messed up

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#761]
This is the markdown table

**Table 1. Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>**
| **Creatinine Clearance (mL/min/1.73 m<sup>2</sup>)**    | **Men HCT (%)**  | **Women HCT (%)** |
|---------------------------------------------------------|------------------|-------------------|
| Healthy                                                 | 45.5             | 40                |
| 60<CrCl=70                                              | 45.2             | 39.9              |
| 50<CrCl=60                                              | 44.8             | 39.6              |
| 40<CrCl=50                                              | 43.3             | 39.7              |
| 30<CrCl=40                                              | 42.6             | 38.4              |
| 20<CrCl=30                                              | 41.7             | 37.4              |
| CrCl=20                                                 | 34.3             | 33.5              |
| Hemodialysis                                            | 31               | 29                |

**Table 2. Fraction of Healthy Values (Normal Coefficient of Variation % ) in Chronic Kidney Disease Patients by Stage**
|Parameter                     |    Stage 3 (30-60 mL/min/1.73 m<sup>2</sup>)   |    Stage 4 (15-30 mL/min/1.73 m<sup>2</sup>)  |    Stage 5 (<15 mL/min/1.73 m<sup>2</sup>)   |   Dialysis   |
| :--------------------------- | :-------------------: | :---------------------: | :--------------------------: | :-------------------------: |
|Fraction unbound in plasma    |   1.07<sup>12</sup>   |    1.16<sup>12</sup>    |       1.55<sup>12</sup>      |      1.55<sup>12</sup>     |
|Gastric emptying time         |          1.0          |  1.6 (25%)<sup>14</sup> |   1.6 (25%)<sup>13,14</sup>  |  1.6 (30%)<sup>15-18</sup> |
|Small intestinal transit time |          1.0          |  1.4 (25%)<sup>14</sup> |    1.4 (25%)<sup>14</sup>    |   1.8 (30%)<sup>19</sup>   |
|Colonic transit time          |          1.0          |           1.0           |             1.0              |   1.8 (50%)<sup>20</sup>   |

This is how it looks like in word

![image](https://user-images.githubusercontent.com/1041237/161391835-46e18c45-d73e-4f99-b505-7663bddde0fa.png)

and 

![image](https://user-images.githubusercontent.com/1041237/161391843-cd13e203-9f44-4d5e-b559-3cb988a1a06e.png)

**Comment by msevestre** [comment]
@Yuri05 @pchelle @abdullahhamadeh is this a know issue?

**Comment by Yuri05** [comment]
It seems that in some (not in all) tables a blank line is missing in **report-word.md**.

E.g. this table from report-word.md is not properly created in word:
```
**Table 1. Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>**
| **Creatinine Clearance (mL/min/1.73 m<sup>2</sup>)**    | **Men HCT (%)**  | **Women HCT (%)** |
|---------------------------------------------------------|------------------|-------------------|
| Healthy                                                 | 45.5             | 40                |
| 60<CrCl=70                                              | 45.2             | 39.9              |
...
```

And this table from **report-word.md** looks good:
```
**Table 1. Physicochemical properties and ADME of gabapentin for oral model construction**

| **Physicochemical properties**    |                             |
|--|--|
| Octanol:water coefficient (logP)  | -0.08 Log Units             |
| Fraction unbound in plasma (f<sub>u</sub>) | 0.97<sup>24</sup>                        |
...

![grafik](https://user-images.githubusercontent.com/25061876/161392142-af2f015b-a280-4b19-8701-ffbd1636262d.png)

```

**Comment by msevestre** [comment]
is this because of the empty space between title and table maybe?

**Table 1. Hematocrit in Patients With Chronic Kidney Disease<sup>9, 10, 11</sup>**
| **Creatinine Clearance (mL/min/1.73 m<sup>2</sup>)**    | **Men HCT (%)**  | **Women HCT (%)** |

vs

**Table 1. Physicochemical properties and ADME of gabapentin for oral model construction**

| **Physicochemical properties**    |                             |

**Comment by Yuri05** [comment]
exactly, that seems to be the reason
