### ISSUE TITLE
Wrong pipe symbol ?

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#762]
@abdullahhamadeh 
From PR #760 , did you mean `%||%` instead of the `%>%` from `{magrittr}` package ?
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/1ae0849ffd6cb312b794cc4abae9765ad1f48998/R/qualification-ddi.R#L133

**Comment by pchelle** [comment]
Okay
Then, we need to declare it comes from `dplyr` using `dplyr::%>%` I think.
Otherwise, if the package is not loaded by the user while running DDI workflows, they'll get the following error: `could not find function "%>%"`

**Comment by abdullahhamadeh** [comment]
Ok. Probably simpler to just change that line to 
`mechanism = getMechanismName(ratioList[[pkParameter]]$mechanism), `

Can you do this in PR #763 ?

**Comment by pchelle** [comment]
Since the issue is not related at all, I made a separate PR #764
