### ISSUE TITLE
Workflow folder name

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#77]
I have started a workflow yesterday and today (R closed and reopend in the meanwhile).
However the workflow folder is called the same all the time: `Workflow_20200314_181342`

**Comment by msevestre** [comment]
@Yuri05 Please assign @abdullahhamadeh and @pchelle to ensure they get notifications of bugs

**Comment by msevestre** [comment]
@pchelle Do you create some kind of RData file that is loaded again? If yes, this is probably the reason

**Comment by pchelle** [comment]
Since the first issue we obtained with .RData files, I haven't relied on any RData file for the workflow instances.
The bug is in the nomenclature: the folder name has become fixed and should be updated every time the workflow is initialized
I'll fix that asap

**Comment by msevestre** [comment]
Tried to run the same workflow twice on my machien
```
> source('C:/tests/9.0/SA/Test03/Input/test_03.R')
[1] "17/03/2020 - 16:51:04 : Path: 'C:/tests/9.0/SA/Test03/WorkingDir/Workflow_20200317_165020' already exists."
Error in logErrorThenStop(messages$warningExistingPath(path)) : 
  Path: 'C:/tests/9.0/SA/Test03/WorkingDir/Workflow_20200317_165020' already exists.
```
