### ISSUE TITLE
AdjustTitlePage seems not to work

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#777]
[Qualification.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/8489163/Qualification.zip)
`createQualificationReport(qualificationRunnerFolder = "C:/QualificationRunner_11.0.114", pkSimPortableFolder = "C:/PK-Sim_11.0.123/", versionInfo = QualificationVersionInfo$new("1.1", "11.0", "2.3"))`

Created reports:
[report.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/8489177/report.zip)

**Comment by pchelle** [comment]
Qualification Runner sends the file `titlepage.md` to `re_input/Intro` instead of `re_input/Content`

**Comment by msevestre** [comment]
That's because this file is referenced in the Intro paragraph. Why do we have an Intro folder and a Content folder?
@Yuri05 do you remember?

**Comment by Yuri05** [comment]
>Why do we have an Intro folder and a Content folder?

No idea

**Comment by msevestre** [comment]
Isn;t it becaue we were merging all content together and then adding Intro at the top at some point?

**Comment by msevestre** [comment]
@pchelle How do you deal with the Intro folder in the reporting engine? Intro and Section Folder seems to behave quite the same . What is the difference in the code on your side?

**Comment by msevestre** [comment]
ok. So let's leave it as is for now. This file should definitely be at the top as is. I think this should work just fine then
