### ISSUE TITLE
DDI table artifact does not have a caption

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#783]
Currently the DDI Table artifact (supposed to be Table 4 below) does not have a title/caption.
For PK Ratio, the value in the field `Title` is used for that artifact. 
@Yuri05 
Should we use the same here ? (this would be "Table 4: CYP3A4 DDI")

Table 2: Summary table for CYP3A4 DDI DDIRatio-1 AUC

|AUC                          |Number |Ratio [%] |
|:----------------------------|:------|:---------|
|Points total                 |6      |-        |
|Points within Guest *et al.* |4      |66.67     |
|Points within 2 fold         |5      |83.33     |

<br>
<br>

Table 3: Summary table for CYP3A4 DDI DDIRatio-1 CMAX

|CMAX                         |Number |Ratio [%] |
|:----------------------------|:------|:---------|
|Points total                 |6      |-        |
|Points within Guest *et al.* |4      |66.67     |
|Points within 2 fold         |4      |66.67     |

<br>
<br>

|DataID |Perpetrator                                                                     |Victim        |Predicted AUC Ratio |Observed AUC Ratio |Pred/Obs AUC Ratio |Predicted CMAX Ratio |Observed CMAX Ratio |Pred/Obs CMAX Ratio |Reference          |
|:------|:-------------------------------------------------------------------------------|:-------------|:-------------------|:------------------|:------------------|:--------------------|:-------------------|:-------------------|:------------------|

**Comment by Yuri05** [comment]
`Summary table for CYP3A4 DDI` (same as for othe tables).

By the way, `CYP3A4 DDI` is the plot title from the qualification plan I guess - but what is "DDIRatio-1" 
(e.g. `Table 2: Summary table for CYP3A4 DDI DDIRatio-1 AUC`)?

Better would be smthg like this: `Summary table for <Plot title> - <PK Parameter> Ratio`, 
e.g. `Table 2: Summary table for CYP3A4 DDI - AUC Ratio`
