### ISSUE TITLE
DDIRatioPlot: Plot Guest criterion in the total plotting area

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#784]
Referring to exemplary output: https://github.com/Yuri05/TestReport/blob/main/Report_01/report.md Figure 1 and 2 for example. Guest criterion lines stop before end of plotting area.

**Comment by pchelle** [comment]
@Yuri05 
Wondering if this should be taken care of as `tlf` option/parameter ?
Basically, `ggplot2` likes to use a white space between the displayed data and axes but vertical, horizontal and diagonal lines are not affected by this feature.
The white space can be removed using the `ggplot2` function `expansion`
https://ggplot2.tidyverse.org/reference/expansion.html

**Comment by pchelle** [comment]
The following PR should fix this
https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/251

**Comment by Yuri05** [comment]
fixed with the TLF-PR. Closing

**Comment by Yuri05** [comment]
In some plots it does not work, e.g. see just created DDI-CYP3A4 report:
https://github.com/Yuri05/TestReport/blob/main/Report03_DDI_CYP3A4/report.md

![grafik](https://user-images.githubusercontent.com/25061876/170138454-e2cbe941-436e-49bc-a9b7-3102664c066f.png)
![grafik](https://user-images.githubusercontent.com/25061876/170138514-87cbf68c-0989-4da9-8105-dfca9d14e337.png)
