### ISSUE TITLE
Speed up build time by introducing code coverage and vignettes build on nightly

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#806]

**Comment by Yuri05** [comment]
Good idea. Just please keep artifacts (R package) also in non-nightly builds

**Comment by msevestre** [comment]
This is going to be very confusing. We will have different numbers etc.. I would not do this

**Comment by Yuri05** [comment]
you could replace the build number in non-nightly e.g. with 99999 Then it would be immediately clear what is what.
I use the package from PRs quite often to see how the package behaves.

**Comment by msevestre** [comment]
Ok....
