### ISSUE TITLE
DDI Ratio plots: The (large) legend is truncated.

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#821]
Example from here: https://github.com/Yuri05/TestReport/blob/main/Report03_DDI_CYP3A4/report.md#1225

![image](https://user-images.githubusercontent.com/26569320/173577357-14da5333-f24c-43c2-9c5c-4532a5ca140b.png)

**Comment by Yuri05** [comment]
yep. some entries at the top of the legend are cut off as well:
![grafik](https://user-images.githubusercontent.com/25061876/174592661-eb0336f4-61dd-40d8-8b1e-f22a58252a27.png)

**Comment by pchelle** [comment]
If that is okay, we can leverage the function we created for updating the plot dimensions based on legend size (#775)
The idea would be to use the max between initial dimension and legend dimension for preventing truncated long legends.
> I tested updating the legend font but it does not work that well, because spacing between legend entries also needs scaling
