### ISSUE TITLE
Duplicated figures reported (?) in MeanModel/Population-Workflows 

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#823]
Unsure if this is a bug though:

Example from: https://github.com/Yuri05/TestReport/blob/main/Report_02_Pediatric_CYP3A4/My_report.md 

There are duplicated figures reported, the second figure should have been in linear y-scale. However this may have been wrongly set in the snapshot model file.

![image](https://user-images.githubusercontent.com/25530079/173779118-877f429e-a1f8-4a3f-a789-1ea04c909739.png)

**Comment by Yuri05** [comment]
Yep, it's a bug. The 2nd plot must be in linear scale.
Matlab-RE handled this correctly (compare https://github.com/Open-Systems-Pharmacology/OSP-Qualification-Reports/blob/master/Pediatric_Qualification_Package_CYP3A4_Ontogeny/report.md#24-alfentanil-concentration-time-profiles-in-children )
