### ISSUE TITLE
DDI-Ratio plot: change default theme

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#826]
Currently DDI Ratio plots look like this:
![grafik](https://user-images.githubusercontent.com/25061876/174991960-c1e897e7-b99b-4a58-ba25-c1b7ec00de9e.png)

PK-Ratio plots look like this:
![grafik](https://user-images.githubusercontent.com/25061876/174992783-0baba688-b1b1-45ea-9fc6-1740755326b6.png)

I think the default symbol size for the DDI-Ratio plots should be the same as for PK-Ratio plots.

Question: (@sfrechen @AndreDlm @Incei) should the symbols in both plot types be filled (like now) or not (like before, compare below)?
![grafik](https://user-images.githubusercontent.com/25061876/174993207-45a61fd6-1fc5-4503-88c1-582c77676bae.png)

**Comment by sfrechen** [comment]
default can be filled.

**Comment by sfrechen** [comment]
> I am in favor of empty symbols as they can be visually distinguished more easily when they overlap

Good point. Agree.

**Comment by Incei** [comment]
Unfilled would indeed be more informative when there is overlap.

**Comment by pchelle** [comment]
Here are samples of the updated plots after fix
__PK Ratio__
![1_pk_ratio_plot_AUC](https://user-images.githubusercontent.com/45343665/175314960-0f96dc35-e7a2-4796-b249-7d0754cd1ae7.png)
__DDI Ratio__ 
![DDIRatio_1_ddi_ratio_plot_AUC_predictedVsObserved](https://user-images.githubusercontent.com/45343665/175319932-7ba45c81-479f-48f3-ab56-6dd25af80149.png)

**Comment by AndreDlm** [comment]
Looks good, thanks @pchelle
