### ISSUE TITLE
Observed data not properly read (anymore)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#853]
[37_ObservedData.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/9047826/37_ObservedData.zip)
Using this observed data in a population workflow (here an example to reproduce: [bug_data.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/9047902/bug_data.zip) )
* RE **2.0.171** - no problem
* RE **2.0.185** (with the same versions of all other packages as with RE 2.0.171)
First the warning below comes multiple times (for each simulation set where this observed data is used):
```
Warning: In source:
'time', 'dv' columns are not all present in observed dataset columns: 'SID', ',"time","tad","dv","dvname","dvunit","grp","sex","age","weight","height","bmi"'.
```
After that, plotTimeProfiles-Task crashes:
```
[1] "05/07/2022 - 18:11:14 : Plot Time profiles and Residuals task for Filmcoated_tablet_400mg_sd"
Error in x[[jj]][iseq] <- vjj : replacement has length zero

> traceback()
10: `[<-.data.frame`(`*tmp*`, selectedRows, timeColumn, value = numeric(0))
9: `[<-`(`*tmp*`, selectedRows, timeColumn, value = numeric(0))
8: loadObservedDataFromSimulationSet(structureSet$simulationSet, 
       logFolder)
...
```

I guess the crash is the follow up of "observed data columns not found".

**Comment by pchelle** [comment]
This is an interesting bug, there is actually one more column in the data than in the header and `read.csv` is smart enough to assume the first value is the row name

File content is:
| SID| time| tad|    dv|dvname |dvunit | grp| sex| age| weight| height| bmi||
|---:|----:|---:|-----:|:------|:------|---:|---:|---:|------:|------:|---:|---:|
|   1|   1|   60|  60| 0.002|parent |umol/L |   1|   1|  39|     72|    165|  26|

While data.frame becomes:

|(row.name)| SID| time| tad|    dv|dvname |dvunit | grp| sex| age| weight| height| bmi|
|---:|----:|---:|-----:|:------|:------|---:|---:|---:|------:|------:|---:|---:|
|   1|   1|   60|  60| 0.002|parent |umol/L |   1|   1|  39|     72|    165|  26|

**Comment by Yuri05** [comment]
>there is actually one more column in the data than in the header and read.csv is smart enough to assume the first value is the row name

Indeed, lol. So what you describe is what happened in the previous version of RE? Because this would explain why it did not crash before.
Actually RE should detect that CSV file is invalid and throw an error in such a case (maybe there is an option in read.csv which disables this weird "artificial intelligence"?)

But I also wonder what happend in the last few weeks (between RE 2.0.171 and 2.0.185) that results in this change of behaviour?

**Comment by pchelle** [comment]
In the last few weeks, I had made a PR to select the right reader based on consistency in columns per rows.
Since the header had one column less than the next line, the selection preferred `read.table` instead of `read.csv` which would have been used in the previous versions.

I need to include an additional check into the selection process: *"if there is a header, we allow that it has one less column than the next lines"*
