### ISSUE TITLE
Avoid "shrinking" of the plot area if the legend is above/below the plot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#861]
This issue was fixed e.g. for PK Ratio plots (https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/758) but it still happens in MEanModel/Population workflows for many plot types (time profiles, residual plots, histograms, ...)
Plot area must keep its size for ALL plot types.
![grafik](https://user-images.githubusercontent.com/25061876/177748808-8c13638f-7424-4f20-8bf0-33037db45921.png)

**Comment by pchelle** [comment]
Should be fixed by PR #924

**Comment by Yuri05** [comment]
For some images it works good; for many images it does not.
S. the report here: https://github.com/Yuri05/TestReport/tree/main/Report_07_Population_Pediatric_Raltegravir (Report inputs are in the same folder)

<details><summary><b> Some of the problematic images</b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/209839414-91502374-c5eb-478a-b77e-f41f4c614697.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839536-346a08a3-0467-4f73-ab4a-af40bca284c0.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839571-bafa9936-cb62-4079-aebd-c535726d6a74.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839595-caa551f6-d927-472a-bc47-3e6759082036.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839632-888fe0b4-b517-437b-9756-b62aa20dc2bc.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839653-9fa9efa7-9f72-442e-861d-c71220cf3d22.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839676-2b6cd61c-678e-410b-9c4e-0e6f5162ef9e.png)

![grafik](https://user-images.githubusercontent.com/25061876/209839718-b9767dc1-db84-4850-9248-157df36be2b3.png)

</details>
