### ISSUE TITLE
PopulationWorkflow / TimeProfile: new input (StatisticsType)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#864]
Introduce new optional input **StatisticsType** with possible values:
* **5th-95th percentile** ==> plot 5th-95th range and median 
* **Arithmetic mean** ==> Plot arithmetic mean and mean+-SD range
* **Geometric mean** ==> Plot geometric mean and */geoSD range

If not given: plot 5-95 range + median (compare https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/862)

**Comment by pchelle** [comment]
Should be fixed by PR #939
