### ISSUE TITLE
Population Workflow / Time profiles: Legend

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#865]
Is it possible to combine the legend for 5-95 range and for the median in the same legend entry?
![grafik](https://user-images.githubusercontent.com/25061876/177753473-e3b492cf-0b5f-4ea4-8730-f93c64b7eb50.png)

The legend entry should be then **Simulated median and 5<sup>th</sup>-95<sup>th</sup> percentiles for ...**
(also <sup>th</sup> as superscript!)

**Comment by pchelle** [comment]
I can think of 2 possible solutions for this. @Yuri05  let me know which one sounds better

1- Use unicode characters for superscripts "t" and "h": `"\u1d57\u02b0"` 
> Rendering for both plots and report: 5-95ᵗʰ

2- Use html tags `<sup>th</sup>` and allow `ggtext::element_markdown` in `{tlf}` package
> Rendering for both plots and report: 5-95<sup>th</sup>

**Comment by Yuri05** [comment]
ggtext is currently not in our validated packages list - so let's try the unicode solution

**Comment by pchelle** [comment]
Should be fixed by PR #939
