### ISSUE TITLE
Population Workflow / Time profile: Observed data legend caption

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#871]
In the plots with the reference population: it's not clear if the observed data belongs to the **reference** population or not.

We could e.g. add the population name in brackets for the observed data in the same manner as for the simulated data.

<img width="500" src="https://user-images.githubusercontent.com/25061876/177757904-cf96bc93-6191-4acf-9f3b-5b39ae7a0e48.png">

**Comment by pchelle** [comment]
@Yuri05 
The CRAN package `{ggtext}` has functions that can be used to render captions, labels and watermark from markdown/html text.

If interested, we could use it to render __reference__ populations in bold, italic or/and in different colors.
The change would also allow simple ways to include <sub>subscript</sub> and <sup>superscript</sup> in the titles, captions, etc. 
We could also use the feature to include images in watermark

**Comment by pchelle** [comment]
Should be fixed by PR #939
