### ISSUE TITLE
MeanModel/PopWorkflow: Colors and symbols are the same for all outputs of observed data in GOF plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#874]
![grafik](https://user-images.githubusercontent.com/25061876/177759679-6fb17aac-2852-4872-9a62-a578c9c1dd0b.png)

**Comment by pchelle** [comment]
Should be fixed by PR #939 
Also PR #947 provide additional ways of defining different colors
