### ISSUE TITLE
Excel template: definition and Generation of Outputs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#882]
After #881 is implemented:

Redesign the excel template:
* Exactly 1 sheet with the outputs definition (rename it in the template from **Outputs_1** to **Outputs**
* For each SimulationSet: enter the List of Output names (e.g. comma separated or semicolon separated)
![grafik](https://user-images.githubusercontent.com/25061876/177816252-177960ef-4a44-474f-99b3-ee119977a841.png)

The Outputs must be generated only once then (e.g. just **Output1** instead of _SimSet1.Output1_, _SimSet2.Output1_, ...)

**Comment by pchelle** [comment]
Fixed by PR #882
