### ISSUE TITLE
Missing plot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#886]
Pop workflow / Residuals across all simulation: QQ-plot is missing (the very last plot in the attached report).
The plot caption is there, but no plot created
[bug_QQPlot.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/9065762/bug_QQPlot.zip)
.

**Comment by pchelle** [comment]
This seems to have been fixed with the refactoring of PR #924

**Comment by Yuri05** [comment]
ok, let's close then
