### ISSUE TITLE
MeanModel/PopWorkflow: Residuals across all simulation: add missing plot types

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#888]
At the moment we have only histogram of residuals and qq-plot here.
Other GOF plots are missing and should be added as well:
* Predicted vs observed
* Residuals vs observed
* Residuals vs time

Issue #887 applies for these plot types as well:
* Split by output
* Colouring by SimulationSet the same in all plots

**Comment by pchelle** [comment]
Should be fixed by PR #939
