### ISSUE TITLE
population/parallelComparison workflow: the new logging crashes in the PlotTimeProfiles task

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#907]
Got the error message below for one workflow. 
```
i Info	Starting run of Plot Time profiles and Residuals task for PO450mg
Error: Error in gsub(pattern = highlightWrap[1], x = as.character(text), replacement = "", : input string 1 is invalid UTF-8
```
Unfortunately I cannot upload the workflow inputs here. IT is population/parallelComparison workflow.
The error must come from 
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/1a0c1e46f0ebf6cf9a52b0bbaf0e5da545bb127d/R/messages.R#L310

**Comment by pchelle** [comment]
From the error message, you are right.
I thought the highlighting process and its removal were robust enough, but it seems not. 
Here, I am guessing the `gsub` replacement create an invalid character because of a greek letter or a utf specific character

I'll fix that ASAP
