### ISSUE TITLE
Crash in the Sensitivity task (popWorkflow / parallelComparison)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#910]
[4mail.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/9301788/4mail.zip)

```
i Info	Starting run of Sensitivity Analysis task for Theophylline
Error: Error in `vec_as_location()`:
! `...` must be empty.
x Problematic argument:
* call = call
```

**Comment by pchelle** [comment]
I could not reproduce with my environment.
The link below suggests that the bug comes from the version of the package `{vctrs}` 
https://community.rstudio.com/t/code-error-grouping-and-generating-of-variables-not-possible-dplyr/143774

> I think that package is internally used by `{dplyr}` that may be potentially called somewhere by `{ospsuite}` during the sensitivity analysis

**Comment by Yuri05** [comment]
ok, after I have updated all CRAN packages and all OSP packages to the latest version, the error disappeared. Closing.
