### ISSUE TITLE
Missing Y2 in plots of Qualification Report (Workflow.R)

### ISSUE THREAD

**Issue by GhazalMontaseri** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#934]
I tried to generate the qualification report for Fluconazole model based on files provided here:
https://github.com/Open-Systems-Pharmacology/Fluconazole-Model

However, instead of Workflow.m I have used workflow.R as described here:
https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/qualification-workflow.html#template

I have PK-Sim portable version 11 and latest version of 'QualificationRunner'. The issue is in concentration-time profiles with double Y axes like Y and Y2 (like the third plot in section 3.3.1), I got a plot with only Y and not both Y and Y2. Can you please help me with this issue?

**Comment by Yuri05** [comment]
I guess you are talkimg about this plot: https://raw.githubusercontent.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/master/Fluconazole/images/003_3_Results_and_Discussion/003_3_3_Concentration-Time_Profiles/001_3_3_1_Model_Building/003_plotTimeProfile.png (here created in Matlab.)
How does the plot look like in your case?

**Comment by GhazalMontaseri** [comment]
This is my plot, both observations and model prediction on Y2 axis are missing.

![no_Y2](https://user-images.githubusercontent.com/30312003/192791783-a37e9927-65e4-41ba-88c3-8c3cf0f563e0.png)

**Comment by GhazalMontaseri** [comment]
anThis is my plot, both observations and model prediction on Y2 axis are missing.

![no_Y2](https://user-images.githubusercontent.com/30312003/192791783-a37e9927-65e4-41ba-88c3-8c3cf0f563e0.png)

it seems that my issue is not specific only for the fluconazole report but for a simple template 
https://github.com/Open-Systems-Pharmacology/Evaluation-plan-template

when I add a second plot on Y2, I cannot get it in the generated pictures from the reporting engine.

**Comment by pchelle** [comment]
This is a limitation of the current versions of `{ospsuite.reportingengine}` and `{tlf}` packages that cannot handle Y2 axis yet.
For this reason, every data on Y2 axis are skipped in the figure.
As a workaround, I suggest to plot the data in Y2 axis as a separate figure.

**Comment by GhazalMontaseri** [comment]
Thanks Pierre for your answer. May I ask if this is a limitation only for R users (worflow.R)? because in the original qualification report which was generated using Matlab (workflow.m) Y2 exists.

https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/tree/master/Fluconazole

Do you suggest me to use Matlab instead of R as an option to solve this issue?

**Comment by pchelle** [comment]
Yes, it is currently a limitation for R users only.
Matlab can handle Y2 axis, so using Matlab instead of R may be an option as well.
However, I don't know if there could be compatibility issues with between Matlab and latest OSPSuite versions.
@Yuri05 may have more insight about this aspect

**Comment by GhazalMontaseri** [comment]
thanks a lot Pierre, may I ask if you have a plan to solve it for R users?

**Comment by pchelle** [comment]
@Yuri05 , please correct me if I am wrong

>     1. if you have a plan to solve it for R users?

Yes, we intend to add the Y2 axis feature for time profile plots. However, I don't know in terms of timeline exactly when we will fix that.

>     2. where I may find instructions for generating a qualification report based on MATLAB?

You will find the instructions for using the Matlab qualification framework [here](https://github.com/Open-Systems-Pharmacology/QualificationPlan/releases/tag/v2.3)

**Comment by GhazalMontaseri** [comment]
Hello Pierre, thanks for your supports. For the moment, I switch to MATLAB. 
My questions is how can I install 'Reporting engine 3.0.1.53' as MATLAB source code library (alternative no. 1 according to the link you have sent me)? There is no .exe file for installation.
When I run the 'Workflow.m' file, it calls many functions and since they are not at the same folder as 'workflow.m' or the library is not installed I get errors saying 'unrecognize function or variable ....'

thanks for your supports.

**Comment by Yuri05** [comment]
@GhazalMontaseri Matlab Reporting Engine is just zipped Matlab source code .
You need to unzip it and add the Felder with the source Code (with subfolders) to the Matlab search path

**Comment by GhazalMontaseri** [comment]
thank you so much Juri, I used ''addpath'' command to add all subfolders to the search path.

**Comment by GhazalMontaseri** [comment]
@Yuri05 Hello Yuri, may I ask if in the new release, adding the Y2 axis feature for time profile plots in the qualification report workflow.R, has been resolved?

**Comment by Yuri05** [comment]
Hello @GhazalMontaseri  , this will be fixed in the next release, which will be hopefully available till the end of March.

**Comment by Yuri05** [comment]
Dear @GhazalMontaseri , new release with the fixed Y2-issue is available now: 
https://github.com/Open-Systems-Pharmacology/QualificationPlan/releases/tag/v3.1

**Comment by GhazalMontaseri** [comment]
Thanks @Yuri05 .

**Comment by GhazalMontaseri** [comment]
Hello @Yuri05, can you please help me how I may modify/increase size of  points in the generated Gof plots from the qualification report? As you see below the points are very small.
![2_gof_plot_predictedVsObserved](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/30312003/8b372e13-8763-4c6e-86b2-73fd32b5d056)

**Comment by Yuri05** [comment]
Hi @GhazalMontaseri , 
try to use the new default theme:
* download the file https://raw.githubusercontent.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/develop/inst/extdata/re-theme.json 
* In you Workflow.R, before `runWorkflow()`, load this theme
```
...
setDefaultThemeFromJson("C:/Temp/re-theme.json")
workflow$runWorkflow()
...
```
If the symbol size is still too small, you can modify the downloaded theme file and increase it, e.g.
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/25061876/4026e8e8-7f5e-4854-bf78-76070b311591)

**Comment by Yuri05** [comment]
You can also modify the theme properties programmatically, s.
https://www.open-systems-pharmacology.org/OSPSuite.ReportingEngine/articles/plot-settings.html

E.g. 
```
...
jsonFile <- system.file("extdata", "re-theme.json",  package = "ospsuite.reportingengine")
reTheme <- tlf::loadThemeFromJson(jsonFile)
reTheme$plotConfigurations$plotObsVsPred$points$size=8
setDefaultTheme(reTheme)

workflow$runWorkflow()
...

```

**Comment by Yuri05** [comment]
Please note, that those changes are **global** and will apply to all workflows which are executed after the setting of the new theme.
Plot settings can also be changed locally only for the workflow being executed. However not all such settings are (easily) accessible.
E.g. I don'r know how to change the symbol size for the GOF plots of the given workflow. Maybe @pchelle could advice.

**Comment by GhazalMontaseri** [comment]
Hello @Yuri05 , I tried this in my workflow.R:

jsonFile <- system.file("extdata", "re-theme.json",  package = "ospsuite.reportingengine")
reTheme <- tlf::loadThemeFromJson(jsonFile)

reTheme$plotConfigurations$plotObsVsPred$points$size=8 --> for GoF plots
reTheme$plotConfigurations$plotTimeProfile$points$size=40 --> for time profiles
  
 setDefaultTheme(reTheme)
workflow$runWorkflow()

However, while point size in the GoF plot has been increased this is not the case for the time profile plot (second Y-axis has some points but very small)
![2_gof_plot_predictedVsObserved](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/30312003/214b2950-399a-4749-9407-e8a14c7f61b3)

![1_time_profile_plot_Rifampicin_Midazolam_DDI_test_DDI_Treatment___Rifampicin_Midazolam___Yu_2004__CYP3A5_s3_s3__parameters](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/assets/30312003/fd2486b2-8aad-49ac-af42-cf57adf119fb)

**Comment by Yuri05** [comment]
>However, while point size in the GoF plot has been increased this is not the case for the time profile plot (second Y-axis has some points but very small)

It's a bug :(

You can try the latest **development** version of the reporting engine where this bug was fixed.
For this, you need to install some CRAN packages first:
* showtext
* sysfonts
* data.table
* svglite

Then install the latest development version of the OSP packages:
* https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip?pr=false
* https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip?pr=false
* https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip?pr=false
* https://ci.appveyor.com/api/buildjobs/4xl3jltyxcmqi62u/artifacts/ospsuite.reportingengine_2.2.266.tar.gz

**Comment by GhazalMontaseri** [comment]
Thanks @Yuri05 , any plan to release the **validated** reporting engine package with this bug being fixed in near future?

**Comment by Yuri05** [comment]
Hopefully till the end of summer

**Comment by GhazalMontaseri** [comment]
Hello Juri,
any update on reportingEngine package in which the issue with Y2 (dual axes) plots has been solved?
