### ISSUE TITLE
Qualfication report / GOF plot: valid simulation output path is not accepted

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#940]
When running the qualification plan from https://github.com/Christoph27/Tefibazumab-Model (under Evaluation): 
The error message below comes:

 ```
Error in validateIsPathInSimulation(allOutputPaths, simulation) : 
  In createQualificationReport:
'Organism|PeripheralVenousBlood|Tefibazumab__Kd_Zhou2003|Plasma (Peripheral Venous Blood)' is an invalid output path for simulation 'Tefibazumab_2mgkg_Kd_Zhou2003'.In createQualificationReport:
'Organism|PeripheralVenousBlood|Tefibazumab|Plasma (Peripheral Venous Blood)' is an invalid output path for simulation 'Tefibazumab_2mgkg_Kd_Zhou2003'. 

```

However the path **Organism|PeripheralVenousBlood|Tefibazumab__Kd_Zhou2003|Plasma (Peripheral Venous Blood)** is valid for the given simulation.

Also the error message is printed 2 times

**Comment by Yuri05** [comment]
@Christoph27 FYI

**Comment by pchelle** [comment]
@Christoph27 
Thanks for the zip, I was able to reproduce and investigate.
There are actually a series of 2 bugs:

1- `validateIsPathInSimulation` should only return the paths not in the simulation __and__ in the same sentence.
Here, there is a confusing almost duplicate message. Actually only `'Organism|PeripheralVenousBlood|Tefibazumab|Plasma (Peripheral Venous Blood)'` was the invalid path.
2- The invalid path is a bug from the function `getOutputsFromConfigurationPlan` which aims at checking which outputs should be used prior running the Qualification Workflow. Output paths from previous simulations are kept as outputs of the current simulations while they should not.
