### ISSUE TITLE
Template Starter: Issue when the PKSim Portable path has a space 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#954]
```
Error in validateCommandStatus(command, status) : 
  Command : '"C:/dev/QualificationRunner/src/QualificationRunner/bin/Debug/net472/QualificationRunner.exe" -i "C:/dev/Qualification-CKD/Qualification/input/qualification_plan.json" -o "C:/dev/Qualification-CKD/Qualification/re_input" --norun -p C:/dev/Releases/v11/PK-Sim 11.0.150 -n "report-configuration-plan" -f' returned Error Status 1
```

Somehow, the path is not using "" and this does not work

FYI @Yuri05

**Comment by Yuri05** [comment]
`-p C:/dev/Releases/v11/PK-Sim 11.0.150`
PK-Sim path is not in quotes and has a blank...

**Comment by msevestre** [comment]
Yes I know. But
This should be done at the reporting engine level right? I am calling the startQualificatonRunner method

**Comment by Yuri05** [comment]
ah ok, I see.
Then it's a bug indedd. PK-Sim folder should be taken into double quotes
https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/527b1ced5f2d69aad8e682f8a0e669b724116145/R/utilities-qualification.R#L410
