### ISSUE TITLE
Pandoc options

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#963]
In the current version of pandoc, option `self-contained` has been deprecated in favor of `embed-resources` and `standalone`.
This currently shows the following warning when pandoc is used:

```
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
```

Should we use these new arguments instead ?

**Comment by pchelle** [comment]
Also, I have tested some Pandoc **extensions**.
Would it be worth allowing the extension `tex_math_dollars` in the conversion from md to docx ?

The feature allows the conversion of math equations written in LateX within `$$...$$` as docx equations (if not allowed, the equations are written verbatim).

To use such an extension, the additional argument `--from=markdown+tex_math_dollars` needs to be passed to Pandoc

**Comment by Yuri05** [comment]
At the moment we are still using the older pandoc version 2.9.2.1
At some time point I tried a newer pandoc version - and it produced a lot of garbage.
We can try with the latest version and check if it works correctly now.

Regarding the extensions: do we need any extra installations for that?

**Comment by pchelle** [comment]
After tests of Pandoc version 2.9.2.1

- Option `--embed-resources` is not available, conversion do not work if option is included
```r
Unknown option --embed-resources.
Try pandoc.exe --help for more information.
Error in (function (input, format, ext, exec, cfg)  : conversion failed
```
- Extension `+tex_math_dollars` was available and converted LateX formatted equations

**Comment by pchelle** [comment]
An interesting finding was that I was also to modify the Pandoc version used for the conversion !
The function `find_pandoc` from the `{rmarkdown}` package can update the pandoc path and can be tested using `pandoc_exec()`. 
The process below can be used prior in a workflow script to set the appropriate Pandoc version

I had both versions `2.19` and `2.9.2.1`
```r
# If latest version is cached, then the latest version will still be used instead
# the path is directory where your `pandoc.exe` file is located
> rmarkdown::find_pandoc(cache = FALSE, dir = "path/to/pandoc-2.9.2.1")
$version
[1] '2.9.2.1'
$dir
[1] "path/to/pandoc-2.9.2.1"

# If you want to test the update
> rmarkdown::pandoc_exec()
[1] "path/to/pandoc-2.9.2.1"
```
