### ISSUE TITLE
Population workflow/Time profiles: Invalid axis caption

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#969]
S. the reports here: https://github.com/Yuri05/TestReport/tree/main/Report_07_Population_Pediatric_Raltegravir (Report inputs are in the same folder)

In the report created with R3.6, Y-axis captions of time profile plots are invalid, e.g.:
https://github.com/Yuri05/TestReport/blob/main/Report_07_Population_Pediatric_Raltegravir/Report/Report.md#31-time-profiles-and-residual-plots-for-filmcoated_tablet_400mg_sd

![grafik](https://user-images.githubusercontent.com/25061876/209847667-08f39b74-beba-4db0-a843-122d96973434.png)

In the R4-report looks good.

**Comment by pchelle** [comment]
@Yuri05 
Do we still support R3.6 (now build is performed only for R4) ?

**Comment by pchelle** [comment]
Closing since R3.6 is not supported any longer and the issue does not appear starting R4.0
