### ISSUE TITLE
PKRatio Plot: irritating error message if required observed data columns are not found

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#992]
E.g. in the example attached, **AUC_tEnd** was selected as PK-Parameter; however the required columns **AUC_tEnd Avg** and **AUC_tEnd AvgUnit** are missing in the corresponding observed data file. Then the error message below comes.
[PKRatioCrash.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/10743161/PKRatioCrash.zip)

Would be much better to get something like "At least one of the required columns **AUC_tEnd Avg** and **AUC_tEnd AvgUnit** is missing in the observed data file **MyObservedData.csv**"

```
i Info	Starting run of Plot PK Ratio task
15/02/2023 - 13:51:26
! Warning	argument is not a character vector
	
> Error Trace
	 ↪ createQualificationReport(qualificationRunnerFolder = "C:/Temp/11.1beta/QualificationRunner_11.1.104")
	  ↪ workflow$runWorkflow()
	   ↪ self[[plotTask]]$runTask(self$configurationPlan)
	    ↪ self$getTaskResults(configurationPlan, self$settings)
	     ↪ getQualificationPKRatioData(pkRatioPlan, configurationPlan, settings)
	      ↪ getPKRatioForMapping(pkRatioMapping, pkParameterNames, configurationPlan, 
	       ↪ ospsuite::toUnit(quantityOrDimension = pkParameter$dimension, 
	        ↪ .encodeUnit(targetUnit)
 Error: argument is not a character vector 
```

**Comment by pchelle** [comment]
Yes, I numbered the related issue instead of the PR...
